import { supabase } from './supabase.js';
import { formatClinicalRecordForDocument } from './clinicalRecordFormat.js';
const DOCUMENT_FIELDS='id,client_id,client_ref,client_name,title,document_type,report_date,status,content,source_manifest,purpose,recipient,period_start,period_end,version,finalized_at,storage_path,original_filename,mime_type,size_bytes,created_at,updated_at';
function requireSupabase(){if(!supabase)throw new Error('Supabase is not configured');return supabase;}
async function requireUser(client){const {data,error}=await client.auth.getUser();if(error)throw error;if(!data?.user)throw new Error('Please sign in again');return data.user;}
async function authHeaders(){const client=requireSupabase();const {data,error}=await client.auth.getSession();if(error)throw error;const token=data?.session?.access_token;if(!token)throw new Error('Please sign in again');return {Authorization:`Bearer ${token}`,'Content-Type':'application/json'};}
async function apiError(response,fallback){let message=fallback;try{const payload=await response.json();message=payload?.error?.message||payload?.error||message;}catch{}const error=new Error(message);error.status=response.status;if(response.status===409)error.code='DOCUMENT_CONFLICT';throw error;}
export function presentClientDocument(row){if(!row)return null;return{id:row.id,clientId:row.client_id,clientRef:row.client_ref,clientName:row.client_name,title:row.title,documentType:row.document_type,reportDate:row.report_date,status:row.status,content:row.content||{},sourceManifest:Array.isArray(row.source_manifest)?row.source_manifest:[],purpose:row.purpose||'',recipient:row.recipient||'',periodStart:row.period_start,periodEnd:row.period_end,version:row.version||1,finalizedAt:row.finalized_at,storagePath:row.storage_path,originalFilename:row.original_filename,mimeType:row.mime_type,sizeBytes:row.size_bytes,createdAt:row.created_at,updatedAt:row.updated_at};}
export async function listClientDocuments(clientId){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('documents').select(DOCUMENT_FIELDS).eq('client_id',clientId).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(presentClientDocument);}
export async function findSessionSummary({clientId,sessionId}){const documents=await listClientDocuments(clientId);return documents.find(doc=>doc.documentType==='session_summary'&&doc.sourceManifest?.some(src=>src.sessionId===sessionId))||null;}
export async function getClientDocument({clientId,documentId}){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('documents').select(DOCUMENT_FIELDS).eq('id',documentId).eq('client_id',clientId).single();if(error)throw error;return presentClientDocument(data);}
export async function createClientDocumentDraft({client,title,documentType='clinical_summary',purpose='',recipient='',periodStart=null,periodEnd=null,content={},sourceManifest=[]}){const db=requireSupabase();const user=await requireUser(db);const {data,error}=await db.from('documents').insert({user_id:user.id,client_id:client.id,client_ref:client.id,client_name:client.display_name,title:title.trim(),document_type:documentType,status:'draft',purpose,recipient,period_start:periodStart||null,period_end:periodEnd||null,content,source_manifest:sourceManifest}).select(DOCUMENT_FIELDS).single();if(error)throw error;return presentClientDocument(data);}
export async function saveClientDocumentDraft(document,changes){const client=requireSupabase();await requireUser(client);const payload={title:changes.title?.trim()||document.title,document_type:changes.documentType||document.documentType,purpose:changes.purpose??document.purpose,recipient:changes.recipient??document.recipient,period_start:changes.periodStart??document.periodStart,period_end:changes.periodEnd??document.periodEnd,content:changes.content??document.content,source_manifest:changes.sourceManifest??document.sourceManifest,version:document.version+1,updated_at:new Date().toISOString()};const {data,error}=await client.from('documents').update(payload).eq('id',document.id).eq('client_id',document.clientId).eq('status','draft').eq('version',document.version).select(DOCUMENT_FIELDS).maybeSingle();if(error)throw error;if(!data){const conflict=new Error('This document changed in another tab. Reopen it before saving again.');conflict.code='DOCUMENT_CONFLICT';throw conflict;}return presentClientDocument(data);}
export async function deleteClientDocument(document){if(!document?.id||!document?.clientId)throw new Error('Open a valid client document before deleting it');if(document.status==='completed')throw new Error('Finalised documents cannot be deleted');const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('documents').delete().eq('id',document.id).eq('client_id',document.clientId).in('status',['draft','review']).select('id').maybeSingle();if(error)throw error;if(!data)throw new Error('This document could not be deleted. It may already be finalised or removed.');return true;}
export async function listDocumentSourceSessions(clientId){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('sessions').select('id,client_id,occurred_at,status,notes,notes_status,version,completed_at').eq('client_id',clientId).eq('status','completed').order('occurred_at',{ascending:false});if(error)throw error;return(data||[]).map(row=>({id:row.id,occurredAt:row.occurred_at,notes:formatClinicalRecordForDocument(row.notes),notesStatus:row.notes_status,version:row.version,completedAt:row.completed_at}));}
export async function listClientSummaryEvidence(clientId){const headers=await authHeaders();const response=await fetch('/api/ai/client-session-summary',{method:'POST',headers,body:JSON.stringify({clientId,preview:true})});if(!response.ok)return apiError(response,'Could not load reviewed Session Captures');const payload=await response.json();return payload.data?.availableSessions||[];}
export async function generateClientSessionSummary({clientId,lens='general',window='last_three',therapistGuidance='',anchorSessionId=null}){const headers=await authHeaders();const response=await fetch('/api/ai/client-session-summary',{method:'POST',headers,body:JSON.stringify({clientId,lens,window,therapistGuidance,anchorSessionId})});if(!response.ok)return apiError(response,'Could not generate the client summary');const payload=await response.json();return payload.data;}
export async function generateSessionSummary({clientId,sessionId,transcriptId}){const headers=await authHeaders();const response=await fetch('/api/ai/session-summary',{method:'POST',headers,body:JSON.stringify({clientId,sessionId,transcriptId})});if(!response.ok)return apiError(response,'Could not generate the session summary');const payload=await response.json();return payload.data;}
export async function finaliseClientDocument(document){if(!document?.id||document.status==='completed')throw new Error('Only draft documents can be finalised');const headers=await authHeaders();delete headers['Content-Type'];const response=await fetch(`/api/documents?finalize=${encodeURIComponent(document.id)}&expectedVersion=${encodeURIComponent(document.version)}`,{method:'POST',headers});if(!response.ok)return apiError(response,'Could not finalise this document');const payload=await response.json();return presentClientDocument(payload.document);}
export async function downloadClientDocument(document){if(!document?.storagePath)throw new Error('This document has not been finalised yet');const headers=await authHeaders();delete headers['Content-Type'];const response=await fetch(`/api/documents?download=${encodeURIComponent(document.id)}`,{headers});if(!response.ok)return apiError(response,'Could not download this document');const payload=await response.json();const link=window.document.createElement('a');link.href=payload.url;link.download=document.originalFilename||`${document.title||'document'}.pdf`;link.rel='noopener noreferrer';window.document.body.appendChild(link);link.click();link.remove();}
