import { supabase } from './supabase.js'

function requireSupabase() { if (!supabase) throw new Error('Supabase is not configured'); return supabase }
function mapCareItem(row) { return { id:row.id, clientId:row.client_id, kind:row.kind, body:row.body, status:row.status, origin:row.origin, provenanceSessionId:row.provenance_session_id, aiPromptVersion:row.ai_prompt_version, createdAt:row.created_at, updatedAt:row.updated_at } }
function careError(error) { const e = new Error(error?.message || 'Care request failed'); e.code = error?.code || 'CARE_REQUEST_FAILED'; if (String(error?.message||'').includes('client_care_items')) e.code='CARE_SCHEMA_UNAVAILABLE'; return e }
export async function listClientCareItems(clientId) { const db=requireSupabase(); const {data,error}=await db.from('client_care_items').select('*').eq('client_id',clientId).order('updated_at',{ascending:false}); if(error)throw careError(error); return(data||[]).map(mapCareItem) }
export async function createClientCareItem({clientId,kind,body,origin='clinician',provenanceSessionId=null,aiPromptVersion=null}) { const db=requireSupabase(); const {data:auth}=await db.auth.getUser(); if(!auth?.user){const e=new Error('Authentication required');e.code='UNAUTHENTICATED';throw e} const {data,error}=await db.from('client_care_items').insert({therapist_id:auth.user.id,client_id:clientId,kind,body:body.trim(),origin,provenance_session_id:provenanceSessionId,ai_prompt_version:aiPromptVersion}).select('*').single(); if(error)throw careError(error); return mapCareItem(data) }
export async function createClientCareItems(clientId,drafts) { const saved=[]; for(const draft of drafts) saved.push(await createClientCareItem({clientId,...draft})); return saved }
export async function updateClientCareItem(itemId,changes) { const db=requireSupabase(); const payload={}; if(changes.body!==undefined)payload.body=changes.body.trim(); if(changes.status!==undefined)payload.status=changes.status; if(changes.kind!==undefined)payload.kind=changes.kind; const {data,error}=await db.from('client_care_items').update(payload).eq('id',itemId).select('*').single(); if(error)throw careError(error); return mapCareItem(data) }
async function authenticatedHeaders() { const db=requireSupabase(); const {data}=await db.auth.getSession(); const token=data?.session?.access_token; if(!token){const e=new Error('Authentication required');e.code='UNAUTHENTICATED';throw e} return {'Content-Type':'application/json','Authorization':`Bearer ${token}`} }
export async function generateCareSuggestions({clientId,lensId='gentle_cbt',input,steering='',currentCare=[]}) { const response=await fetch('/api/ai/care-suggestions',{method:'POST',headers:await authenticatedHeaders(),body:JSON.stringify({clientId,lensId,input,steering,currentCare:currentCare.map(item=>({id:item.id,kind:item.kind,body:item.body,status:item.status}))})}); const payload=await response.json().catch(()=>({})); if(!response.ok){const e=new Error(payload?.error?.message||'Suggestions could not be generated');e.code=payload?.error?.code||'CARE_SUGGESTIONS_FAILED';throw e} return payload }
export async function transcribeCareAudio(audio) { const response=await fetch('/api/ai/transcribe',{method:'POST',headers:await authenticatedHeaders(),body:JSON.stringify({audio})}); const payload=await response.json().catch(()=>({})); if(!response.ok){const e=new Error(payload?.error?.message||'Dictation could not be transcribed');e.code=payload?.error?.code||'TRANSCRIPTION_FAILED';throw e} return payload.text||'' }
