import { supabase } from './supabase.js';

const DOCUMENT_FIELDS = 'id,client_id,client_ref,client_name,title,document_type,report_date,status,content,source_manifest,purpose,recipient,period_start,period_end,version,finalized_at,storage_path,original_filename,mime_type,size_bytes,created_at,updated_at';
function requireSupabase(){if(!supabase)throw new Error('Supabase is not configured');return supabase;}
async function requireUser(client){const {data,error}=await client.auth.getUser();if(error)throw error;if(!data?.user)throw new Error('Please sign in again');return data.user;}
async function authHeaders(){const client=requireSupabase();const {data,error}=await client.auth.getSession();if(error)throw error;const token=data?.session?.access_token;if(!token)throw new Error('Please sign in again');return {Authorization:`Bearer ${token}`};}
async function apiError(response,fallback){let message=fallback;try{const payload=await response.json();message=payload?.error||message;}catch{}const error=new Error(message);error.status=response.status;if(response.status===409)error.code='DOCUMENT_CONFLICT';throw error;}

export function presentClientDocument(row){if(!row)return null;return {id:row.id,clientId:row.client_id,clientRef:row.client_ref,clientName:row.client_name,title:row.title,documentType:row.document_type,reportDate:row.report_date,status:row.status,content:row.content||{},sourceManifest:Array.isArray(row.source_manifest)?row.source_manifest:[],purpose:row.purpose||'',recipient:row.recipient||'',periodStart:row.period_start,periodEnd:row.period_end,version:row.version||1,finalizedAt:row.finalized_at,storagePath:row.storage_path,originalFilename:row.original_filename,mimeType:row.mime_type,sizeBytes:row.size_bytes,createdAt:row.created_at,updatedAt:row.updated_at};}
export async function listClientDocuments(clientId){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('documents').select(DOCUMENT_FIELDS).eq('client_id',clientId).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(presentClientDocument);}
export async function getClientDocument({clientId,documentId}){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('documents').select(DOCUMENT_FIELDS).eq('id',documentId).eq('client_id',clientId).single();if(error)throw error;return presentClientDocument(data);}
export async function createClientDocumentDraft({client,title,documentType='clinical_summary',purpose='',recipient='',periodStart=null,periodEnd=null,content={},sourceManifest=[]}){const db=requireSupabase();const user=await requireUser(db);const {data,error}=await db.from('documents').insert({user_id:user.id,client_id:client.id,client_ref:client.id,client_name:client.display_name,title:title.trim(),document_type:documentType,status:'draft',purpose,recipient,period_start:periodStart||null,period_end:periodEnd||null,content,source_manifest:sourceManifest}).select(DOCUMENT_FIELDS).single();if(error)throw error;return presentClientDocument(data);}
export async function saveClientDocumentDraft(document,changes){const client=requireSupabase();await requireUser(client);const payload={title:changes.title?.trim()||document.title,document_type:changes.documentType||document.documentType,purpose:changes.purpose??document.purpose,recipient:changes.recipient??document.recipient,period_start:changes.periodStart??document.periodStart,period_end:changes.periodEnd??document.periodEnd,content:changes.content??document.content,source_manifest:changes.sourceManifest??document.sourceManifest,version:document.version+1,updated_at:new Date().toISOString()};const {data,error}=await client.from('documents').update(payload).eq('id',document.id).eq('client_id',document.clientId).eq('status','draft').eq('version',document.version).select(DOCUMENT_FIELDS).maybeSingle();if(error)throw error;if(!data){const conflict=new Error('This document changed in another tab. Reopen it before saving again.');conflict.code='DOCUMENT_CONFLICT';throw conflict;}return presentClientDocument(data);}
export async function listDocumentSourceSessions(clientId){const client=requireSupabase();await requireUser(client);const {data,error}=await client.from('sessions').select('id,client_id,occurred_at,status,notes,notes_status,version,completed_at').eq('client_id',clientId).eq('status','completed').order('occurred_at',{ascending:false});if(error)throw error;return(data||[]).map(row=>({id:row.id,occurredAt:row.occurred_at,notes:row.notes||'',notesStatus:row.notes_status,version:row.version,completedAt:row.completed_at}));}

function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function printableHtml(document,client){const body=escapeHtml(document.content?.body||'').replace(/\n/g,'<br>');const meta=[document.recipient&&`Recipient: ${escapeHtml(document.recipient)}`,document.purpose&&`Purpose: ${escapeHtml(document.purpose)}`,document.periodStart&&`Period: ${escapeHtml(document.periodStart)}${document.periodEnd?` – ${escapeHtml(document.periodEnd)}`:''}`].filter(Boolean).map(item=>`<p>${item}</p>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(document.title)}</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#17202a;line-height:1.5;font-size:11pt}h1{font-size:20pt;margin:0 0 4mm}.client{font-size:12pt;font-weight:600;margin-bottom:5mm}.meta{color:#4b5563;font-size:9.5pt;border-bottom:1px solid #d1d5db;padding-bottom:4mm;margin-bottom:6mm}.body{white-space:normal}.footer{margin-top:10mm;padding-top:4mm;border-top:1px solid #d1d5db;color:#6b7280;font-size:8.5pt}</style></head><body><h1>${escapeHtml(document.title)}</h1><div class="client">${escapeHtml(client?.display_name||document.clientName||'')}</div><div class="meta">${meta}</div><div class="body">${body}</div><div class="footer">Prepared in Helio · ${new Date().toLocaleDateString('en-GB')}</div></body></html>`;}
export function openDocumentPrintView(document,client){const win=window.open('','_blank','noopener,noreferrer');if(!win)throw new Error('Allow pop-ups to preview or print this document');win.document.open();win.document.write(printableHtml(document,client));win.document.close();win.focus();setTimeout(()=>win.print(),150);}
export async function finaliseClientDocument(document,client){if(!document?.id||document.status==='completed')throw new Error('Only draft documents can be finalised');const html=printableHtml(document,client);const frame=documentWindow(html);try{const blob=await printFrameToPdf(frame);const headers=await authHeaders();const response=await fetch(`/api/documents?finalize=${encodeURIComponent(document.id)}&expectedVersion=${encodeURIComponent(document.version)}`,{method:'POST',headers:{...headers,'Content-Type':'application/pdf'},body:blob});if(!response.ok)return apiError(response,'Could not finalise this document');const payload=await response.json();return presentClientDocument(payload.document);}finally{frame.remove();}}
function documentWindow(html){const frame=window.document.createElement('iframe');frame.setAttribute('aria-hidden','true');frame.style.position='fixed';frame.style.width='1px';frame.style.height='1px';frame.style.opacity='0';frame.style.pointerEvents='none';window.document.body.appendChild(frame);frame.contentDocument.open();frame.contentDocument.write(html);frame.contentDocument.close();return frame;}
async function printFrameToPdf(){throw new Error('Automatic PDF generation is not available in this browser build yet. Use Print / Save as PDF, then upload the final PDF.');}
export async function downloadClientDocument(document){if(!document?.storagePath)throw new Error('This document has not been finalised yet');const headers=await authHeaders();const response=await fetch(`/api/documents?download=${encodeURIComponent(document.id)}`,{headers});if(!response.ok)return apiError(response,'Could not download this document');const payload=await response.json();window.open(payload.url,'_blank','noopener,noreferrer');}
