import { supabase } from './supabase.js';
import { downloadClientDocument, finaliseClientDocument } from './clientDocuments.js';
const FIELDS='id,user_id,scope,client_id,client_ref,client_name,title,document_type,report_date,status,content,source_manifest,purpose,recipient,period_start,period_end,version,finalized_at,storage_path,original_filename,mime_type,size_bytes,created_at,updated_at';
function db(){if(!supabase)throw new Error('Supabase is not configured');return supabase;}
async function user(client){const {data,error}=await client.auth.getUser();if(error)throw error;if(!data?.user)throw new Error('Please sign in again');return data.user;}
async function authHeaders(){const client=db();const {data,error}=await client.auth.getSession();if(error)throw error;const token=data?.session?.access_token;if(!token)throw new Error('Please sign in again');return {Authorization:`Bearer ${token}`};}
async function apiError(response,fallback){let message=fallback;try{const payload=await response.json();message=payload?.error?.message||payload?.error||message;}catch{}throw new Error(message);}
export function presentDocument(row){return row?{id:row.id,scope:row.scope||'client',clientId:row.client_id,clientName:row.client_name,title:row.title,documentType:row.document_type,status:row.status,content:row.content||{},purpose:row.purpose||'',recipient:row.recipient||'',version:row.version||1,finalizedAt:row.finalized_at,storagePath:row.storage_path,originalFilename:row.original_filename,mimeType:row.mime_type,sizeBytes:row.size_bytes,updatedAt:row.updated_at,createdAt:row.created_at}:null;}
export async function listDocuments({scope=null}={}){const client=db();await user(client);let query=client.from('documents').select(FIELDS).order('updated_at',{ascending:false});if(scope)query=query.eq('scope',scope);const {data,error}=await query;if(error)throw error;return(data||[]).map(presentDocument);}
export async function createUnscopedDocumentDraft({scope,title,documentType='other',purpose='',recipient='',content={body:''}}){if(!['practice','prospect'].includes(scope))throw new Error('A non-client document must be practice or prospect scoped');const client=db();const owner=await user(client);const {data,error}=await client.from('documents').insert({user_id:owner.id,scope,client_id:null,client_ref:null,client_name:null,title:title.trim(),document_type:documentType,status:'draft',purpose,recipient,content,source_manifest:[]}).select(FIELDS).single();if(error)throw error;return presentDocument(data);}
export async function saveDocumentDraft(document,changes){const client=db();await user(client);const payload={title:changes.title?.trim()||document.title,document_type:changes.documentType||document.documentType,purpose:changes.purpose??document.purpose,recipient:changes.recipient??document.recipient,content:changes.content??document.content,version:document.version+1,updated_at:new Date().toISOString()};const {data,error}=await client.from('documents').update(payload).eq('id',document.id).eq('status','draft').eq('version',document.version).select(FIELDS).maybeSingle();if(error)throw error;if(!data){const conflict=new Error('This document changed in another tab. Reopen it before saving again.');conflict.code='DOCUMENT_CONFLICT';throw conflict;}return presentDocument(data);}
export async function uploadPracticeDocument(file){if(!file)throw new Error('Choose a document to upload');const allowed=new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);if(!allowed.has(file.type))throw new Error('Upload a PDF or Word document');if(file.size>10*1024*1024)throw new Error('File must be 10 MB or smaller');const title=file.name.replace(/\.[^.]+$/,'').trim()||'Uploaded document';const params=new URLSearchParams({scope:'practice',title,documentType:'other'});const headers=await authHeaders();headers['Content-Type']=file.type;headers['X-File-Name']=encodeURIComponent(file.name);const response=await fetch(`/api/documents?${params.toString()}`,{method:'POST',headers,body:file});if(!response.ok)return apiError(response,'Could not upload this practice document');const payload=await response.json();return presentDocument(payload.document);}
export const finaliseDocument=finaliseClientDocument;
export const downloadDocument=downloadClientDocument;
