export const DOCUMENT_TEMPLATES = [
  { id:'agreement', label:'Therapy agreement', scope:'practice', eyebrow:'THERAPY AGREEMENT', title:'Therapy Agreement', purpose:'Working agreement', intro:'This agreement sets out the practical and professional basis for our work together.', sections:[['Our work together','Use this section to describe the therapeutic approach, boundaries and what the client can expect.'],['Appointments and cancellations','Set out appointment length, cancellation notice and any relevant fees.'],['Confidentiality','Explain confidentiality and the circumstances in which information may need to be shared.'],['Contact between sessions','Explain how and when the practice can be contacted between appointments.']] },
  { id:'consent_form', label:'Consent form', scope:'practice', eyebrow:'CONSENT', title:'Consent to Therapy', purpose:'Informed consent', intro:'Please read this document carefully. It records the information needed to make an informed decision about therapy.', sections:[['About therapy','Describe the nature and purpose of the service.'],['Confidentiality and records','Explain how information and records are handled.'],['Consent','Record the points the client is being asked to understand and agree to.']] },
  { id:'information_sheet', label:'Information sheet', scope:'practice', eyebrow:'CLIENT INFORMATION', title:'Information for Clients', purpose:'Client information', intro:'Practical information about the service and what to expect.', sections:[['About the service','Introduce the practice and therapeutic service.'],['Appointments','Add practical appointment information.'],['Getting in touch','Add appropriate contact information and response expectations.']] },
  { id:'marketing_letter', label:'Welcome letter', scope:'prospect', eyebrow:'INTRODUCTION', title:'Welcome', purpose:'Initial enquiry communication', intro:'Thank you for getting in touch. This document introduces the service and explains the next steps.', sections:[['How I can help','Describe the service in clear, accessible language.'],['What happens next','Explain consultation, availability or booking steps.']] },
  { id:'other', label:'Blank professional document', scope:'practice', eyebrow:'DOCUMENT', title:'Untitled Document', purpose:'', intro:'', sections:[['','']] }
]
export function getDocumentTemplate(id){return DOCUMENT_TEMPLATES.find(template=>template.id===id)||DOCUMENT_TEMPLATES[DOCUMENT_TEMPLATES.length-1]}
export function templateBody(template){return [template.intro,...template.sections.flatMap(([heading,body])=>[heading,body])].filter(Boolean).join('\n\n')}
export function bodyBlocks(body=''){return String(body).split(/\n{2,}/).map(value=>value.trim()).filter(Boolean)}
