import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Client Workspace supervision entry reuses private reflection mutation', async () => {
  const header = await readFile(new URL('../src/components/workspace/ClientWorkspaceHeader.vue', import.meta.url), 'utf8')
  const picker = await readFile(new URL('../src/components/workspace/ClientSupervisionPicker.vue', import.meta.url), 'utf8')
  const query = await readFile(new URL('../src/lib/clientSupervision.js', import.meta.url), 'utf8')
  const reflections = await readFile(new URL('../src/lib/reflections.js', import.meta.url), 'utf8')
  assert.match(header, /Add to Supervision/)
  assert.match(header, /openSupervisionPicker/)
  assert.match(header, /getPrivateReflectionsForClient/)
  assert.match(header, /setReflectionSupervisionSelection/)
  assert.match(header, /listSessions/)
  assert.match(header, /included: true/)
  assert.match(header, /Saved to supervision\./)
  assert.match(header, /role="status"/)
  assert.match(header, /aria-live="polite"/)
  assert.match(header, /View Supervision Workspace/)
  assert.match(header, /\/supervision\/workspace/)
  assert.match(query, /export async function getPrivateReflectionsForClient/)
  assert.match(query, /\.eq\('user_id', user\.id\)/)
  assert.match(query, /\.eq\('client_id', clientId\)/)
  assert.match(query, /included_in_supervision/)
  assert.match(reflections, /export async function setReflectionSupervisionSelection/)
  assert.match(picker, /type="checkbox"/)
  assert.match(picker, /Already in pack/)
  assert.match(picker, /Client identifiers are not shown/)
  assert.doesNotMatch(picker, /client_id/)
  assert.doesNotMatch(picker, /session_ref\s*\}\}/)
})

test('Supervision report supports direct PDF download without changing stored reflections', async () => {
  const preview = await readFile(new URL('../src/components/professional-development/SupervisionReportPreview.vue', import.meta.url), 'utf8')
  const workspace = await readFile(new URL('../src/views/supervision/SupervisionWorkspace.vue', import.meta.url), 'utf8')
  assert.match(preview, /Download PDF/)
  assert.match(preview, /download-pdf/)
  assert.match(preview, /data-testid="download-supervision-pdf"/)
  assert.match(workspace, /@download-pdf="downloadPdf"/)
  assert.match(workspace, /application\/pdf/)
  assert.match(workspace, /supervision-report-/)
  assert.match(workspace, /URL\.createObjectURL/)
  assert.match(workspace, /clientAliases/)
  assert.match(workspace, /includeClientReferences/)
})

test('Supervision global content options control preview and exported report content', async () => {
  const preview = await readFile(new URL('../src/components/professional-development/SupervisionReportPreview.vue', import.meta.url), 'utf8')
  const workspace = await readFile(new URL('../src/views/supervision/SupervisionWorkspace.vue', import.meta.url), 'utf8')

  assert.match(preview, /options\.includeDates && itemOptions\(reflection\)\.includeDate/)
  assert.match(preview, /options\.includeThemes && itemOptions\(reflection\)\.includeTheme/)
  assert.match(preview, /options\.includeText && itemOptions\(reflection\)\.includeText/)
  assert.match(workspace, /exportOptions\.value\.includeDates && opts\.includeDate/)
  assert.match(workspace, /exportOptions\.value\.includeThemes && opts\.includeTheme/)
  assert.match(workspace, /exportOptions\.value\.includeText && opts\.includeText/)
})
