import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildClinicalIntelligenceEvidenceMap, renderClientSessionSummary, selectClinicalIntelligenceSources, validateClientSessionSummaryResponse } from '../api/_lib/ai-client-session-summary.js';
import { CLINICAL_INTELLIGENCE_CASES, CLINICAL_INTELLIGENCE_EVALUATION_RUBRIC } from './fixtures/clinical-intelligence-evaluation.js';
import { scoreClinicalIntelligenceOutput, compareClinicalIntelligenceOutputs } from './support/clinical-intelligence-evaluator.js';
const read = path => readFile(new URL(path, import.meta.url), 'utf8');

test('client session summary reuses Client Documents without importing raw internal clinical material', async () => { const workspace=await read('../src/views/ClientWorkspace.vue');const panel=await read('../src/components/workspace/ClientDocumentsPanel.vue');const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');const pdf=await read('../api/_lib/documentPdf.js');assert.match(panel,/Create session summary/i);assert.match(panel,/@click="\$emit\('create','session_summary'\)"/);assert.match(workspace,/@create="newDocument"/);assert.match(workspace,/:initial-document-type="newDocumentType"/);assert.match(composer,/session_summary/);assert.match(composer,/internal clinical notes are not included automatically/i);assert.match(composer,/v-if="!isSessionSummary"[^>]*>Add from clinical notes/);assert.match(composer,/Finalise PDF/);assert.match(pdf,/SESSION SUMMARY/);assert.doesNotMatch(pdf,/session_summary.*Confidential clinical document/); });
test('Helios Clinical Intelligence offers only General, Gentle CBT, and Integrative lenses', async()=>{const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');assert.match(composer,/General/);assert.match(composer,/Gentle CBT/);assert.match(composer,/Integrative/);assert.doesNotMatch(composer,/>EMDR/);});
test('client summary generation uses up to three reviewed Session Captures and accepted Care context',async()=>{const endpoint=await read('../api/ai/client-session-summary.js');assert.match(endpoint,/session_capture_drafts/);assert.match(endpoint,/eq\('status', 'reviewed'\)/);assert.match(endpoint,/selectClinicalIntelligenceSources\(captures\|\|\[\],\{anchorSessionId,limit:captureLimit\}\)/);assert.match(endpoint,/client_care_items/);assert.match(endpoint,/eq\('status', 'current'\)/);assert.match(endpoint,/eq\('client_id', clientId\)/);assert.match(endpoint,/eq\('user_id', user\.id\)/);});
test('Clinical Intelligence uses a stronger feature-specific model default without changing other AI defaults',async()=>{const execution=await read('../api/_lib/ai-execution.js');assert.match(execution,/CLIENT_SESSION_SUMMARY_MODEL\s*=\s*'gpt-5\.6-terra'/);assert.match(execution,/CLIENT_SESSION_SUMMARY.*OPENAI_CLIENT_SUMMARY_MODEL.*CLIENT_SESSION_SUMMARY_MODEL/s);assert.match(execution,/DEFAULT_TEXT_MODEL\s*=\s*'gpt-4o-mini'/);});
test('Clinical Intelligence prompt separates recurrence from causality and protects client-facing boundaries',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');assert.match(prompt,/recurrence is not causality/i);assert.match(prompt,/do not infer diagnoses/i);assert.match(prompt,/risk|safeguarding/i);assert.match(prompt,/directly reported/i);assert.match(prompt,/recurring/i);assert.match(prompt,/possible connection/i);assert.match(prompt,/absence.*improvement/i);});
test('Clinical Intelligence builds a source-aware evidence map before client prose',()=>{const map=buildClinicalIntelligenceEvidenceMap({captures:[{sessionId:'s3',occurredAt:'2026-08-30',content:{summary:'Work criticism led to worry and repeated checking.'}},{sessionId:'s2',occurredAt:'2026-08-23',content:{summary:'After uncertain feedback, client worried and checked messages repeatedly.'}},{sessionId:'s1',occurredAt:'2026-08-16',content:{summary:'Client felt calmer after asking a colleague for perspective.'}}],careItems:[{kind:'current_focus',body:'Self-criticism around uncertainty at work.'}],therapistGuidance:'Notice the exception when another perspective helped.'});assert.equal(map.reviewedSessions.length,3);assert.equal(map.reviewedSessions[0].position,'current');assert.equal(map.reviewedSessions[1].position,'previous_1');assert.equal(map.currentAcceptedCareContext[0].sourceType,'accepted_care');assert.equal(map.therapistAuthoredContext.sourceType,'therapist_guidance');assert.match(map.therapistAuthoredContext.content,/exception/i);assert.deepEqual(map.comparisonTasks,['recurrence','change','stability','exceptions','resources','unfinished_threads','possible_connections']);});
test('Clinical Intelligence quality contract requires staged comparison and evidence thresholds',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');assert.match(prompt,/evidence map/i);assert.match(prompt,/two or more reviewed sessions/i);assert.match(prompt,/current observation/i);assert.match(prompt,/change|stability/i);assert.match(prompt,/exception/i);assert.match(prompt,/unfinished thread/i);assert.match(prompt,/source type/i);assert.match(prompt,/draft the client-facing sections only after/i);});
test('Clinical Intelligence prompt gives each client-facing section a distinct job',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');assert.match(prompt,/opening.*current session|current session.*opening/is);assert.match(prompt,/whatWeWorkedOn.*therapist action|therapist action.*whatWeWorkedOn/is);assert.match(prompt,/patternsOverTime.*two or more reviewed sessions|two or more reviewed sessions.*patternsOverTime/is);assert.match(prompt,/changesAndExceptions.*change.*exception|exception.*changesAndExceptions/is);assert.match(prompt,/strengthsAndResources.*resource|resource.*strengthsAndResources/is);assert.match(prompt,/betweenSession.*agreed|agreed.*betweenSession/is);assert.match(prompt,/closing.*carry forward|carry forward.*closing/is);assert.match(prompt,/do not repeat the same point across sections/i);assert.match(prompt,/avoid generic encouragement|generic therapeutic language/i);});
test('Clinical Intelligence evaluation benchmark covers core therapist quality dimensions',()=>{assert.ok(CLINICAL_INTELLIGENCE_CASES.length>=3);assert.deepEqual(CLINICAL_INTELLIGENCE_EVALUATION_RUBRIC,['factual_grounding','longitudinal_usefulness','specificity','client_readability','exceptions_and_resources','actionable_continuity','provenance_safety','unsupported_inference','repetition']);assert.ok(CLINICAL_INTELLIGENCE_CASES.some(item=>item.lens==='gentle_cbt'&&item.captures.length===3));assert.ok(CLINICAL_INTELLIGENCE_CASES.some(item=>item.lens==='integrative'&&item.captures.length===3));assert.ok(CLINICAL_INTELLIGENCE_CASES.some(item=>item.lens==='general'&&item.captures.length===1));for(const item of CLINICAL_INTELLIGENCE_CASES){assert.ok(item.expectedSignals);assert.ok(Array.isArray(item.expectedSignals.avoid));}});
test('evaluation scorer rewards grounded longitudinal output and penalises unsupported claims',()=>{const fixture=CLINICAL_INTELLIGENCE_CASES.find(item=>item.id==='gentle-cbt-work-uncertainty');const grounded='Across recent sessions, uncertainty or ambiguous feedback has repeatedly been followed by a self-critical interpretation and repeated checking. Talking with a trusted colleague offered another perspective and interrupted that sequence. A useful next step is to notice the urge earlier and try one clarifying question.';const unsafe=`${grounded} This proves a diagnosis and causes the problem.`;const good=scoreClinicalIntelligenceOutput(fixture,grounded);const bad=scoreClinicalIntelligenceOutput(fixture,unsafe);assert.ok(good.percentage>=70);assert.equal(good.scores.unsupported_inference,5);assert.equal(bad.scores.unsupported_inference,0);const ranked=compareClinicalIntelligenceOutputs(fixture,{unsafe,grounded});assert.equal(ranked[0].name,'grounded');});
test('single-session evaluation penalises invented longitudinal claims',()=>{const fixture=CLINICAL_INTELLIGENCE_CASES.find(item=>item.id==='general-sparse-evidence');const current='This session focused on presentation anxiety and poor sleep before the presentation. You identified one practical preparation step and we will review how the presentation went.';const invented='Across recent sessions this has become a recurring pattern of presentation anxiety and poor sleep.';assert.ok(scoreClinicalIntelligenceOutput(fixture,current).scores.longitudinal_usefulness>scoreClinicalIntelligenceOutput(fixture,invented).scores.longitudinal_usefulness);});
test('Gentle CBT longitudinal synthesis includes supported sequence mapping without forcing CBT onto other lenses',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');assert.match(prompt,/antecedent|situation or trigger/i);assert.match(prompt,/thoughts.*emotions.*body/i);assert.match(prompt,/behaviour|behavior/i);assert.match(prompt,/consequence/i);assert.match(prompt,/interruptions|exceptions/i);assert.match(prompt,/short-term|short term/i);assert.match(prompt,/longer-term|longer term/i);assert.match(prompt,/Integrative/);assert.match(prompt,/General/);});
test('therapist-authored additions are passed separately and never presented as client statements',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');const endpoint=await read('../api/ai/client-session-summary.js');const service=await read('../src/lib/clientDocuments.js');const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');assert.match(prompt,/therapist-authored/i);assert.match(prompt,/not.*client (said|statement)|not.*client statement/i);assert.match(prompt,/therapistGuidance/);assert.match(endpoint,/therapistGuidance/);assert.match(service,/therapistGuidance/);assert.match(composer,/Therapist additions|Guidance for Helios/i);});
test('AI returns structured clinical intelligence and Helios renders the client document deterministically',async()=>{const prompt=await read('../api/_lib/ai-client-session-summary.js');const endpoint=await read('../api/ai/client-session-summary.js');for(const field of ['opening','whatWeWorkedOn','patternsOverTime','changesAndExceptions','strengthsAndResources','perspectiveReflection','betweenSession','closing'])assert.match(prompt,new RegExp(field));assert.match(prompt,/renderClientSessionSummary/);assert.match(endpoint,/renderClientSessionSummary/);assert.match(endpoint,/sections/);const rendered=renderClientSessionSummary({opening:'Work has felt more uncertain this week.',whatWeWorkedOn:'We explored what happens after critical feedback.',patternsOverTime:'Across recent sessions, uncertainty has repeatedly been followed by worry and checking.',changesAndExceptions:'Asking for another perspective interrupted the checking on one occasion.',strengthsAndResources:'You noticed the pattern sooner and reached out for support.',perspectiveReflection:'The checking may settle uncertainty briefly while also keeping attention on the threat.',betweenSession:'Notice what happens before the urge to re-check and what helps you respond differently.',closing:'We will carry this thread into the next session.'},'gentle_cbt');assert.match(rendered,/Patterns across our recent work/);assert.match(rendered,/interrupted the checking/);assert.match(rendered,/gentle CBT perspective/i);});
test('composer generates an editable draft and keeps therapist finalisation explicit',async()=>{const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');const service=await read('../src/lib/clientDocuments.js');assert.match(composer,/Generate client summary/i);assert.match(composer,/Last 3 reviewed sessions/i);assert.match(composer,/This session only/i);assert.match(composer,/generateClientSessionSummary/);assert.match(service,/\/api\/ai\/client-session-summary/);assert.match(composer,/Finalise PDF/);});
test('manual Clinical Intelligence benchmark uses only synthetic fixtures and never persists AI usage',async()=>{const packageJson=JSON.parse(await read('../package.json'));const runner=await read('../scripts/evaluate-clinical-intelligence.mjs');assert.equal(packageJson.scripts['evaluate:clinical-intelligence'],'node scripts/evaluate-clinical-intelligence.mjs');assert.match(runner,/CLINICAL_INTELLIGENCE_CASES/);assert.match(runner,/clientSessionSummarySystemPrompt/);assert.match(runner,/buildClientSessionSummaryInput/);assert.match(runner,/validateClientSessionSummaryResponse/);assert.match(runner,/renderClientSessionSummary/);assert.match(runner,/CLIENT_SESSION_SUMMARY_PROMPT_VERSION/);assert.match(runner,/scoreClinicalIntelligenceOutput/);assert.match(runner,/OPENAI_API_KEY/);assert.match(runner,/response_format:\s*\{\s*type:\s*['"]json_object['"]/s);assert.match(runner,/temperature:\s*0\.2/);assert.match(runner,/max_tokens:\s*2600/);assert.match(runner,/--show-output/);assert.doesNotMatch(runner,/runTextAI|getSupabaseClient|supabase/i);assert.doesNotMatch(runner,/Promise\.all/);});

test('source selection follows clinical chronology and never reaches beyond the anchor session',()=>{
  const captures=[
    {id:'draft-old-reviewed-late',session_id:'s1',reviewed_at:'2026-09-01',sessions:{occurred_at:'2026-08-01'}},
    {id:'draft-current',session_id:'s3',reviewed_at:'2026-08-30',sessions:{occurred_at:'2026-08-30'}},
    {id:'draft-middle',session_id:'s2',reviewed_at:'2026-08-20',sessions:{occurred_at:'2026-08-20'}},
    {id:'draft-future',session_id:'s4',reviewed_at:'2026-08-31',sessions:{occurred_at:'2026-08-31'}}
  ];
  assert.deepEqual(selectClinicalIntelligenceSources(captures,{anchorSessionId:'s3',limit:3}).map(item=>item.session_id),['s3','s2','s1']);
});

test('evidence map excludes private or safety-sensitive Care kinds before model input',()=>{
  const map=buildClinicalIntelligenceEvidenceMap({careItems:[
    {id:'c1',kind:'current_focus',status:'current',body:'Work uncertainty.'},
    {id:'c2',kind:'risk',status:'current',body:'Must not reach the model.'},
    {id:'c3',kind:'supervision',status:'current',body:'Private therapist reflection.'},
    {id:'c4',kind:'current_focus',status:'draft',body:'Not accepted.'}
  ]});
  assert.deepEqual(map.currentAcceptedCareContext.map(item=>item.id),['care:c1']);
  assert.doesNotMatch(JSON.stringify(map),/Must not reach|Private therapist reflection|Not accepted/);
});

test('structured response requires every material claim to cite a valid source',()=>{
  const valid=validateClientSessionSummaryResponse({
    sections:{opening:'Work uncertainty was central this week.',whatWeWorkedOn:'',patternsOverTime:'',changesAndExceptions:'',strengthsAndResources:'',perspectiveReflection:'',betweenSession:'',closing:''},
    claims:[{section:'opening',text:'Work uncertainty was central this week.',sourceIds:['session:s3'],evidenceStrength:'current_observation'}]
  },new Set(['session:s3']));
  assert.equal(valid.claims[0].sourceIds[0],'session:s3');
  assert.equal(validateClientSessionSummaryResponse({...valid,claims:[{...valid.claims[0],sourceIds:['session:unknown']}]},new Set(['session:s3'])),null);
  assert.equal(validateClientSessionSummaryResponse({...valid,claims:[{...valid.claims[0],text:'A claim absent from the rendered section.'}]},new Set(['session:s3'])),null);
});

test('composer preserves generated provenance and offers restoration before replacing edited text',async()=>{
  const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');
  assert.match(composer,/Evidence used/);
  assert.match(composer,/Restore previous version/);
  assert.match(composer,/replace your edited draft/i);
  assert.match(composer,/sourceManifest/);
});

test('therapist can inspect and choose the clinical anchor before generation',async()=>{
  const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');
  const service=await read('../src/lib/clientDocuments.js');
  const endpoint=await read('../api/ai/client-session-summary.js');
  assert.match(composer,/Summary anchored to/);
  assert.match(composer,/anchorSessionId/);
  assert.match(composer,/Evidence window/);
  assert.match(service,/listClientSummaryEvidence/);
  assert.match(endpoint,/preview/);
});
