import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');

test('client document schema is additive, client-scoped and draft-capable',async()=>{const migration=await read('../supabase/migrations/20260809154138_harden_client_documents.sql');assert.match(migration,/add column if not exists client_id uuid references public\.clients\(id\)/);assert.match(migration,/content jsonb/);assert.match(migration,/source_manifest jsonb/);assert.match(migration,/version integer/);assert.match(migration,/alter column storage_path drop not null/);assert.match(migration,/documents_user_client_created_idx/);assert.match(migration,/c\.user_id = auth\.uid\(\)/);});

test('document service only offers completed clinical sessions as sources',async()=>{const service=await read('../src/lib/clientDocuments.js');assert.match(service,/from\('sessions'\)/);assert.match(service,/\.eq\('client_id',\s*clientId\)/);assert.match(service,/\.eq\('status',\s*'completed'\)/);assert.match(service,/notes,notes_status,version/);assert.doesNotMatch(service,/private_reflections/);assert.doesNotMatch(service,/included_in_supervision/);assert.match(service,/DOCUMENT_CONFLICT/);assert.match(service,/\.eq\('version',\s*document\.version\)/);});

test('Client Workspace owns the professional clinical composer and exposes safe document actions',async()=>{const header=await read('../src/components/workspace/ClientWorkspaceHeader.vue');const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');const panel=await read('../src/components/workspace/ClientDocumentsPanel.vue');const workspace=await read('../src/views/ClientWorkspace.vue');assert.match(header,/data-testid="create-client-document"/);assert.doesNotMatch(header,/ClientDocumentComposer/);assert.match(header,/create-document/);assert.match(workspace,/@create-document="newDocument"/);assert.match(workspace,/ClientDocumentComposer/);assert.match(composer,/data-testid="client-document-composer"/);assert.match(composer,/Completed clinical session notes only/);assert.match(composer,/Private reflections and supervision material are excluded/);assert.match(composer,/data-testid="clinical-document-canvas"/);assert.match(composer,/Document details/);assert.match(composer,/Add from clinical notes/);assert.doesNotMatch(composer,/Preview PDF/);assert.match(composer,/Save Draft/);assert.match(composer,/Finalise PDF/);assert.match(composer,/finaliseClientDocument/);assert.match(composer,/Unsaved changes/);assert.match(composer,/PDF finalised and saved/);assert.match(composer,/Download PDF/);assert.match(composer,/View Client Documents/);assert.match(panel,/data-testid="client-documents-panel"/);assert.match(panel,/Continue editing/);assert.match(workspace,/activeTab === 'Documents'/);assert.match(workspace,/listClientDocuments/);assert.match(workspace,/downloadClientDocument/);});

test('clinical source selector stays compact and prevents duplicate note insertion',async()=>{const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');assert.match(composer,/data-testid="clinical-source-panel"/);assert.match(composer,/overflow-y-auto/);assert.match(composer,/Search session notes/);assert.match(composer,/expandedSourceId/);assert.match(composer,/selectedSourceIds\.length/);assert.match(composer,/Add \$\{addableSelectedSources\.length\} selected note/);assert.match(composer,/addedSourceIds/);assert.match(composer,/addableSelectedSources/);assert.match(composer,/hasMoreSources/);assert.match(composer,/loadMoreSources/);assert.doesNotMatch(composer,/line-clamp-4/);});

test('clinical finalisation uses therapist-authenticated PDF generation and private download',async()=>{const api=await read('../api/documents.js');const renderer=await read('../api/_lib/documentPdf.js');const service=await read('../src/lib/clientDocuments.js');const composer=await read('../src/components/workspace/ClientDocumentComposer.vue');assert.match(api,/getSupabaseUserClient/);assert.match(api,/buildDocumentPdf/);assert.match(api,/req\.query\.finalize/);assert.doesNotMatch(api,/req\.query\.preview/);assert.match(api,/eq\('user_id',user\.id\)/);assert.match(api,/expectedVersion/);assert.match(api,/status:'completed'/);assert.match(api,/contentType:'application\/pdf'/);assert.match(api,/createSignedUrl/);assert.match(renderer,/PDFDocument/);assert.match(renderer,/@fontsource\/noto-sans/);assert.match(renderer,/registerFont\('NotoSans'/);assert.match(renderer,/registerFont\('NotoSansBold'/);assert.match(renderer,/bufferPages:true/);assert.match(renderer,/bufferedPageRange/);assert.match(renderer,/switchToPage/);assert.match(renderer,/Confidential clinical document/);assert.doesNotMatch(renderer,/pageAdded/);assert.doesNotMatch(renderer,/replace\(\/\[\^\\x20-\\x7E/);assert.doesNotMatch(service,/\/api\/documents\?preview=/);assert.match(service,/\/api\/documents\?finalize=/);assert.match(service,/\/api\/documents\?download=/);assert.doesNotMatch(service,/window\.open/);assert.match(composer,/data-testid="clinical-document-canvas"/);assert.doesNotMatch(composer,/iframe/);});
