import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Growth & Learning View logic and wording', async () => {
  const growthContent = await readFile(new URL('../src/views/supervision/SupervisionGrowth.vue', import.meta.url), 'utf8')
  assert.match(growthContent, /What is your reflective practice showing you about the therapist you are becoming\?/)
  assert.match(growthContent, /class="[^"]*font-fraunces italic/)
  assert.match(growthContent, /Appearing more frequently/)
  assert.match(growthContent, /Emerging across recent reflections/)
  assert.match(growthContent, /Themes to keep under consideration/)
  assert.match(growthContent, /supervision session/)
  assert.match(growthContent, /const learningGoals=ref\(\[\]\)/)
  assert.match(growthContent, /function addGoal/)
  assert.match(growthContent, /function removeGoal/)
  assert.match(growthContent, /Learning goals are currently kept only for this visit/)
  assert.match(growthContent, /Add a learning goal for this visit/)
  assert.doesNotMatch(growthContent, /Refining boundary communication in initial consultations/)
  assert.doesNotMatch(growthContent, /Exploring somatic countertransference patterns/)
  assert.match(growthContent, /to="\/supervision\/workspace"/)
  assert.match(growthContent, /Prepare for Supervision/)
  assert.match(growthContent, /Reading/)
  assert.match(growthContent, /Theoretical texts related to your recent themes/)
  assert.match(growthContent, /Peer Discussion/)
  assert.match(growthContent, /Explore these themes in a safe peer group setting/)
  assert.match(growthContent, /const landscapeThemes=computed/)
  assert.match(growthContent, /props\.themes\.filter/)
  assert.match(growthContent, /Continue reflecting to see your clinical strengths emerge here/)
  assert.match(growthContent, /Your recurring themes will appear as you build your practice history/)
})
