import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Overview view requirements', async () => {
  const overview = await readFile(new URL('../src/views/Overview.vue', import.meta.url), 'utf8')

  assert.match(overview, /\{\{ todayLabel \}\}/)
  assert.match(overview, /Good afternoon, Robert/)
  assert.match(overview, /Today’s Schedule/)
  assert.match(overview, /v-for="event in todayEvents"/)
  assert.match(overview, /formatTime\(event.start\)/)
  assert.match(overview, /event.clientName/)
  assert.match(overview, /formatStatus\(event.status\)/)
  assert.match(overview, /Open Client/)
  assert.match(overview, /Start Session/)
  assert.match(overview, /View Calendar →/)

  // Session entry must create/resume a real session before routing.
  assert.match(overview, /createOrResumeSession\(event\.clientId\)/)
  assert.match(overview, /sessionId: session\.id/)
  assert.doesNotMatch(overview, /sessions\/\$\{event\.id\}/)
  assert.match(overview, /startingEventId/)
  assert.match(overview, /Couldn’t open the session workspace\. Please try again\./)

  assert.match(overview, /Continue Working/)
  assert.match(overview, /pendingWork/)
  assert.match(overview, /No pending drafts or reviews./)
  assert.match(overview, /Practice Focus/)
  assert.match(overview, /practiceFocusObservation/)
  assert.match(overview, /Development/)
  assert.match(overview, /Supervision Prep/)
  assert.match(overview, /Go to Supervision →/)
  assert.match(overview, /reflectionsCount/)
  assert.match(overview, /Recent Activity/)
  assert.match(overview, /No recent activity to show./)
  assert.doesNotMatch(overview, /PHQ-9/)
  assert.doesNotMatch(overview, /GAD-7/)
  assert.doesNotMatch(overview, /score/)
})

test('Calendar view requirements', async () => {
  const calendar = await readFile(new URL('../src/views/Calendar.vue', import.meta.url), 'utf8')

  assert.match(calendar, /Agenda Panel/)
  assert.match(calendar, /miniMonthName/)
  assert.match(calendar, /Today/)
  assert.match(calendar, /Upcoming/)
  assert.match(calendar, /Google Calendar/)
  assert.match(calendar, /currentRangeLabel/)
  assert.match(calendar, /move\(-1\)/)
  assert.match(calendar, /move\(1\)/)
  assert.match(calendar, /goToday/)
  assert.match(calendar, /v-for="day in weekDays"/)
  assert.match(calendar, /day.shortName/)
  assert.match(calendar, /day.date.getDate\(\)/)
  assert.match(calendar, /v-for="event in day.events/)
  assert.match(calendar, /event.clientName/)
  assert.match(calendar, /formatTime\(event.start\)/)
  assert.match(calendar, /selectedEventId === event\.id/)
  assert.match(calendar, /selectAppointment\(event, \$event\)/)
  assert.match(calendar, /Open Client/)
  assert.match(calendar, /Start Session/)
  assert.match(calendar, /:to="`\/clients\/\${selectedEvent\.clientId}`"/)
  assert.match(calendar, /window\.addEventListener\('keydown', handleGlobalEsc\)/)
  assert.match(calendar, /@click="selectedEventId = null"/)
  assert.match(calendar, /tabindex/)
  assert.doesNotMatch(calendar, /inspector/)
  assert.doesNotMatch(calendar, /clinical-panel/)
  assert.doesNotMatch(calendar, /preparation-panel/)
  assert.doesNotMatch(calendar, /edit-appointment/)
  assert.doesNotMatch(calendar, /create-appointment/)
  assert.doesNotMatch(calendar, /drag-and-drop/)
})
