import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Overview view requirements', async () => {
  const overview = await readFile(new URL('../src/views/Overview.vue', import.meta.url), 'utf8')
  assert.match(overview, /\{\{ todayLabel \}\}/)
  assert.match(overview, /Good afternoon, Robert/)
  assert.match(overview, /Today’s Schedule/)
  assert.match(overview, /v-for="event in todayEvents"/)
  assert.match(overview, /formatTime\(event.start\)/)
  assert.match(overview, /event.clientName/)
  assert.match(overview, /formatStatus\(event.status\)/)
  assert.match(overview, /Open Client/)
  assert.match(overview, /Start Session/)
  assert.match(overview, /event\.isEligibleForStart && event\.sessionId/)
  assert.match(overview, /sessions\/\$\{event\.sessionId\}/)
  assert.doesNotMatch(overview, /sessions\/\$\{event\.id\}/)
  assert.match(overview, /calendarSourceDisclosure/)
  assert.match(overview, /isGoogleConnected/)
  assert.match(overview, /View Calendar →/)
  assert.match(overview, /Continue Working/)
  assert.match(overview, /pendingWork/)
  assert.match(overview, /No pending drafts or reviews./)
  assert.match(overview, /Practice Focus/)
  assert.match(overview, /practiceFocusObservation/)
  assert.match(overview, /Development/)
  assert.match(overview, /Supervision Prep/)
  assert.match(overview, /Go to Supervision →/)
  assert.match(overview, /reflectionsCount/)
  assert.match(overview, /Recent Activity/)
  assert.match(overview, /No recent activity to show./)
  assert.doesNotMatch(overview, /PHQ-9|GAD-7|score/)
})

test('Calendar view requirements', async () => {
  const calendar = await readFile(new URL('../src/views/Calendar.vue', import.meta.url), 'utf8')
  assert.match(calendar, /Agenda Panel/)
  assert.match(calendar, /miniMonthName/)
  assert.match(calendar, /Today/)
  assert.match(calendar, /Upcoming/)
  assert.match(calendar, /Google Calendar/)
  assert.match(calendar, /currentRangeLabel/)
  assert.match(calendar, /move\(-1\)/)
  assert.match(calendar, /move\(1\)/)
  assert.match(calendar, /goToday/)
  assert.match(calendar, /v-for="day in weekDays"/)
  assert.match(calendar, /day.shortName/)
  assert.match(calendar, /day.date.getDate\(\)/)
  assert.match(calendar, /v-for="event in day.events/)
  assert.match(calendar, /event.clientName/)
  assert.match(calendar, /formatTime\(event.start\)/)
  assert.match(calendar, /selectedEventId === event\.id/)
  assert.match(calendar, /selectAppointment\(event, \$event\)/)
  assert.match(calendar, /Open Client/)
  assert.match(calendar, /Start Session/)
  assert.match(calendar, /:to="`\/clients\/\${selectedEvent\.clientId}`"/)
  assert.match(calendar, /:to="`\/clients\/\${selectedEvent\.clientId}\/sessions\/\${selectedEvent\.originalId}`"/)
  assert.match(calendar, /window\.addEventListener\('keydown', handleGlobalEsc\)/)
  assert.match(calendar, /@click="selectedEventId = null"/)
  assert.match(calendar, /tabindex/)
  assert.doesNotMatch(calendar, /clinical-panel|preparation-panel|edit-appointment|create-appointment|drag-and-drop/)
})
