import test from 'node:test';import assert from 'node:assert/strict';import { readFile } from 'node:fs/promises';import { decodeSessionReflection,encodeSessionReflection } from '../src/lib/reflections.js';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');
test('structured private reflection round-trips all therapist fields',()=>{const input={stoodOut:'A',emotionalResponse:'B',countertransference:'C',uncertainties:'D',supervisionQuestions:'E',nextSession:'F'};assert.deepEqual(decodeSessionReflection(encodeSessionReflection(input)),input);});
test('legacy reflection bodies remain visible rather than discarded',()=>{assert.equal(decodeSessionReflection('Legacy reflection').stoodOut,'Legacy reflection');});
test('Session Workspace passes real client and session ids into private reflection',async()=>{const source=await read('../src/views/SessionWorkspace.vue');assert.match(source,/<ReflectionTab[^>]*:clientId="session\.clientId"[^>]*:sessionId="session\.id"/);assert.match(source,/clinical session record and base notes/);assert.match(source,/source transcript remains therapist-owned and read-only/);});
test('Reflection tab loads and persists through private_reflections helpers',async()=>{const source=await read('../src/components/workspace/ReflectionTab.vue');assert.match(source,/getPrivateReflection/);assert.match(source,/upsertPrivateReflection/);assert.match(source,/decodeSessionReflection/);assert.match(source,/@input="queueSave"/);assert.match(source,/@transcribed="queueSave"/);assert.match(source,/<DictationControl/);assert.match(source,/Could not save your private reflection/);});
test('DictationControl component implements MediaRecorder and transcription pipeline',async()=>{const source=await read('../src/components/workspace/DictationControl.vue');assert.match(source,/new MediaRecorder/);assert.match(source,/getUserMedia/);assert.match(source,/authenticatedFetch\('\/api\/ai\/transcribe'/);assert.match(source,/Recording…/);assert.match(source,/Transcribing…/);assert.match(source,/track\.stop\(\)/);assert.match(source,/audioChunks = \[\]/);});
test('Professional Development renders stored reflection fields and no placeholder summary copy',async()=>{const source=await read('../src/components/workspace/SupervisionSummaryTab.vue');for(const field of ['supervisionQuestions','stoodOut','emotionalResponse','countertransference','uncertainties','nextSession'])assert.match(source,new RegExp(field));assert.doesNotMatch(source,/placeholderSections|will appear here|areas extracted from session content/);assert.match(source,/setReflectionSupervisionSelection/);});
test('transcript API never accepts source transcript text as a therapist PATCH field',async()=>{const source=await read('../api/zoom/transcripts.js');const patchBody=source.match(/if \(req\.method === 'PATCH'\)([\s\S]*?)return res\.status\(405\)/)?.[1]||'';assert.doesNotMatch(patchBody,/req\.body[^\n]*originalTranscript|original_transcript\s*=/);assert.match(source,/\.eq\('therapist_user_id', user\.id\)/);});
