import fs from 'node:fs';
import PDFDocument from 'pdfkit';
const FONT_REGULAR=new URL('../../node_modules/@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff',import.meta.url);
const FONT_BOLD=new URL('../../node_modules/@fontsource/noto-sans/files/noto-sans-latin-700-normal.woff',import.meta.url);
function text(value){return String(value??'').replace(/\r\n?/g,'\n');}
function formatDate(value){if(!value)return'';const date=new Date(`${value}T00:00:00Z`);return Number.isNaN(date.getTime())?text(value):new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(date);}
function metadataLines(draft){const period=draft.period_start?`${formatDate(draft.period_start)}${draft.period_end?` – ${formatDate(draft.period_end)}`:''}`:'';return[[draft.client_name,'Client'],[draft.recipient,'Recipient'],[draft.purpose,'Purpose'],[period,'Period']].filter(([value])=>text(value).trim());}
function isClientDocument(draft){return !draft.scope||draft.scope==='client';}
function addBufferedFooters(pdf,draft){const range=pdf.bufferedPageRange();for(let index=range.start;index<range.start+range.count;index+=1){pdf.switchToPage(index);const originalBottom=pdf.page.margins.bottom;pdf.page.margins.bottom=0;const y=pdf.page.height-38;const footer=isClientDocument(draft)?'Helio Therapist · Confidential clinical document':'Helio Therapist · Document';pdf.save().font('NotoSans').fontSize(8).fillColor('#6b7280').text(footer,pdf.page.margins.left,y,{width:pdf.page.width-pdf.page.margins.left-pdf.page.margins.right,align:'left',lineBreak:false}).restore();pdf.page.margins.bottom=originalBottom;}}
export async function buildDocumentPdf(draft){const chunks=[];const fallback=isClientDocument(draft)?'Client document':'Document';const pdf=new PDFDocument({size:'A4',bufferPages:true,margins:{top:54,bottom:64,left:58,right:58},info:{Title:text(draft.title||fallback),Author:'Helio',Subject:text(draft.purpose||draft.document_type||fallback),Creator:'Helio Therapist'}});pdf.on('data',chunk=>chunks.push(chunk));const done=new Promise((resolve,reject)=>{pdf.on('end',()=>resolve(Buffer.concat(chunks)));pdf.on('error',reject);});pdf.registerFont('NotoSans',fs.readFileSync(FONT_REGULAR));pdf.registerFont('NotoSansBold',fs.readFileSync(FONT_BOLD));const pageWidth=pdf.page.width-pdf.page.margins.left-pdf.page.margins.right;pdf.font('NotoSansBold').fontSize(9).fillColor('#6b7280').text('HELIO THERAPIST',{characterSpacing:1.2});pdf.moveDown(0.8);pdf.font('NotoSansBold').fontSize(22).fillColor('#111827').text(text(draft.title||fallback),{width:pageWidth});pdf.moveDown(0.8);const meta=metadataLines(draft);if(meta.length){for(const [value,label] of meta){pdf.font('NotoSansBold').fontSize(9).fillColor('#4b5563').text(`${label}:`,{continued:true});pdf.font('NotoSans').fillColor('#111827').text(` ${text(value)}`);}pdf.moveDown(0.8);}pdf.moveTo(pdf.x,pdf.y).lineTo(pdf.x+pageWidth,pdf.y).lineWidth(0.7).strokeColor('#d1d5db').stroke();pdf.moveDown(1.1);const body=text(draft.content?.body||'').trim();if(body){for(const paragraph of body.split(/\n{2,}/)){const normalized=paragraph.trim();if(!normalized)continue;const isHeading=normalized.length<=90&&!normalized.includes('\n')&&/^(session\s|summary|background|progress|recommendations?|plan|assessment|clinical|purpose|outcome)/i.test(normalized);pdf.font(isHeading?'NotoSansBold':'NotoSans').fontSize(isHeading?12:10.5).fillColor('#111827').text(normalized,{width:pageWidth,align:'left',lineGap:isHeading?2:3});pdf.moveDown(isHeading?0.55:0.8);}}else pdf.font('NotoSans').fontSize(10.5).fillColor('#6b7280').text('No document body supplied.');addBufferedFooters(pdf,draft);pdf.end();return done;}
