<template>
<section aria-labelledby="care-heading" class="space-y-stack-lg">
  <header class="border-b border-border pb-stack-md"><h2 id="care-heading" class="text-h2 font-semibold text-ink">Care</h2><p class="text-body-sm text-ink-secondary mt-1">Think aloud or type. Helio can offer possibilities; you decide what becomes part of Care.</p><p class="text-caption text-ink-muted mt-stack-sm">CBT-informed direction without pass/fail goals. AI suggestions remain temporary until you review and save them.</p></header>

  <section class="border border-border rounded-panel bg-surface-elevated p-inline-lg py-stack-lg space-y-stack-md" aria-labelledby="care-capture-heading">
    <div><h3 id="care-capture-heading" class="text-h3 font-semibold text-ink">What’s on your mind?</h3><p class="text-body-sm text-ink-muted mt-1">A thought, impression, uncertainty, pattern or possible next step. This draft is not part of the clinical record.</p></div>
    <textarea v-model="capture" rows="5" class="w-full border border-border rounded-control bg-surface px-inline-md py-stack-sm text-body text-ink" placeholder="Type here, or use the microphone to dictate…"></textarea>
    <div class="flex flex-wrap items-center gap-inline-sm">
      <button type="button" :disabled="transcribing" class="px-inline-md py-stack-xs border border-border rounded-control text-body-sm font-medium text-ink" @click="toggleRecording">{{ recording ? '■ Stop recording' : '🎙 Dictate' }}</button>
      <span v-if="recording" class="text-caption text-action-link">Listening… {{ recordingSeconds }}s</span><span v-else-if="transcribing" class="text-caption text-ink-muted">Transcribing securely…</span>
      <select v-model="steering" class="border border-border rounded-control bg-surface px-inline-sm py-stack-xs text-body-sm text-ink-secondary"><option value="">Balanced suggestions</option><option value="stay close to observable evidence">Stay close to evidence</option><option value="offer alternative hypotheses and avoid premature certainty">Alternative hypotheses</option><option value="emphasise gentle behavioural experiments and practical next steps">More behavioural</option><option value="make the language less interpretive and more tentative">Less interpretive</option></select>
      <button type="button" :disabled="generating || !capture.trim()" class="ml-auto px-inline-md py-stack-xs bg-action-link text-on-action rounded-control text-body-sm font-medium disabled:opacity-50" @click="generate">{{ generating ? 'Thinking…' : suggestions.length ? 'Regenerate suggestions' : 'Generate suggestions' }}</button>
    </div>
    <p v-if="captureError" class="text-body-sm text-state-danger">{{ captureError }}</p>
  </section>

  <section v-if="suggestions.length" class="space-y-stack-md" aria-labelledby="suggestions-heading">
    <div class="flex items-end justify-between gap-inline-md"><div><h3 id="suggestions-heading" class="text-h3 font-semibold text-ink">Possibilities to review</h3><p class="text-body-sm text-ink-muted mt-1">Accept useful thoughts, edit them, or decline them. Accepted items are still staged until you save.</p></div><span class="text-caption text-ink-muted">{{ acceptedCount }} accepted</span></div>
    <article v-for="suggestion in suggestions" :key="suggestion.id" class="border rounded-panel p-inline-lg py-stack-md" :class="suggestion.decision === 'accepted' ? 'border-action-link bg-surface-subtle' : 'border-border bg-surface-elevated'">
      <div class="flex flex-wrap gap-inline-sm mb-stack-sm"><span class="text-caption font-medium text-ink-secondary">{{ sectionTitle(suggestion.kind) }}</span><span class="text-caption text-ink-muted">{{ epistemicLabel(suggestion.epistemic) }}</span><span class="text-caption text-ink-muted">{{ basisLabel(suggestion.basis) }}</span></div>
      <textarea v-if="suggestion.decision === 'accepted'" v-model="suggestion.body" rows="3" class="w-full border border-border rounded-control bg-surface px-inline-md py-stack-sm text-body text-ink"></textarea><p v-else class="text-body text-ink leading-relaxed">{{ suggestion.body }}</p>
      <div class="flex gap-inline-sm mt-stack-md"><button type="button" class="px-inline-sm py-stack-xs rounded-control text-body-sm font-medium" :class="suggestion.decision === 'accepted' ? 'bg-action-link text-on-action' : 'border border-border text-ink'" @click="suggestion.decision='accepted'">Accept{{ suggestion.decision === 'accepted' ? 'ed' : '' }}</button><button type="button" class="px-inline-sm py-stack-xs border border-border rounded-control text-body-sm text-ink-secondary" @click="suggestion.decision='declined'">Decline</button></div>
    </article>
    <div v-if="acceptedCount" class="flex flex-col sm:flex-row sm:items-center justify-between gap-stack-sm border-t border-border pt-stack-md"><p class="text-body-sm text-ink-secondary">Review the accepted wording above. Saving makes only those items part of the durable Care record.</p><button type="button" :disabled="saving" class="px-inline-md py-stack-xs bg-action-link text-on-action rounded-control font-medium disabled:opacity-50" @click="saveAccepted">{{ saving ? 'Saving…' : `Save ${acceptedCount} accepted ${acceptedCount === 1 ? 'change' : 'changes'}` }}</button></div>
    <p v-if="saveError" class="text-body-sm" :class="saveErrorKind === 'configuration' ? 'text-ink-secondary' : 'text-state-danger'">{{ saveError }}</p>
  </section>

  <p v-if="loading" class="text-body-sm text-ink-muted py-stack-lg">Loading Care…</p>
  <div v-else class="space-y-stack-xl">
    <section v-for="section in sections" :key="section.kind"><div class="mb-stack-sm"><h3 class="text-h3 font-semibold text-ink">{{ section.title }}</h3><p class="text-body-sm text-ink-muted mt-1">{{ section.description }}</p></div><div v-if="itemsFor(section.kind).length" class="border-y border-border divide-y divide-border"><article v-for="item in itemsFor(section.kind)" :key="item.id" class="py-stack-md flex gap-inline-md justify-between items-start"><div><p class="text-body text-ink leading-relaxed">{{ item.body }}</p><p class="text-caption text-ink-muted mt-stack-xs">{{ formatDate(item.updatedAt) }}<span v-if="item.origin === 'ai_assisted'"> · AI-assisted, clinician accepted</span></p></div><select :value="item.status" class="shrink-0 border border-border rounded-control bg-surface px-inline-sm py-stack-xs text-caption text-ink-secondary" @change="changeStatus(item,$event.target.value)"><option value="current">Current</option><option value="less_relevant">Less relevant</option><option value="paused">Paused</option><option value="historical">Earlier</option></select></article></div><p v-else class="border-y border-border py-stack-md text-body-sm text-ink-muted">{{ section.empty }}</p></section>
  </div>
</section>
</template>
<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { createClientCareItems, generateCareSuggestions, listClientCareItems, transcribeCareAudio, updateClientCareItem } from '../../lib/clientCare.js'
const props=defineProps({clientId:{type:String,required:true}}); const emit=defineEmits(['changed'])
const items=ref([]),loading=ref(true),capture=ref(''),steering=ref(''),suggestions=ref([]),generating=ref(false),saving=ref(false),recording=ref(false),transcribing=ref(false),recordingSeconds=ref(0),captureError=ref(''),saveError=ref(''),saveErrorKind=ref(''); let recorder=null,chunks=[],stream=null,recordingTimer=null
const sections=[{kind:'current_focus',title:'Current focus',description:'What seems important in the work right now.',empty:'No current focus has been recorded yet.'},{kind:'shared_understanding',title:'Shared understanding',description:'Patterns, meanings, responses, strengths and maintaining processes emerging together.',empty:'The shared understanding can emerge gradually.'},{kind:'trying',title:'What we’re trying',description:'Approaches, experiments and practices being explored rather than tasks to pass or fail.',empty:'No approaches or experiments are being tracked yet.'},{kind:'change_noticed',title:'Changes we’re noticing',description:'Differences across sessions, including improvement, difficulty, recurrence or uncertainty.',empty:'No changes have been recorded yet.'},{kind:'learning',title:'What we’re learning',description:'What the work is teaching you and the client, including findings that challenge the current understanding.',empty:'Learning from the work will appear here as it develops.'}]
const acceptedCount=computed(()=>suggestions.value.filter(s=>s.decision==='accepted').length)
function itemsFor(kind){return items.value.filter(i=>i.kind===kind&&i.status!=='historical')} function sectionTitle(kind){return sections.find(s=>s.kind===kind)?.title||'Care'} function epistemicLabel(v){return {observation:'Observation',clinical_inference:'Clinical inference',possible_next_step:'Possible next step'}[v]||'Possibility'} function basisLabel(v){return {therapist_input:'From your note',approved_record:'From approved record',both:'Your note + approved record'}[v]||'From your note'}
async function load(){loading.value=true;saveError.value='';try{items.value=await listClientCareItems(props.clientId)}catch(e){saveErrorKind.value=e.code==='CARE_SCHEMA_UNAVAILABLE'?'configuration':'error';saveError.value=e.code==='CARE_SCHEMA_UNAVAILABLE'?'Care storage is not available in this environment yet. Your typed or dictated draft will remain on screen, but it cannot be committed until storage is configured.':'Care could not be loaded. Please try again.'}finally{loading.value=false}}
async function generate(){generating.value=true;captureError.value='';try{const result=await generateCareSuggestions({clientId:props.clientId,input:capture.value,steering:steering.value});suggestions.value=result.suggestions.map(s=>({...s,decision:'pending'}))}catch(e){captureError.value=e.message||'Suggestions could not be generated.'}finally{generating.value=false}}
async function saveAccepted(){const accepted=suggestions.value.filter(s=>s.decision==='accepted'&&s.body.trim());if(!accepted.length)return;saving.value=true;saveError.value='';try{const saved=await createClientCareItems(props.clientId,accepted.map(s=>({kind:s.kind,body:s.body,origin:'ai_assisted',aiPromptVersion:s.promptVersion})));items.value=[...saved,...items.value];suggestions.value=suggestions.value.filter(s=>s.decision!=='accepted');emit('changed',items.value)}catch(e){saveErrorKind.value=e.code==='CARE_SCHEMA_UNAVAILABLE'?'configuration':'error';saveError.value=e.code==='CARE_SCHEMA_UNAVAILABLE'?'Care storage has not been configured in this environment. Nothing was lost; your accepted suggestions remain staged above.':e.code==='UNAUTHENTICATED'?'Your secure session has expired. Sign in again before saving these Care changes.':'These accepted changes could not be saved. They remain staged above so you can retry.'}finally{saving.value=false}}
async function changeStatus(item,status){try{const updated=await updateClientCareItem(item.id,{status});items.value=items.value.map(i=>i.id===updated.id?updated:i);emit('changed',items.value)}catch(e){saveError.value='That Care item could not be updated. Its previous state has been kept.'}}
async function toggleRecording(){if(recording.value){recorder?.stop();return}captureError.value='';try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=transcribeRecording;recorder.start();recording.value=true;recordingSeconds.value=0;recordingTimer=setInterval(()=>recordingSeconds.value++,1000)}catch(e){captureError.value='Microphone access was not available. You can continue by typing.'}}
async function transcribeRecording(){recording.value=false;clearInterval(recordingTimer);stream?.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:recorder?.mimeType||'audio/webm'});if(!blob.size)return;transcribing.value=true;try{const audio=await blobToDataUrl(blob);const text=await transcribeCareAudio(audio);capture.value=[capture.value.trim(),text.trim()].filter(Boolean).join(capture.value.trim()?'\n':'')}catch(e){captureError.value=e.message||'The recording could not be transcribed. You can continue by typing.'}finally{transcribing.value=false}}
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})} function formatDate(v){return v?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):''}
onMounted(load);onBeforeUnmount(()=>{clearInterval(recordingTimer);stream?.getTracks().forEach(t=>t.stop())})
</script>
