<template>
  <header class="bg-surface border-b border-border-muted px-inline-lg py-stack-md">
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-stack-md">
      <div class="flex items-center gap-inline-md"><div class="h-10 w-10 rounded-pill bg-avatar flex items-center justify-center text-h3 font-semibold text-ink shrink-0">{{ clientInitials }}</div><div class="flex flex-col min-w-0"><div class="flex items-center gap-inline-sm flex-wrap"><h1 class="text-h2 font-semibold text-ink truncate">{{ client.display_name }}</h1><StatusBadge :status="client.archived ? 'archived' : 'active'" /></div><div class="flex flex-wrap items-center gap-x-inline-md gap-y-0 text-caption text-ink-muted"><span>Next: {{ nextAppointmentLabel }}</span><span>Therapist: {{ therapistLabel }}</span><span v-if="client.archived_at">Archived {{ archiveDate }}</span></div></div></div>
      <div class="flex items-center gap-inline-sm flex-wrap"><button @click="openSupervisionPicker" class="px-inline-md py-stack-xs bg-surface-elevated border border-border text-caption font-medium text-ink-secondary rounded-control hover:bg-surface-subtle transition-colors">Add to Supervision</button><button @click="$emit('create-document')" class="px-inline-md py-stack-xs bg-surface-elevated border border-border text-body-sm font-medium text-ink rounded-control hover:bg-surface-subtle transition-colors" data-testid="create-client-document">Create Document</button><button v-if="!client.archived && !activeSession" @click="joinMeeting" :disabled="joiningMeeting || !nextAppointment?.zoom_meeting_id" class="px-inline-md py-stack-xs bg-surface-elevated border border-border text-caption font-medium text-ink-secondary rounded-control hover:bg-surface-subtle transition-colors disabled:opacity-50 disabled:cursor-not-allowed"><span>{{ joiningMeeting ? 'Opening Zoom…' : videoLabel }}</span></button><button v-if="!activeSession" type="button" :disabled="archiveSaving" @click="requestArchiveChange" class="px-inline-md py-stack-xs bg-surface-elevated border border-border text-body-sm font-medium text-ink-secondary rounded-control hover:bg-surface-subtle disabled:opacity-50" data-testid="client-archive-action">{{ archiveSaving ? 'Saving…' : (client.archived ? 'Restore client' : 'Archive client') }}</button></div>
    </div>
    <div v-if="activeSession" class="mt-stack-md flex flex-col sm:flex-row sm:items-center sm:justify-between gap-stack-sm rounded-panel border-2 border-state-selected bg-surface p-inline-lg py-stack-md shadow-sm" data-testid="active-session-timer-panel">
      <div class="flex items-center gap-inline-md">
        <div class="w-12 h-12 rounded-full bg-state-selected/10 flex items-center justify-center shrink-0">
          <span class="w-3 h-3 rounded-full bg-state-selected animate-pulse"></span>
        </div>
        <div>
          <div class="flex items-center gap-inline-sm">
            <span class="text-body font-bold text-ink">Session in progress</span>
            <span class="text-h3 font-mono font-bold text-ink" aria-live="polite">{{ elapsedTime }}</span>
          </div>
          <p class="text-caption text-ink-muted mt-0.5">Started at {{ formatSessionTime(activeSession.startedAt) }} · Timing continues in both workspaces</p>
        </div>
      </div>
      <div class="flex items-center gap-inline-sm">
        <button @click="rejoinSessionVideo" :disabled="joiningMeeting" class="px-inline-md py-stack-sm bg-surface border border-border text-body-sm font-semibold text-ink rounded-control hover:bg-surface-subtle transition-colors disabled:opacity-50 disabled:cursor-not-allowed">{{ joiningMeeting ? 'Opening Zoom…' : 'Return to Video Session' }}</button>
        <button @click="$emit('open-clinical-workspace')" class="px-inline-md py-stack-sm bg-surface border border-border text-body-sm font-semibold text-ink rounded-control hover:bg-surface-subtle transition-colors">Clinical Workspace</button>
        <button @click="$emit('end-session')" :disabled="sessionBusy" class="px-inline-md py-stack-sm bg-state-danger text-body-sm font-semibold text-white rounded-control hover:bg-opacity-90 transition-colors disabled:opacity-60">{{ sessionBusy ? 'Ending…' : 'End Session' }}</button>
      </div>
    </div>
    <div v-else-if="!client.archived" class="mt-stack-md">
      <button @click="$emit('start-session')" :disabled="sessionBusy" class="px-inline-lg py-stack-sm bg-action-link text-body font-semibold text-on-action rounded-control hover:bg-action-link-hover transition-colors shadow-sm disabled:opacity-60" data-testid="start-session">
        {{ sessionBusy ? 'Starting…' : 'Start Session' }}
      </button>
    </div>
    <div v-if="sessionError" role="alert" class="mt-stack-sm rounded-control border border-state-danger/20 bg-state-danger/5 px-inline-md py-stack-xs text-body-sm font-medium text-state-danger">{{ sessionError }}</div>
    <div v-if="meetingError" role="alert" class="mt-stack-sm rounded-control border border-state-danger/20 bg-state-danger/5 px-inline-md py-stack-xs text-body-sm font-medium text-state-danger">{{ meetingError }}</div>
    <div v-if="archiveError" role="alert" class="mt-stack-sm rounded-control border border-state-danger/20 bg-state-danger/5 px-inline-md py-stack-xs text-body-sm text-state-danger">{{ archiveError }}</div>
    <div v-if="supervisionSuccess" role="status" class="mt-stack-sm inline-flex flex-wrap items-center gap-inline-sm rounded-control border border-state-success/20 bg-state-success-surface px-inline-md py-stack-xs text-body-sm font-medium text-state-success"><span>✓</span><span>{{ supervisionSuccess }}</span><button @click="router.push('/supervision/workspace')" class="ml-inline-xs font-semibold underline">View Supervision Workspace</button></div>
    <ClientSupervisionPicker v-if="supervisionPickerOpen" :client-name="client.display_name" :reflections="supervisionReflections" :sessions="supervisionSessions" :loading="supervisionLoading" :saving="supervisionSaving" :error="supervisionError" @close="closeSupervisionPicker" @confirm="addSelectedToSupervision" />
  </header>
</template>
<script setup>
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import StatusBadge from './StatusBadge.vue'; import ClientSupervisionPicker from './ClientSupervisionPicker.vue';
import { listSessions } from '../../lib/sessions.js'; import { setClientArchived } from '../../lib/clients.js'; import { getPrivateReflectionsForClient } from '../../lib/clientSupervision.js'; import { setReflectionSupervisionSelection } from '../../lib/reflections.js'; import { authenticatedFetch } from '../../lib/api.js'; import { videoProviderService } from '../../lib/videoProvider.js';
const props = defineProps({ client:{type:Object,required:true}, nextAppointment:{type:Object,default:null}, therapistLabel:{type:String,default:'Current therapist'}, activeSession:{type:Object,default:null}, elapsedTime:{type:String,default:'00:00:00'}, sessionBusy:{type:Boolean,default:false}, sessionError:{type:String,default:''} });
const emit = defineEmits(['create-document','client-updated','start-session','open-clinical-workspace','end-session']); const router=useRouter();
const supervisionPickerOpen=ref(false), supervisionReflections=ref([]), supervisionSessions=ref([]), supervisionLoading=ref(false), supervisionSaving=ref(false), supervisionError=ref(''), supervisionSuccess=ref(''), archiveSaving=ref(false), archiveError=ref(''), joiningMeeting=ref(false), meetingError=ref(''); let supervisionSuccessTimer;
async function openSupervisionPicker(){supervisionPickerOpen.value=true;supervisionLoading.value=true;supervisionError.value='';supervisionSuccess.value='';clearTimeout(supervisionSuccessTimer);try{[supervisionReflections.value,supervisionSessions.value]=await Promise.all([getPrivateReflectionsForClient({clientId:props.client.id}),listSessions({clientId:props.client.id})])}catch(error){console.error('Failed to load supervision choices:',error);supervisionError.value='Could not load private reflections for supervision.'}finally{supervisionLoading.value=false}}
function closeSupervisionPicker(){if(!supervisionSaving.value)supervisionPickerOpen.value=false}
async function addSelectedToSupervision(ids){supervisionSaving.value=true;supervisionError.value='';try{const selected=supervisionReflections.value.filter(r=>ids.includes(r.id)&&!r.included_in_supervision);const updated=await Promise.all(selected.map(r=>setReflectionSupervisionSelection({reflectionId:r.id,included:true})));const byId=new Map(updated.map(r=>[r.id,r]));supervisionReflections.value=supervisionReflections.value.map(r=>byId.get(r.id)||r);supervisionPickerOpen.value=false;if(updated.length){supervisionSuccess.value=updated.length===1?'Saved to supervision.':`${updated.length} reflections saved to supervision.`;supervisionSuccessTimer=setTimeout(()=>{supervisionSuccess.value=''},8000)}}catch(error){supervisionError.value='Could not add the selected reflection to supervision.'}finally{supervisionSaving.value=false}}
async function requestArchiveChange(){const archiving=!props.client.archived;const message=archiving?`Archive ${props.client.display_name}? Their records will be retained and the client can be restored later.`:`Restore ${props.client.display_name} to the active caseload?`;if(!window.confirm(message))return;archiveSaving.value=true;archiveError.value='';try{emit('client-updated',await setClientArchived({clientId:props.client.id,archived:archiving}))}catch(error){archiveError.value=archiving?'Could not archive this client.':'Could not restore this client.'}finally{archiveSaving.value=false}}
async function joinMeeting(){if(!props.nextAppointment?.id||!props.nextAppointment?.zoom_meeting_id||joiningMeeting.value)return;joiningMeeting.value=true;meetingError.value='';const popup=window.open('','_blank');if(popup)popup.opener=null;try{const response=await authenticatedFetch('/api/zoom/join-appointment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:props.client.id,appointmentId:props.nextAppointment.id})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.startUrl)throw new Error(data.error||'Unable to open the Zoom appointment.');if(popup)popup.location.replace(data.startUrl);else window.open(data.startUrl,'_blank','noopener,noreferrer')}catch(error){if(popup)popup.close();meetingError.value=error?.message||'Unable to open the Zoom appointment.'}finally{joiningMeeting.value=false}}
async function rejoinSessionVideo(){if(!props.activeSession?.id||joiningMeeting.value)return;joiningMeeting.value=true;meetingError.value='';const popup=window.open('','_blank');if(popup)popup.opener=null;try{const response=await authenticatedFetch('/api/zoom/start-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:props.client.id,sessionRef:props.activeSession.id})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.startUrl)throw new Error(data.error||'Unable to rejoin the Zoom session.');if(popup)popup.location.replace(data.startUrl);else window.open(data.startUrl,'_blank','noopener,noreferrer')}catch(error){if(popup)popup.close();meetingError.value=error?.message||'Unable to rejoin the Zoom session.'}finally{joiningMeeting.value=false}}
const videoLabel=computed(()=>videoProviderService.getVideoActionLabel({videoProvider:'zoom',meetingUrl:props.nextAppointment?.zoom_meeting_id?'available':null,status:'Scheduled'})); const archiveDate=computed(()=>props.client.archived_at?new Date(props.client.archived_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):''); const clientInitials=computed(()=>props.client.display_name?props.client.display_name.split(' ').map(n=>n[0]).join('').substring(0,2).toUpperCase():'??'); const nextAppointmentLabel=computed(()=>props.nextAppointment?.starts_at?new Date(props.nextAppointment.starts_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Not scheduled');
function formatSessionTime(dateString){if(!dateString)return'';return new Date(dateString).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}
</script>
