<template>
  <div class="space-y-stack-lg max-w-4xl mx-auto"><div class="bg-surface-elevated border border-border-muted rounded-panel p-6 shadow-sm">
    <div class="flex items-center justify-between gap-4 mb-8"><div><h3 class="text-h3 font-semibold text-ink">Professional Development</h3><p class="text-body-sm text-ink-muted mt-1">Private therapist reflection prepared for supervision.</p></div><div v-if="loading" class="text-body-sm text-ink-muted">Loading reflection…</div><div v-else class="flex flex-col items-end gap-2"><button @click="toggleSupervisionPack" :disabled="updating||!reflection" class="px-inline-md py-stack-xs border text-body-sm font-medium rounded-control transition-all" :class="reflection?.included_in_supervision?'bg-state-info/10 border-state-info text-state-info':'bg-surface border-border text-ink'">{{ updating?'Updating…':reflection?.included_in_supervision?'Remove from Supervision Pack':'Add to Supervision Pack' }}</button><p v-if="error" role="alert" class="text-xs text-state-danger">{{ error }}</p></div></div>
    <div v-if="!loading&&!reflection" class="rounded-panel border border-border bg-surface-subtle p-6 text-body-sm text-ink-muted">Complete your private Reflection for this session before adding it to supervision.</div>
    <div v-else-if="reflection" class="space-y-4"><div v-for="section in visibleSections" :key="section.title" class="p-5 border border-border rounded-panel bg-surface-subtle"><h4 class="text-body-sm font-bold text-ink uppercase tracking-wider mb-2">{{ section.title }}</h4><p class="text-body-sm text-ink-muted whitespace-pre-wrap leading-relaxed">{{ section.content }}</p></div><div v-if="!visibleSections.length" class="rounded-panel border border-border bg-surface-subtle p-6 text-body-sm text-ink-muted">This reflection does not yet contain professional-development content.</div></div>
  </div></div>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue';import { decodeSessionReflection,getPrivateReflection,setReflectionSupervisionSelection } from '../../lib/reflections.js';
const props=defineProps({clientId:{type:String,required:true},sessionId:{type:String,required:true}});const reflection=ref(null),loading=ref(true),updating=ref(false),error=ref('');
const visibleSections=computed(()=>{if(!reflection.value)return[];const fields=decodeSessionReflection(reflection.value.body);const candidates=[['Supervision Questions',fields.supervisionQuestions||reflection.value.supervision_question],['What Stood Out',fields.stoodOut],['Therapist Emotional Response',fields.emotionalResponse],['Possible Countertransference',fields.countertransference],['Uncertainties or Sticking Points',fields.uncertainties],['Next Session Considerations',fields.nextSession]];return candidates.filter(([,content])=>String(content||'').trim()).map(([title,content])=>({title,content}));});
async function fetchReflection(){loading.value=true;error.value='';try{reflection.value=await getPrivateReflection({clientId:props.clientId,sessionId:props.sessionId});}catch(err){console.error('[SupervisionSummaryTab] Fetch error:',err);error.value='Could not load your private reflection.';}finally{loading.value=false;}}
async function toggleSupervisionPack(){if(!reflection.value||updating.value)return;updating.value=true;error.value='';try{reflection.value=await setReflectionSupervisionSelection({reflectionId:reflection.value.id,included:!reflection.value.included_in_supervision});}catch(err){console.error('[SupervisionSummaryTab] Update error:',err);error.value='Could not update Supervision Pack status.';}finally{updating.value=false;}}
onMounted(fetchReflection);watch(()=>props.sessionId,fetchReflection);
</script>
