<template>
  <div class="flex flex-col gap-stack-md">
    <div v-if="loading || captureLoading" class="min-h-64 flex flex-col items-center justify-center gap-3 rounded-panel border border-border bg-surface p-6 text-center"><span class="w-8 h-8 border-4 border-state-selected border-t-transparent rounded-full animate-spin"></span><p class="text-body text-ink-muted">Checking session capture…</p></div>
    <div v-else-if="error" class="min-h-64 flex flex-col items-center justify-center gap-4 rounded-panel border border-state-danger/20 bg-surface p-6 text-center"><div><h3 class="text-h3 font-semibold text-state-danger">Session capture unavailable</h3><p class="mt-2 text-body text-ink-muted">{{ error }}</p></div><button class="button-primary" @click="$emit('retry')">Retry</button></div>
    <div v-else-if="!transcript" class="min-h-48 flex flex-col items-center justify-center rounded-panel border border-border bg-surface p-6 text-center"><h3 class="text-h3 font-semibold text-ink">Waiting for session capture</h3><p class="mt-2 max-w-lg text-body-sm text-ink-muted">Your Zoom transcript will be linked to this session when it becomes available. You can continue working in Helio normally.</p><p class="mt-4 text-caption text-ink-subtle italic max-w-md">Transcript Inbox is only needed when Helio cannot confidently match an imported transcript.</p></div>
    <template v-else>
      <div class="flex flex-col lg:flex-row gap-6">
        <div class="flex-1 flex flex-col gap-6"><section class="rounded-panel border border-border bg-surface p-5">
          <header><p class="text-caption font-medium uppercase tracking-wider text-action-link">Helio clinical intelligence</p><h3 class="mt-1 text-h3 font-semibold text-ink">Session Capture</h3><p class="mt-2 text-body-sm text-ink-muted">Prepare editable clinical working material from the raw transcript using Helio’s selected therapeutic lens. Zoom’s summary remains separate source material and is never used as the basis for this output.</p></header>
          <div class="mt-6 border-t border-border pt-5"><h4 class="text-body font-semibold text-ink">Confirm speaker identities</h4><p class="mt-1 text-body-sm text-ink-muted">This mapping prepares the editable capture and does not alter the transcript.</p><div v-if="speakerLabels.length" class="mt-4 grid gap-3 sm:grid-cols-2"><label v-for="label in speakerLabels" :key="label" class="text-body-sm"><span class="mb-1 block font-medium text-ink">{{ label }}</span><select v-model="speakerIdentities[label]" class="w-full rounded-control border border-border bg-surface px-3 py-2 text-ink" :disabled="speakersConfirmed || Boolean(captureDraft)"><option value="">Choose identity</option><option>Therapist</option><option>Client</option><option>Other participant</option></select></label></div><p v-else class="mt-3 text-body-sm text-ink-muted">No speaker labels were found. Confirm that the transcript is ready to use.</p><div class="mt-4 flex flex-wrap items-center gap-3"><button v-if="!speakersConfirmed" type="button" class="button-primary" :disabled="!canConfirmSpeakers" @click="confirmSpeakers">Confirm speakers</button><template v-else><p class="text-body-sm font-medium text-state-success">Speaker identities confirmed</p><button v-if="!captureDraft" type="button" class="text-body-sm font-medium text-action-link" @click="speakersConfirmed=false">Change</button></template></div></div>
          <div v-if="speakersConfirmed && !captureDraft" class="mt-6 border-t border-border pt-5"><h4 class="text-body font-semibold text-ink">Prepare session capture</h4><p class="mt-1 text-body-sm text-ink-muted">Helio will prepare editable, transcript-grounded working material. It is not an approved Clinical Record.</p><button type="button" class="button-primary mt-4" :disabled="preparingCapture" @click="prepareSessionCapture(false)">{{ preparingCapture?'Preparing…':'Prepare session capture' }}</button><p v-if="captureError" class="mt-2 text-body-sm text-state-danger" role="alert">{{ captureError }}</p></div>
          <div v-if="captureDraft" class="mt-6 border-t border-border pt-5">
            <div class="rounded-panel border border-state-info/20 bg-state-info/10 p-4"><p class="text-caption font-medium uppercase tracking-wider text-state-info">AI-assisted working material · {{ reviewed?'reviewed':'review required' }}</p><p class="mt-1 text-body-sm text-ink-secondary">Edit, remove or regenerate suggestions. Nothing here is an approved Clinical Record.</p></div>
            <div class="mt-5 grid gap-5"><article v-for="field in captureFields" :key="field.key" class="rounded-panel border border-border p-4"><div class="flex flex-wrap items-center justify-between gap-2"><label :for="`capture-${field.key}`" class="text-body-sm font-semibold text-ink">{{ field.label }}</label><div class="flex gap-3"><button type="button" class="text-caption font-medium text-action-link" @click="showSource">View source</button><button v-if="!dismissedFields.includes(field.key)" type="button" class="text-caption font-medium text-state-danger" @click="removeField(field.key)">Remove</button><button v-else type="button" class="text-caption font-medium text-action-link" @click="restoreField(field.key)">Restore</button></div></div><p v-if="dismissedFields.includes(field.key)" class="mt-3 text-body-sm italic text-ink-muted">Removed from this review. It will stay empty when you regenerate.</p><textarea v-else :id="`capture-${field.key}`" v-model="captureDraft[field.key]" rows="3" class="mt-3 w-full rounded-control border border-border bg-surface px-3 py-2 text-ink focus:border-state-selected focus:outline-none" @input="markWorking"></textarea></article></div>
            <div class="mt-6 rounded-panel border border-border bg-surface-subtle p-4"><label for="capture-guidance" class="text-body font-semibold text-ink">Add anything Helio should consider</label><p class="mt-1 text-body-sm text-ink-muted">Type or dictate your observations. Helio treats this as therapist input, separately from transcript evidence.</p><textarea id="capture-guidance" v-model="therapistGuidance" rows="4" class="mt-3 w-full rounded-control border border-border bg-surface px-3 py-2 text-ink" placeholder="Add context, corrections or emphasis…" @input="markWorking"></textarea><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><p v-if="dictationError" class="text-caption text-state-danger" role="alert">{{ dictationError }}</p><p v-else class="text-caption text-ink-muted">Audio is transcribed and is not retained.</p><button type="button" class="px-3 py-2 rounded-control border border-border bg-surface text-body-sm font-medium text-ink" :disabled="preparingCapture || transcribing" @click="toggleDictation">🎙️ {{ dictationLabel }}</button></div></div>
            <div class="mt-5 flex flex-wrap items-center gap-3"><button type="button" class="button-primary" :disabled="preparingCapture || transcribing" @click="prepareSessionCapture(true)">{{ preparingCapture?'Regenerating…':'Regenerate with my input' }}</button><button v-if="history.length" type="button" class="px-4 py-2 rounded-control border border-border bg-surface text-body-sm font-medium text-ink" @click="restorePrevious">Restore previous version</button><span v-if="saveState" class="text-caption" :class="saveState==='Saved'?'text-state-success':'text-ink-muted'">{{ saveState }}</span></div><p v-if="captureError" class="mt-2 text-body-sm text-state-danger" role="alert">{{ captureError }}</p>
            <div class="mt-6 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-5"><p class="text-body-sm text-ink-muted">Mark reviewed when this capture reflects your working understanding. Downstream steps remain separate.</p><button type="button" class="button-primary" :disabled="saving || reviewed" @click="markReviewed">{{ reviewed?'Session Capture reviewed':'Mark Session Capture reviewed' }}</button></div>
          </div>
          <div class="mt-6 border-t border-border pt-5" data-testid="session-source-material">
            <p class="text-caption font-medium uppercase tracking-wider text-ink-muted">Optional source material</p>
            <h4 class="mt-1 text-body font-semibold text-ink">Zoom summary and raw transcript</h4>
            <p class="mt-1 text-body-sm text-ink-muted">These imported sources remain unchanged and separate from Helio’s Session Capture and Clinical Record.</p>
            <div v-if="transcript.sourceSummary" class="mt-4"><button type="button" class="text-body-sm font-medium text-action-link" :aria-expanded="isZoomSummaryVisible" aria-controls="zoom-summary-content" @click="isZoomSummaryVisible=!isZoomSummaryVisible">{{ isZoomSummaryVisible ? 'Hide Zoom-generated summary' : 'Review Zoom-generated summary' }}</button><div v-if="isZoomSummaryVisible" id="zoom-summary-content" class="mt-4 max-h-[36rem] overflow-auto whitespace-pre-wrap break-words rounded-panel bg-surface-subtle p-4 text-body-sm leading-relaxed text-ink-secondary">{{ transcript.sourceSummary }}</div></div>
            <div class="mt-4"><button type="button" class="text-body-sm font-medium text-action-link" :aria-expanded="isTranscriptVisible" aria-controls="session-transcript-content" @click="isTranscriptVisible=!isTranscriptVisible">{{ isTranscriptVisible ? 'Hide raw transcript' : 'Review raw transcript' }}</button><pre v-if="isTranscriptVisible" id="session-transcript-content" ref="transcriptPanel" class="mt-4 max-h-[36rem] overflow-auto whitespace-pre-wrap break-words rounded-panel bg-surface-subtle p-4 font-mono text-body-sm leading-relaxed text-ink-secondary">{{ transcript.text }}</pre></div>
          </div>
        </section></div>
        <div class="w-full lg:w-72"><WorkflowStatusPanel :workflowItems="workflowProgress" :activeStage="activeTab" /></div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { authenticatedFetch } from '../../lib/api.js'
import { getSessionCapture, normalizeCaptureContent, saveSessionCapture } from '../../lib/sessionCaptures.js'
import WorkflowStatusPanel from './WorkflowStatusPanel.vue'
const props=defineProps({transcript:{type:Object,default:null},clientId:{type:String,required:true},sessionId:{type:String,required:true},loading:Boolean,error:{type:String,default:''},activeTab:String});defineEmits(['retry'])
const captureFields=[{key:'presentingConcerns',label:'Presenting concerns'},{key:'sessionThemes',label:'Session themes'},{key:'interventionsUsed',label:'Interventions used'},{key:'clientResponse',label:'Client response'},{key:'riskSafeguarding',label:'Risk and safeguarding'},{key:'progressGoals',label:'Progress and goals'},{key:'planNextSession',label:'Plan for next session'}]
const isZoomSummaryVisible=ref(false),isTranscriptVisible=ref(false),transcriptPanel=ref(null),speakersConfirmed=ref(false),preparingCapture=ref(false),captureLoading=ref(false),captureError=ref(''),captureDraft=ref(null),generatedContent=ref(null),therapistGuidance=ref(''),dismissedFields=ref([]),history=ref([]),version=ref(0),reviewed=ref(false),saving=ref(false),saveState=ref(''),speakerIdentities=reactive({}),activeRecording=ref(false),transcribing=ref(false),dictationError=ref('');let recorder=null,stream=null,chunks=[],saveTimer=null
function findSpeakerLabels(text){const labels=[],seen=new Set();for(const line of String(text||'').split(/\r?\n/)){const match=line.match(/^\s*(?:\[[^\]]+\]\s*)?((?:Speaker\s+\w+)|Therapist|Client|Participant\s+\w+):/i);if(!match)continue;const label=match[1].trim();if(!seen.has(label.toLowerCase())){seen.add(label.toLowerCase());labels.push(label)}}return labels}
const speakerLabels=computed(()=>findSpeakerLabels(props.transcript?.text)),canConfirmSpeakers=computed(()=>!speakerLabels.value.length||speakerLabels.value.every(label=>speakerIdentities[label])),dictationLabel=computed(()=>transcribing.value?'Transcribing…':activeRecording.value?'Stop recording':'Dictate')
watch(()=>props.transcript?.id,loadCapture,{immediate:true})
async function loadCapture(){if(!props.transcript?.id)return;captureLoading.value=true;captureError.value='';try{const saved=await getSessionCapture({sessionId:props.sessionId,clientId:props.clientId});for(const key of Object.keys(speakerIdentities))delete speakerIdentities[key];if(saved&&saved.transcript_id===props.transcript.id){Object.assign(speakerIdentities,saved.speaker_identities||{});speakersConfirmed.value=true;captureDraft.value=normalizeCaptureContent(saved.content);generatedContent.value=normalizeCaptureContent(saved.generated_content);therapistGuidance.value=saved.therapist_guidance||'';dismissedFields.value=saved.dismissed_fields||[];history.value=saved.previous_versions||[];version.value=saved.version||0;reviewed.value=saved.status==='reviewed';saveState.value='Saved'}else{speakerLabels.value.forEach(label=>speakerIdentities[label]=/^therapist$/i.test(label)?'Therapist':(/^client$/i.test(label)?'Client':''));speakersConfirmed.value=false;captureDraft.value=null;version.value=0}}catch(err){console.error(err);captureError.value='Saved Session Capture could not be loaded.'}finally{captureLoading.value=false}}
function confirmSpeakers(){if(canConfirmSpeakers.value)speakersConfirmed.value=true}function snapshot(){return{content:normalizeCaptureContent(captureDraft.value),guidance:therapistGuidance.value,dismissedFields:[...dismissedFields.value],savedAt:new Date().toISOString()}}function markWorking(){reviewed.value=false;saveState.value='Unsaved changes';scheduleSave()}function removeField(key){history.value=[...history.value,snapshot()].slice(-10);captureDraft.value[key]='';dismissedFields.value=[...new Set([...dismissedFields.value,key])];markWorking()}function restoreField(key){dismissedFields.value=dismissedFields.value.filter(item=>item!==key);markWorking()}function restorePrevious(){const previous=history.value.at(-1);if(!previous)return;history.value=history.value.slice(0,-1);captureDraft.value=normalizeCaptureContent(previous.content);therapistGuidance.value=previous.guidance||'';dismissedFields.value=previous.dismissedFields||[];markWorking()}function showSource(){isTranscriptVisible.value=true;nextTick(()=>transcriptPanel.value?.scrollIntoView({behavior:'smooth',block:'center'}))}function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>persist('working'),900)}
async function persist(status=reviewed.value?'reviewed':'working'){if(!captureDraft.value||saving.value)return;saving.value=true;saveState.value='Saving…';try{const saved=await saveSessionCapture({sessionId:props.sessionId,clientId:props.clientId,transcriptId:props.transcript.id,speakerIdentities:{...speakerIdentities},generatedContent:generatedContent.value||captureDraft.value,content:captureDraft.value,therapistGuidance:therapistGuidance.value,dismissedFields:dismissedFields.value,previousVersions:history.value,status,expectedVersion:version.value});version.value=saved.version;reviewed.value=saved.status==='reviewed';saveState.value='Saved'}catch(err){saveState.value='Could not save';captureError.value=err.code==='SESSION_CAPTURE_CONFLICT'?'This Session Capture changed in another tab. Reload it before continuing.':'Session Capture could not be saved.'}finally{saving.value=false}}
async function prepareSessionCapture(regenerate){if(!props.transcript?.id||!speakersConfirmed.value||preparingCapture.value)return;clearTimeout(saveTimer);preparingCapture.value=true;captureError.value='';if(regenerate&&captureDraft.value)history.value=[...history.value,snapshot()].slice(-10);try{const response=await authenticatedFetch('/api/ai/transcript-clinical-summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcriptId:props.transcript.id,speakerIdentities:{...speakerIdentities},therapistGuidance:regenerate?therapistGuidance.value:'',dismissedFields:regenerate?dismissedFields.value:[]})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||'Session capture is temporarily unavailable.');const draft=normalizeCaptureContent(payload.data?.draft);captureDraft.value=draft;generatedContent.value=draft;reviewed.value=false;await persist('working')}catch(err){captureError.value=err.message||'Session capture is temporarily unavailable.'}finally{preparingCapture.value=false}}
async function markReviewed(){clearTimeout(saveTimer);await persist('reviewed')}async function toggleDictation(){if(activeRecording.value){recorder?.stop();return}dictationError.value='';try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=processDictation;recorder.start();activeRecording.value=true}catch{dictationError.value='Microphone access was unavailable. You can continue by typing.'}}
async function processDictation(){activeRecording.value=false;stream?.getTracks().forEach(track=>track.stop());const blob=new Blob(chunks,{type:recorder?.mimeType||'audio/webm'});if(!blob.size)return;transcribing.value=true;try{const audio=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});const response=await authenticatedFetch('/api/ai/transcribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||'Dictation could not be transcribed.');const text=String(payload.text||'').trim();if(text){therapistGuidance.value=[therapistGuidance.value.trim(),text].filter(Boolean).join('\n');markWorking()}}catch(err){dictationError.value=err.message||'The recording could not be transcribed. Your audio was not saved.'}finally{transcribing.value=false}}
const workflowProgress=computed(()=>[{label:'Recording',status:'Complete'},{label:'Session Capture',status:reviewed.value?'Complete':'In Progress'},{label:'Notes',status:'Not Started'},{label:'Reflection',status:'Not Started'},{label:'Clinical Record',status:'Not Started'},{label:'Professional Development',status:'Not Started'}]);onBeforeUnmount(()=>{clearTimeout(saveTimer);if(recorder?.state&&recorder.state!=='inactive')recorder.stop();stream?.getTracks().forEach(track=>track.stop())})
</script>
