// Authored content, committed with the bank version. Each row corresponds to
// the original q01–q15 weight matrix (a, b, c, d); never generated at runtime.
export const questionVariants = [
  [
    ['Choosing a session priority', 'A client brings several concerns and asks which to tackle first. What would you usually offer?', 'Suggest a priority and a manageable action to begin with.', 'Invite them to choose the concern whose meaning they want to explore.', 'Ask them to choose a concern and identify a practical step they want to try.', 'Offer a possible thread connecting the concerns as an invitation to understand them together.'],
    ['Naming a difficult reaction', 'A client wonders why a minor disagreement affected them so strongly. Where would you tend to begin?', 'Offer a tentative explanation of the reaction and check whether it fits.', 'Let them lead with their description of the disagreement and what mattered in it.', 'Ask focused questions about what happened and how they experienced it, before explaining.', 'Invite them to choose among possible explanations to explore together.'],
    ['Making room for sadness', 'A client feels sad while discussing a loss and says it feels manageable to continue. Which approach would you usually offer?', 'Agree a sequence for examining their thoughts and meanings about the loss.', 'Stay with the feeling and follow what becomes noticeable as the session unfolds.', 'Offer a short, clearly bounded exercise attending to the felt sadness.', 'Follow the meanings they bring to the loss without setting a sequence.'],
    ['Talking about anger', 'A client gives a detailed explanation of an argument. You are curious about how they experience the anger. What attracts your attention first?', 'Discuss a tentative explanation of the pattern in their account.', 'Invite them to notice feelings and sensations while describing it, before explaining.', 'Clarify what their own words mean to them without proposing a theory.', 'Offer an experiential exploration informed by a tentative account of the anger.'],
    ['Finding words', 'A client pauses and says they cannot quite find the words. There is no immediate safety concern. What would you usually do?', 'Offer a focused question to help articulate what seems hard to say.', 'Leave them room to choose how to express what they notice in the pause.', 'Invite shared attention to what the pause feels like right now.', 'Let them choose whether to think through the difficulty with words or move elsewhere.'],
    ['Recognising support', 'A client says they feel more able to accept support. What would you most want to understand?', 'Discuss a tentative account of what has shifted in their recent interactions.', 'Explore their description of how receiving support relates to earlier relationships.', 'Ask what accepting support looks like in their current life, before explaining.', 'Consider whether a longstanding relational pattern may help explain the shift.'],
    ['A possible cycle', 'You notice a possible cycle in a client’s relationships but remain uncertain. How would you tend to explore it?', 'Agree a focused review of the tentative cycle, including examples that contradict it.', 'Follow further descriptions as they arise without organising them around the hypothesis.', 'Agree a careful description of specific interactions before deciding on an explanation.', 'Hold the tentative cycle lightly and return to it when relevant material emerges.'],
    ['Trying a new format', 'A client wants to approach sessions differently. Which offer would be most characteristic?', 'Propose a specific activity with an agreed sequence and review.', 'Let them choose a direction and develop a format from what emerges.', 'Help them choose an activity within a repeatable format for reviewing it.', 'Offer an improvised exploration guided by what you notice in this session.'],
    ['Preparing for a break', 'An agreed break in therapy is approaching. What would you tend to favour in the remaining sessions?', 'Plan a sequence around difficulties the client currently encounters.', 'Allow emerging material to guide exploration of earlier experiences.', 'Agree a bounded review of earlier learning relevant to the work.', 'Keep sessions open to whichever current situations become most relevant.'],
    ['Expecting disappointment', 'A client seems to expect disappointment from you. You can explore this together. Where would you tend to start?', 'Name a particular recent interaction between you and invite discussion.', 'Let them choose which familiar expectations from earlier relationships to explore.', 'Invite them to describe what they notice between you now and choose the next direction.', 'Propose exploring how earlier relational experiences connect with the expectation.'],
    ['Feeling judged', 'A client often feels judged in social settings. Which starting point most appeals?', 'Map interpretations and predictions in a recent social situation.', 'Attend to feelings and sensations evoked by memories of earlier judgement.', 'Build an account of how meanings about judgement developed in earlier life.', 'Notice the sensations and feelings present while describing a recent encounter.'],
    ['Insight and daily life', 'A client has a clearer account of a difficulty but says daily life feels unchanged. What would you usually offer?', 'Use that account to plan a small practical experiment.', 'Explore the felt experience of daily life without requiring an immediate change.', 'Examine what remains unclear in the account you have developed.', 'Invite an experiential rehearsal of a different response.'],
    ['A quieter week', 'A client has had a quiet week and no pressing concern. How would you usually shape the session?', 'Return to an agreed goal and plan a tangible action.', 'Follow what begins to seem meaningful without fixing a destination.', 'Agree a focused question to understand without setting a task.', 'Follow emerging material and use an opening for practical experimentation.'],
    ['A new confidence', 'A client feels more confident, though its origins have received little attention. What interests you next?', 'Consolidate what helps now and agree practical next steps.', 'Understand the shift within their longer personal story.', 'Explore changes in earlier strategies to inform future action.', 'Deepen their account of what confidence means in present life.'],
    ['Revisiting expectations', 'A client says therapy has taken an unexpected direction. You agree to revisit their expectations. Where would you begin?', 'Offer a tentative explanation of the divergence to inform an adjustment.', 'Describe their experience of the divergence before explaining or changing it.', 'Ask what they expected in concrete terms and agree an adjustment from that account.', 'Explore a tentative meaning of the divergence before deciding on changes.']
  ],
  [
    ['An uncertain next step', 'A client asks for help deciding how to respond to a strained friendship. What would usually be your first move?', 'Suggest a possible response and a small way to try it.', 'Invite them to lead an exploration of what the friendship and dilemma mean.', 'Help them choose a practical response using their own priorities.', 'Offer a tentative understanding of the dilemma to think about together.'],
    ['Looking for an explanation', 'A client asks whether a recurring difficulty fits a familiar psychological pattern. How would you tend to begin?', 'Offer a provisional formulation and discuss its usefulness and limits.', 'Invite them to choose which experiences they want to describe and have recognised.', 'Guide a detailed description of concrete examples before using a framework.', 'Ask which possible frameworks interest them and let that guide exploration.'],
    ['Staying with relief', 'A client feels unexpected relief while talking and is comfortable exploring it. What would you usually offer?', 'Agree a sequence for examining the thoughts and meanings linked to the relief.', 'Follow how the relief feels and what emerges from attending to it.', 'Offer a short experiential exercise with a clear ending to explore the relief.', 'Follow their ideas about the relief without organising the discussion in advance.'],
    ['A careful account', 'A client recounts a difficult decision in careful, analytical language. What would you tend to explore first?', 'Offer a tentative explanatory account and examine it together.', 'Attend to what they notice emotionally or physically while speaking.', 'Clarify the distinctions in their own description before explaining.', 'Try an experiential exploration guided by a provisional hypothesis.'],
    ['A hesitant beginning', 'A client starts several sentences and stops. You have checked that there is no urgent concern. What feels most natural?', 'Ask a focused question to help give the hesitation words.', 'Allow them to choose when and how to express what they notice.', 'Invite immediate attention to the experience of hesitating together.', 'Let them choose whether to discuss possible meanings or another topic.'],
    ['Feeling heard', 'A client says they feel heard in a new way. What would you be most interested in understanding?', 'Whether a tentative account of recent interactions explains that experience.', 'Their own account of how this compares with being heard earlier in life.', 'What feeling heard means in their current life before interpreting it.', 'Whether an earlier relational pattern helps explain what now feels different.'],
    ['Questioning an assumption', 'You suspect an assumption is shaping the work, but you have only a few examples. How would you handle it?', 'Agree a systematic examination of the tentative assumption and counterexamples.', 'Follow further accounts without structuring the work around the assumption.', 'Organise descriptions of particular situations before explaining the pattern.', 'Keep the tentative assumption in mind and revisit it as material emerges.'],
    ['Between-session practice', 'A client asks about practising something between sessions. How would you usually develop the idea?', 'Suggest a defined practice and an agreed method for reviewing it.', 'Invite them to choose the direction and let a practice develop from the conversation.', 'Co-design a repeatable practice with the client choosing its focus.', 'Offer an improvised exploration now as a possible source of ideas.'],
    ['Reviewing a short block', 'You are halfway through an agreed short block of therapy. What would you usually favour next?', 'Plan the remaining sessions around a current recurring problem.', 'Let emerging material guide which earlier experiences you explore.', 'Agree a structured review of earlier experiences connected to the concern.', 'Leave sessions open to current situations as they become relevant.'],
    ['Disagreeing with you', 'A client says disagreeing with you feels difficult. Which invitation would you tend to make first?', 'Name a recent moment of disagreement between you and examine it together.', 'Let them choose which earlier experiences of disagreement feel relevant.', 'Invite them to describe the difficulty here and decide what to explore.', 'Propose examining the history of the pattern through your interaction.'],
    ['Anticipating failure', 'A client frequently anticipates failure when attempting something important. Where would you tend to begin?', 'Examine thoughts and predictions about a recent attempt.', 'Attend to how earlier experiences of failure are felt as they remember them.', 'Build a shared account of how expectations developed over time.', 'Notice present feelings and sensations while describing a recent attempt.'],
    ['Knowing and doing', 'A client says knowing their pattern has not yet changed their response. What would you usually offer?', 'Use the shared account to plan and review a behavioural experiment.', 'Explore what being caught in the pattern feels like without requiring a shift.', 'Clarify what your shared account has not yet explained.', 'Rehearse a different response through an in-session experience.'],
    ['An open session', 'A client asks to use the session without bringing a particular topic. Within your agreement, what would you favour?', 'Return to a goal and identify a practical step.', 'Allow a significant theme to emerge without fixing an aim.', 'Agree a focused topic for deeper understanding without an action task.', 'Follow what arises and look for an opportunity to try a new response.'],
    ['A helpful boundary', 'A client reports setting a helpful boundary, without much discussion of its history. What would interest you next?', 'Consolidating how the boundary works now and planning practical next steps.', 'Understanding this shift in relation to their longer development.', 'Exploring how earlier responses have changed to inform future boundaries.', 'Clarifying what the boundary means in present life without returning to origins.'],
    ['Pace of therapy', 'A client says the pace of therapy does not suit them. You take this seriously. Where would you usually begin?', 'Suggest a tentative explanation of the mismatch to help agree a change.', 'Explore their experience of the pace before explaining or adjusting it.', 'Describe the pace they want and agree a practical adjustment from that description.', 'Consider a tentative meaning of the pace together before changing the format.']
  ],
  [
    ['Responding to an invitation', 'A client asks how to handle an invitation they feel ambivalent about. What would usually be your first move?', 'Offer a provisional suggestion and discuss a small action they could take.', 'Let them lead an exploration of the ambivalence and its meaning.', 'Help them choose a concrete response based on their priorities.', 'Offer a tentative account of the ambivalence as a starting point for understanding.'],
    ['Making sense of change', 'A client asks why they react differently at work and at home. How would you tend to begin?', 'Offer a tentative formulation of the difference and test whether it fits.', 'Invite them to choose which experiences to describe and what the difference means.', 'Ask focused questions about each setting before suggesting a framework.', 'Let them choose among possible explanations to examine together.'],
    ['A moment of warmth', 'A client notices a feeling of warmth toward someone they have struggled with. They want to explore it. What would you offer?', 'Agree a sequence for examining thoughts and meanings associated with the warmth.', 'Stay with the felt experience and follow what arises.', 'Offer a bounded exercise attending to the warmth with an agreed ending.', 'Follow their ideas about the warmth without choosing a sequence.'],
    ['Explaining a disappointment', 'A client gives an articulate account of a disappointment. You want to understand more. What would attract you first?', 'Discuss a tentative explanation of what seems to organise the experience.', 'Invite noticing the immediate feelings and sensations while speaking.', 'Clarify their own descriptions and distinctions without proposing an explanation.', 'Suggest an experiential exploration informed by a tentative account.'],
    ['A pause after a question', 'A client becomes quiet after a question. There is no indication of immediate danger. What would you tend to do?', 'Ask a focused question to help put the pause into words.', 'Leave room for them to decide when to speak about what they notice.', 'Invite attention to the immediate experience of the pause together.', 'Let them choose whether to think about its meaning or move to another topic.'],
    ['Trusting their judgement', 'A client says they trust their own judgement more. What would you want to understand next?', 'Whether a tentative explanation of recent changes helps make sense of this.', 'How they describe the difference from earlier experiences of trusting themselves.', 'What trusting themselves looks like now before proposing an explanation.', 'Whether a longstanding pattern helps explain this shift in self-trust.'],
    ['Holding a formulation lightly', 'A formulation seems promising, but some of the client’s accounts do not fit. What would you tend to do?', 'Agree a focused examination of the formulation and the material against it.', 'Set it aside and follow further descriptions as they emerge.', 'Organise concrete descriptions before deciding whether any formulation is useful.', 'Keep it provisional and revisit it when the session material invites it.'],
    ['A more active session', 'A client asks for a more active way of working. What would you tend to offer?', 'Propose a defined activity with a clear sequence and review.', 'Invite their choice of direction and build the activity as the session unfolds.', 'Agree a repeatable format in which they choose the activity’s focus.', 'Offer an improvised exploration led by what you notice happening now.'],
    ['An agreed ending', 'You and a client are preparing for an agreed ending with several sessions left. What would you favour?', 'Plan a sequence for addressing current difficulties and consolidating the work.', 'Let emerging material guide attention to earlier experiences.', 'Agree a bounded review of earlier learning connected with the work.', 'Keep the sessions open to whichever current concerns arise.'],
    ['A wish to please', 'A client wonders whether they try to please you in sessions. Where would you tend to begin together?', 'Name a specific interaction you noticed and invite examination of it now.', 'Let them choose which earlier relationships seem relevant to that wish.', 'Invite their account of what happens between you now and let them choose a direction.', 'Propose examining the history of pleasing others through your relationship.'],
    ['Difficulty receiving praise', 'A client finds praise uncomfortable and agrees to explore it. What would most appeal as a starting point?', 'Map thoughts and meanings around a recent instance of praise.', 'Attend to feelings and sensations evoked by earlier memories of praise.', 'Develop an account of how meanings about praise formed over time.', 'Notice current feelings and sensations while discussing a recent instance.'],
    ['A familiar impasse', 'A client understands a recurring impasse but still encounters it. What would you usually offer next?', 'Use your shared account to design a small practical experiment.', 'Explore the felt quality of the impasse without requiring immediate movement.', 'Examine the account for meanings that remain unclear or unexplained.', 'Offer an experiential rehearsal of approaching the impasse differently.'],
    ['Room to reflect', 'A client arrives feeling settled and open to reflection. How would you tend to shape the session?', 'Return to an agreed goal and choose a tangible action.', 'Follow what becomes significant without deciding what understanding must result.', 'Agree a focused question to deepen understanding without setting a task.', 'Let material emerge and use any opening for trying a different response.'],
    ['A changed routine', 'A client reports a helpful change in their routine, with little discussion of earlier life. What interests you next?', 'Consolidating what works now and deciding on practical next steps.', 'Understanding how the change fits their longer personal development.', 'Considering changes in earlier strategies to guide future action.', 'Exploring what the change means in their current experience.'],
    ['Changing the focus', 'A client says the current focus of therapy no longer feels useful. How would you tend to begin?', 'Offer a tentative account of the mismatch and use it to propose an adjustment.', 'Explore their experience of what feels missing before explaining or changing focus.', 'Ask what would feel useful in concrete terms and agree an adjustment from that account.', 'Explore a tentative meaning of the mismatch before deciding on a new focus.']
  ]
]
