<template>
  <PublicPageShell title="AI & data processing" eyebrow="Transparency" summary="How AI-assisted features fit within therapist-controlled clinical work.">
    <section><h2 class="type-subsection">Therapist-triggered assistance</h2><p class="mt-2 type-body text-ink-secondary">AI-assisted features are intended to run when a therapist chooses to use them. Their output is suggestion material for professional review, not an autonomous clinical decision.</p></section>
    <section><h2 class="type-subsection">Current provider</h2><p class="mt-2 type-body text-ink-secondary">Helios currently uses OpenAI through server-side Helios functions for supported AI text assistance and audio dictation/transcription. The application does not expose the provider API key to the browser. Only material needed for the feature the therapist invokes should be sent for that processing.</p></section>
    <section><h2 class="type-subsection">Drafts are not Clinical Records</h2><p class="mt-2 type-body text-ink-secondary">Transcripts, generated summaries, suggested wording and editable notes do not become immutable Clinical Records automatically. A therapist must deliberately review and approve a Clinical Record.</p></section>
    <section><h2 class="type-subsection">Human responsibility</h2><p class="mt-2 type-body text-ink-secondary">Therapists remain responsible for checking AI-assisted material for accuracy, relevance and appropriateness before relying on it. Helios should not be used as a substitute for clinical judgement.</p></section>
    <section><h2 class="type-subsection">Production data terms</h2><p class="mt-2 type-body text-ink-secondary">Before public launch, Helios must verify and document the production provider terms that apply to submitted content, including retention, model-training treatment and any international-transfer safeguards. This page does not claim arrangements that have not yet been contractually verified.</p></section>
    <section><h2 class="type-subsection">Questions</h2><p class="mt-2 type-body text-ink-secondary">Questions about Helios AI or data handling can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
