<template>
  <PublicPageShell title="AI & data processing" eyebrow="Transparency" summary="How AI-assisted features fit within therapist-controlled clinical work during current Helios use.">
    <section><h2 class="type-subsection">Therapist-triggered assistance</h2><p class="mt-2 type-body text-ink-secondary">AI-assisted features are intended to run when a therapist chooses to use them. Their output is suggestion material for professional review, not an autonomous clinical decision.</p></section>
    <section><h2 class="type-subsection">Current provider</h2><p class="mt-2 type-body text-ink-secondary">Helios currently uses OpenAI through server-side Helios functions for supported AI text assistance and audio dictation/transcription. The application does not expose the provider API key to the browser. Only material needed for the feature the therapist invokes should be sent for that processing.</p></section>
    <section><h2 class="type-subsection">Current data handling</h2><p class="mt-2 type-body text-ink-secondary">When a therapist deliberately uses an AI or dictation feature, the material needed for that request is sent to OpenAI through Helios' server-side API. OpenAI states that data submitted through its business/API products is not used to train its models by default. Provider retention and processing are also subject to the terms and controls applying to the Helios API account, and Helios will update this page if those arrangements materially change.</p></section>
    <section><h2 class="type-subsection">Google Workspace data and AI</h2><p class="mt-2 type-body text-ink-secondary">Helios' use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. Raw, aggregated or derived Google Workspace API user data is not used, transferred or sold to create, train or improve generalized or foundational artificial intelligence or machine-learning models. Google Workspace API data is used only for permitted user-facing functionality requested by the therapist.</p></section>
    <section><h2 class="type-subsection">Drafts are not Clinical Records</h2><p class="mt-2 type-body text-ink-secondary">Transcripts, generated summaries, suggested wording and editable notes do not become immutable Clinical Records automatically. A therapist must deliberately review and approve a Clinical Record.</p></section>
    <section><h2 class="type-subsection">Human responsibility</h2><p class="mt-2 type-body text-ink-secondary">Therapists remain responsible for checking AI-assisted material for accuracy, relevance and appropriateness before relying on it. Helios should not be used as a substitute for clinical judgement.</p></section>
    <section><h2 class="type-subsection">Questions</h2><p class="mt-2 type-body text-ink-secondary">Questions about Helios AI or data handling can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
