<template>
  <div class="flex flex-col h-full bg-surface-canvas">
    <div v-if="loading" class="flex-1 flex items-center justify-center"><div class="text-ink-muted flex flex-col items-center gap-2"><span class="w-8 h-8 border-4 border-state-selected border-t-transparent rounded-full animate-spin"></span><p>Loading client workspace…</p></div></div>
    <div v-else-if="error" class="flex-1 flex items-center justify-center p-inline-lg"><div class="max-w-md w-full bg-surface p-inline-lg py-stack-lg rounded-card shadow-sm border border-state-danger/20 text-center"><h2 class="text-h2 font-semibold text-state-danger mb-2">Workspace Error</h2><p class="text-ink-secondary mb-6">{{ error }}</p><button @click="loadClient" class="px-inline-md py-stack-sm bg-state-selected text-white rounded-control">Try Again</button></div></div>
    <template v-else-if="client">
      <ClientWorkspaceHeader :client="client" :next-appointment="nextAppointment" :therapist-label="therapistLabel" :active-session="activeSession" :elapsed-time="elapsedTime" :session-busy="sessionBusy" :session-error="sessionError" @create-document="newDocument" @client-updated="client = $event" @start-session="startSession" @open-clinical-workspace="openClinicalWorkspace" @end-session="confirmEndSession" />
      <ClientWorkspaceTabs :tabs="tabs" v-model:activeTab="activeTab" />
      <div class="flex-1 overflow-auto p-inline-lg py-stack-lg"><div class="max-w-6xl mx-auto space-y-stack-lg">
        <div v-if="client.archived" class="rounded-panel border border-border bg-surface-elevated px-inline-lg py-stack-md text-body-sm text-ink-secondary"><strong class="text-ink">Archived client.</strong> Historical records remain available. Restore the client before starting a new session, joining a meeting, or scheduling a new appointment.</div>
        <div v-if="activeTab === 'Overview'" class="space-y-stack-lg">
          <ClinicalAttentionPanel :client="client" />
          <div class="grid grid-cols-1 lg:grid-cols-3 gap-stack-lg"><div class="lg:col-span-2 space-y-stack-lg">
            <section class="bg-surface-elevated border border-border-muted rounded-panel p-inline-lg"><h3 class="text-h3 font-semibold text-ink mb-stack-md pt-stack-md">Recent Sessions</h3><div class="space-y-stack-md pb-stack-md"><p v-if="sessionsLoading" class="text-body-sm text-ink-muted">Loading sessions…</p><template v-else-if="recentSessions.length"><div v-for="session in recentSessions" :key="session.id" class="flex flex-col p-inline-md border border-border rounded-control bg-surface-subtle"><div class="flex justify-between items-start gap-inline-md"><div><span class="font-medium text-ink">Session</span><p class="text-body-sm text-ink-secondary mt-1">{{ sessionSummary(session) }}</p></div><div class="text-right shrink-0"><span class="text-caption text-ink-muted block">{{ formatSessionDate(session.startedAt) }}</span><span v-if="session.status === 'in_progress'" class="text-caption font-medium text-action-link block mt-1">In progress · {{ elapsedTime }}</span><span v-else-if="sessionDurationLabel(session)" class="text-caption font-medium text-ink-secondary block mt-1">{{ sessionTimeRange(session) }} · {{ sessionDurationLabel(session) }}</span></div></div></div></template><p v-else class="text-body-sm text-ink-muted">No sessions recorded for this client yet.</p></div></section>
            <CurrentCareFocus :key="careRefreshKey" :client-id="String(route.params.clientId)" :lens-id="selectedLensId" @open-care="activeTab = 'Care'" />
            <div class="grid grid-cols-1 md:grid-cols-2 gap-stack-lg">
              <section class="bg-surface-elevated border border-border-muted rounded-panel p-inline-lg"><h3 class="text-h3 font-semibold text-ink mb-stack-md pt-stack-md">Recent Documents</h3><div class="space-y-stack-sm pb-stack-md"><button v-for="doc in documents.slice(0, 4)" :key="doc.id" type="button" @click="openDocument(doc)" class="w-full text-left flex items-center justify-between p-inline-md border border-border rounded-control bg-surface hover:border-action-link"><div class="flex flex-col min-w-0 flex-1"><div class="flex items-center gap-inline-sm flex-wrap"><span class="text-body-sm text-ink truncate font-medium">{{ doc.title }}</span><StatusBadge :status="doc.status" /></div><span class="text-caption text-ink-muted mt-0.5">{{ formatDate(doc.updatedAt) }}</span></div><span class="text-ink-subtle ml-2">→</span></button><p v-if="!documents.length && !documentsLoading" class="text-body-sm text-ink-muted">No client documents yet.</p></div></section>
              <ClientFollowUps :client-id="String(route.params.clientId)" />
            </div>
          </div><div class="space-y-stack-lg"><div class="bg-surface-elevated border border-border-muted rounded-panel p-inline-lg"><h3 class="text-h3 font-semibold text-ink mb-stack-md pt-stack-md">Next Appointment</h3><p v-if="appointmentsLoading" class="text-body-sm text-ink-muted pb-stack-md">Loading appointment…</p><div v-else-if="nextAppointment" class="pb-stack-md"><p class="text-body-sm font-medium text-ink">{{ formatDate(nextAppointment.starts_at) }}</p><p class="text-caption text-ink-muted mt-1">{{ nextAppointment.status === 'rescheduled' ? 'Rescheduled' : 'Scheduled' }}</p></div><p v-else class="text-body-sm text-ink-muted pb-stack-md">No upcoming appointment is recorded.</p></div><div class="bg-surface-elevated border border-border-muted rounded-panel p-inline-lg"><h3 class="text-h3 font-semibold text-ink mb-stack-md pt-stack-md">Care Team</h3><p class="text-body-sm text-ink-muted pb-stack-md">Primary therapist: {{ therapistLabel }}</p></div></div></div>
        </div>
        <section v-else-if="activeTab === 'Sessions'" aria-labelledby="sessions-heading" class="space-y-stack-lg"><div class="flex flex-col md:flex-row md:items-end justify-between gap-stack-md border-b border-border pb-stack-md"><div><h2 id="sessions-heading" class="text-h2 font-semibold text-ink">Sessions</h2><p class="text-body-sm text-ink-secondary mt-1">Chronological record of client sessions and recorded clinical time.</p></div><div class="flex items-center gap-inline-lg text-right"><div><span class="text-caption text-ink-muted block">Completed</span><strong class="text-body text-ink">{{ completedSessions.length }}</strong></div><div><span class="text-caption text-ink-muted block">Recorded time</span><strong class="text-body text-ink">{{ totalRecordedTimeLabel }}</strong></div></div></div><p v-if="sessionsLoading" class="text-body-sm text-ink-muted py-stack-lg">Loading sessions…</p><div v-else-if="!sessions.length" class="border-y border-border py-stack-xl text-center"><p class="text-body text-ink-secondary">No sessions have been recorded for this client.</p><button v-if="!client.archived" type="button" class="mt-stack-md px-inline-md py-stack-xs bg-action-link text-on-action rounded-control font-medium hover:bg-action-link-hover" @click="startSession">Start Session</button></div><div v-else class="border-y border-border divide-y divide-border"><article v-for="session in sessions" :key="session.id" class="grid grid-cols-1 md:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)_auto] gap-stack-md md:gap-inline-lg items-center px-inline-sm py-stack-md"><div class="min-w-0"><div class="flex items-center gap-inline-sm flex-wrap"><h3 class="text-body font-semibold text-ink">{{ formatSessionDate(session.startedAt) }}</h3><StatusBadge :status="session.status === 'in_progress' ? 'active' : 'completed'" :label="session.status === 'in_progress' ? 'In progress' : 'Completed'" /></div><p class="text-body-sm text-ink-secondary mt-1">{{ workflowLabel(session) }}</p></div><div><p v-if="session.status === 'in_progress'" class="text-body-sm font-medium text-action-link">Started {{ formatSessionTime(session.startedAt) }} · {{ elapsedTime }}</p><template v-else><p class="text-body-sm font-medium text-ink">{{ sessionTimeRange(session) || formatSessionTime(session.startedAt) }}</p><p class="text-caption text-ink-muted mt-1">{{ sessionDurationLabel(session) || 'Duration unavailable' }}</p></template></div><button type="button" class="min-h-[2.75rem] px-inline-md py-stack-xs border border-border bg-surface-elevated text-body-sm font-medium text-ink rounded-control hover:bg-surface-subtle" @click="openSessionWorkspace(session)">{{ session.status === 'in_progress' ? 'Open Clinical Workspace' : 'Review Clinical Workspace' }}</button></article></div></section>
        <ClientCarePanel v-else-if="activeTab === 'Care'" :client-id="String(route.params.clientId)" v-model:selectedLensId="selectedLensId" @changed="careRefreshKey++" />
        <div v-else-if="activeTab === 'Details'"><ClientDetails :client="client" @updated="client = $event" /></div>
        <ClientTranscriptsPanel v-else-if="activeTab === 'Transcripts'" :client-id="String(route.params.clientId)" />
        <ClientDocumentsPanel v-else-if="activeTab === 'Documents'" :documents="documents" :loading="documentsLoading" :error="documentsError" @create="newDocument" @edit="editDocument" @download="downloadDocument" />
        <div v-else><div v-if="activeTab === 'Timeline'" class="bg-surface-elevated border border-border-muted rounded-panel p-inline-lg max-w-2xl mx-auto"><h3 class="text-h3 font-semibold text-ink mb-stack-lg pt-stack-md">Client Timeline</h3><div v-if="timelineLoading" class="py-stack-xl text-center"><p class="text-body-sm text-ink-subtle">Loading clinical narrative...</p></div><div v-else-if="timelineEvents.length === 0" class="py-stack-xl text-center"><p class="text-body-sm text-ink-subtle">No clinical events recorded for this client.</p></div><div v-else class="space-y-0"><TimelineItem v-for="(event, index) in timelineEvents" :key="event.id" :event-type="event.event_type" :date="formatDate(event.occurred_at)" :description="event.summary" :subject-type="event.subject_type" :subject-id="event.subject_id" :session-id="event.session_id" :is-last="index === timelineEvents.length - 1" /></div></div><EmptyState v-else :title="activeTab" :description="`The ${activeTab} module does not yet have a structured data source for this client.`" icon="🛠️"><template #action><button @click="activeTab = 'Overview'" class="text-action-link font-medium hover:underline">Return to Overview</button></template></EmptyState></div>
      </div></div>
      <ClientDocumentComposer v-if="documentComposerOpen" :client="client" :document="editingDocument" @close="closeDocumentComposer" @saved="documentSaved" @show-documents="showDocuments" />
      <div v-if="showEndSessionConfirmation" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"><div class="bg-surface max-w-md w-full rounded-card shadow-xl p-6 border border-border"><h3 class="text-h3 font-semibold text-ink mb-2">End this client session?</h3><p class="text-body text-ink-muted mb-6">This stops the session timer and completes the clinical record.</p><div class="flex justify-end gap-3"><button @click="showEndSessionConfirmation=false" class="px-4 py-2 bg-surface border border-border text-ink-secondary rounded-control">Cancel</button><button @click="endSession" class="px-4 py-2 bg-state-danger text-white rounded-control">End Session</button></div></div></div>
    </template>
  </div>
</template>
<script setup>
import { computed, ref, onMounted, onBeforeUnmount } from 'vue'; import { useRoute, useRouter } from 'vue-router';
import { getClient, getCurrentTherapistLabel, getTimelineEvents } from '../lib/clients.js'; import { listSessions, createOrResumeSession, completeSessionRecord } from '../lib/sessions.js'; import { listClientAppointments, nextClientAppointment } from '../lib/appointments.js'; import { downloadClientDocument, listClientDocuments } from '../lib/clientDocuments.js';
import { DEFAULT_LENS_ID } from '../lib/clinicalLenses.js';
import ClientWorkspaceHeader from '../components/workspace/ClientWorkspaceHeader.vue'; import ClientWorkspaceTabs from '../components/workspace/ClientWorkspaceTabs.vue'; import ClinicalAttentionPanel from '../components/workspace/ClinicalAttentionPanel.vue'; import ClientDocumentsPanel from '../components/workspace/ClientDocumentsPanel.vue'; import ClientTranscriptsPanel from '../components/workspace/ClientTranscriptsPanel.vue'; import ClientDocumentComposer from '../components/workspace/ClientDocumentComposer.vue'; import ClientCarePanel from '../components/workspace/ClientCarePanel.vue'; import CurrentCareFocus from '../components/workspace/CurrentCareFocus.vue'; import ClientFollowUps from '../components/workspace/ClientFollowUps.vue'; import StatusBadge from '../components/workspace/StatusBadge.vue'; import TimelineItem from '../components/workspace/TimelineItem.vue'; import EmptyState from '../components/workspace/EmptyState.vue'; import ClientDetails from './ClientDetails.vue';
const route=useRoute(), router=useRouter(); const client=ref(null), loading=ref(true), error=ref(''); const tabs=['Overview','Sessions','Transcripts','Details','Care','Measures','Resources','Documents','Timeline'], activeTab=ref('Overview'), timelineEvents=ref([]), timelineLoading=ref(false); const documents=ref([]), documentsLoading=ref(false), documentsError=ref(''), documentComposerOpen=ref(false), editingDocument=ref(null); const sessions=ref([]), sessionsLoading=ref(false), appointments=ref([]), appointmentsLoading=ref(false), therapistLabel=ref('Current therapist'); const sessionBusy=ref(false), sessionError=ref(''), showEndSessionConfirmation=ref(false), now=ref(Date.now()), careRefreshKey=ref(0), selectedLensId=ref(DEFAULT_LENS_ID); let clockTimer;
const recentSessions=computed(()=>sessions.value.slice(0,4)), nextAppointment=computed(()=>nextClientAppointment(appointments.value)), activeSession=computed(()=>sessions.value.find(s=>s.status==='in_progress')||null), completedSessions=computed(()=>sessions.value.filter(s=>s.status==='completed')); const elapsedTime=computed(()=>{if(!activeSession.value?.startedAt)return'00:00:00';const seconds=Math.max(0,Math.floor((now.value-new Date(activeSession.value.startedAt).getTime())/1000));const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return [h,m,s].map(v=>String(v).padStart(2,'0')).join(':')}); const totalRecordedTimeLabel=computed(()=>formatDurationMs(completedSessions.value.reduce((total,session)=>total+(sessionDurationMs(session)||0),0),false));
async function loadClient(){loading.value=true;error.value='';try{client.value=await getClient({clientId:route.params.clientId});const results=await Promise.allSettled([loadTimeline(),refreshDocuments(),loadSessions(),loadAppointments(),loadTherapist()]);for(const result of results)if(result.status==='rejected')console.error('Client workspace context failed to load:',{code:result.reason?.code||'CONTEXT_LOAD_FAILED'})}catch(e){error.value='The client workspace could not be loaded.'}finally{loading.value=false}}
async function loadTimeline(){if(!route.params.clientId)return;timelineLoading.value=true;try{timelineEvents.value=await getTimelineEvents({clientId:route.params.clientId})}finally{timelineLoading.value=false}}
async function refreshDocuments(){if(!route.params.clientId)return;documentsLoading.value=true;documentsError.value='';try{documents.value=await listClientDocuments(route.params.clientId)}catch(e){documentsError.value='Could not load client documents.';throw e}finally{documentsLoading.value=false}}
async function loadSessions(){sessionsLoading.value=true;try{sessions.value=await listSessions({clientId:route.params.clientId});now.value=Date.now()}finally{sessionsLoading.value=false}}
async function loadAppointments(){appointmentsLoading.value=true;try{appointments.value=await listClientAppointments({clientId:route.params.clientId})}finally{appointmentsLoading.value=false}}
async function loadTherapist(){therapistLabel.value=await getCurrentTherapistLabel()}
async function startSession(){if(client.value?.archived||sessionBusy.value)return;sessionBusy.value=true;sessionError.value='';try{const {session}=await createOrResumeSession(client.value.id);sessions.value=[session,...sessions.value.filter(s=>s.id!==session.id)];now.value=Date.now()}catch(e){sessionError.value=e?.code==='CLIENT_ARCHIVED'?'Restore this client before starting a session.':'Couldn’t start the session. Please try again.'}finally{sessionBusy.value=false}}
function openClinicalWorkspace(){if(activeSession.value)openSessionWorkspace(activeSession.value)} function openSessionWorkspace(session){if(!session?.id||!client.value?.id)return;router.push({name:'SessionWorkspace',params:{clientId:client.value.id,sessionId:session.id}})} function confirmEndSession(){if(activeSession.value)showEndSessionConfirmation.value=true}
async function endSession(){if(!activeSession.value||sessionBusy.value)return;sessionBusy.value=true;sessionError.value='';try{const updated=await completeSessionRecord(activeSession.value,activeSession.value.notes);sessions.value=sessions.value.map(s=>s.id===updated.id?updated:s);showEndSessionConfirmation.value=false}catch(e){sessionError.value='Couldn’t end the session. Please try again.'}finally{sessionBusy.value=false}}
function sessionSummary(session){if(session.status==='in_progress')return'Session in progress.';if(session.workflowStatus==='needs_review'||session.workflowStatus==='drafts_awaiting_review')return'Session review is waiting.';return session.completedAt?'Session completed.':'Session recorded.'}
function workflowLabel(session){const labels={awaiting_transcript:'Awaiting transcript',transcript_received:'Transcript received',needs_review:'Needs review',review_choices_saved:'Review choices saved',drafts_awaiting_review:'Drafts awaiting review',approved:'Approved',no_further_action:'No further action'};return session.status==='in_progress'?'Active clinical session':(labels[session.workflowStatus]||'Clinical record')}
function sessionEndTime(session){return session.endedAt||session.completedAt||null}
function sessionDurationMs(session){if(!session?.startedAt)return null;const end=sessionEndTime(session);if(!end)return null;const startMs=new Date(session.startedAt).getTime(),endMs=new Date(end).getTime();if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||endMs<startMs)return null;return endMs-startMs}
function formatDurationMs(duration,minimumOneMinute=true){if(duration===null||!Number.isFinite(duration))return'';const rounded=Math.round(duration/60000),totalMinutes=minimumOneMinute?Math.max(1,rounded):Math.max(0,rounded);const hours=Math.floor(totalMinutes/60),minutes=totalMinutes%60;if(!hours)return`${minutes} min`;if(!minutes)return`${hours} hr`;return`${hours} hr ${minutes} min`}
function sessionDurationLabel(session){return formatDurationMs(sessionDurationMs(session))}
function sessionTimeRange(session){const end=sessionEndTime(session);if(!session?.startedAt||!end)return'';return`${formatSessionTime(session.startedAt)}–${formatSessionTime(end)}`}
function newDocument(){editingDocument.value=null;documentComposerOpen.value=true} function editDocument(document){editingDocument.value=document;documentComposerOpen.value=true} function openDocument(document){if(document.status==='completed'&&document.storagePath)downloadDocument(document);else editDocument(document)} async function downloadDocument(document){try{await downloadClientDocument(document)}catch(e){documentsError.value='Could not download this document.'}} function closeDocumentComposer(){documentComposerOpen.value=false;editingDocument.value=null} async function documentSaved(){await refreshDocuments()} function showDocuments(){closeDocumentComposer();activeTab.value='Documents'} function formatDate(dateString){if(!dateString)return'';return new Date(dateString).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})} function formatSessionDate(dateString){if(!dateString)return'';return new Date(dateString).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} function formatSessionTime(dateString){if(!dateString)return'';return new Date(dateString).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}
onMounted(()=>{clockTimer=setInterval(()=>{now.value=Date.now()},1000);loadClient()}); onBeforeUnmount(()=>clearInterval(clockTimer));
</script>
