<template>
  <div class="p-inline-lg py-stack-lg">
    <div class="flex items-start justify-between gap-inline-lg mb-stack-lg">
      <div class="flex items-start gap-inline-md min-w-0"><span class="icon-surface icon-surface-accent !h-11 !w-11 mt-1" aria-hidden="true"><UsersRound class="workspace-icon-lg" /></span><PageHeader title="Clients" supporting="Manage your clinical directory." /></div>
      <AppButton variant="primary" @click="showAddClient=true"><UserPlus class="workspace-icon" aria-hidden="true" /><span>Add Client</span></AppButton>
    </div>
    <div v-if="loading" class="flex items-center justify-center py-stack-xl"><div class="text-ink-muted flex flex-col items-center gap-2"><span class="w-8 h-8 border-4 border-state-selected border-t-transparent rounded-full animate-spin"></span><p class="type-body">Loading clients…</p></div></div>
    <div v-else-if="error" class="bg-surface-elevated border border-state-danger/20 p-inline-lg py-stack-lg rounded-panel text-center"><h2 class="type-section-title text-state-danger mb-stack-sm">Error loading clients</h2><p class="type-body text-ink-secondary mb-stack-lg">{{ error }}</p><AppButton variant="secondary" @click="loadClients">Try again</AppButton></div>
    <template v-else>
      <div v-if="clients.length===0" class="mb-stack-lg rounded-panel border border-border-muted bg-surface-elevated p-inline-lg py-stack-lg" data-testid="sample-workspace-prompt"><div class="flex items-start gap-inline-md"><span class="icon-surface icon-surface-reflection" aria-hidden="true"><Sparkles class="workspace-icon" /></span><div><h2 class="type-section-title text-ink">Explore with sample clients</h2><p class="mt-stack-sm max-w-2xl type-body text-ink-secondary">Add a fictional workspace to explore Helios before adding your own clients.</p></div></div><div class="mt-stack-md flex flex-wrap items-center gap-inline-md"><AppButton variant="secondary" :disabled="seedingSample" @click="seedSampleWorkspace"><Sparkles v-if="!seedingSample" class="workspace-icon" aria-hidden="true" /><span>{{ seedingSample?'Adding sample workspace…':'Add sample workspace' }}</span></AppButton><span class="type-metadata text-ink-muted">Archive sample clients whenever you no longer need them.</span></div><p v-if="sampleError" class="mt-stack-sm type-body text-state-danger">{{ sampleError }}</p></div>
      <div v-if="sampleActionError" role="alert" class="mb-stack-md rounded-control border border-state-danger/20 bg-state-danger/5 px-inline-md py-stack-sm type-body text-state-danger">{{ sampleActionError }}</div>
      <div class="grid grid-cols-1 md:grid-cols-5 gap-inline-md md:items-center mb-stack-md"><FormControl class="md:col-span-3"><template #default="{controlClass}"><span class="sr-only">Search clients</span><div class="relative"><Search class="pointer-events-none absolute left-3 top-1/2 workspace-icon -translate-y-1/2 text-accent" aria-hidden="true" /><input v-model="searchQuery" type="search" placeholder="Search clients by name or reference…" :class="[controlClass,'pl-10 placeholder:text-ink-muted']" data-testid="client-search" /></div></template></FormControl><div class="md:col-span-2 inline-flex min-h-touch self-start rounded-control border border-border bg-surface p-1" role="group" aria-label="Client status filter"><button v-for="option in statusOptions" :key="option.value" type="button" class="flex-1 min-h-touch px-inline-md rounded-control type-ui transition-colors" :aria-pressed="statusFilter===option.value" :class="statusFilter===option.value?'bg-state-selected text-ink font-semibold':'text-ink-secondary hover:bg-surface-subtle'" @click="statusFilter=option.value">{{ option.label }} <span class="text-ink-muted">{{ option.count }}</span></button></div></div>
      <div class="flex items-center justify-between mb-stack-sm"><p class="type-metadata text-ink-muted">{{ resultLabel }}</p></div>
      <div v-if="filteredClients.length===0" class="bg-surface-elevated border border-border-muted p-inline-lg py-stack-xl rounded-panel text-center"><p class="type-body text-ink-secondary">{{ searchQuery?'No clients match your search.':emptyStatusMessage }}</p></div>
      <div v-else class="bg-surface-elevated border border-border-muted rounded-panel overflow-hidden"><table class="w-full text-left border-collapse"><thead class="bg-surface-subtle border-b border-border-muted"><tr><th class="px-inline-lg py-stack-md type-eyebrow text-ink-secondary">Client</th><th class="px-inline-lg py-stack-md type-eyebrow text-ink-secondary">Next appointment</th><th v-if="statusFilter==='all'" class="px-inline-lg py-stack-md type-eyebrow text-ink-secondary">Status</th><th class="px-inline-lg py-stack-md type-eyebrow text-ink-secondary text-right"><span class="sr-only">Client actions</span></th></tr></thead><tbody class="divide-y divide-border-muted"><tr v-for="client in filteredClients" :key="client.id" tabindex="0" role="link" :aria-label="`Open ${client.display_name}`" class="group cursor-pointer hover:bg-surface-subtle/50 transition-colors" @click="openClient(client.id)" @keydown.enter.prevent="openClient(client.id)" @keydown.space.prevent="openClient(client.id)"><td class="px-inline-lg py-stack-md"><div class="flex items-center gap-3"><span class="icon-surface icon-surface-accent !h-8 !w-8 !rounded-pill opacity-80" aria-hidden="true"><UserRound class="workspace-icon-sm" /></span><div><div class="type-body-medium text-ink">{{ client.display_name }}</div><div v-if="client.reference" class="type-metadata text-ink-muted">{{ client.reference }}</div></div></div></td><td class="px-inline-lg py-stack-md type-ui text-ink-secondary">{{ appointmentLabel(client.id) }}</td><td v-if="statusFilter==='all'" class="px-inline-lg py-stack-md"><StatusIndicator :tone="client.archived?'neutral':'success'">{{ client.archived?'Archived':'Active' }}</StatusIndicator></td><td class="px-inline-lg py-stack-md text-right"><button v-if="isSampleClient(client)" type="button" class="mr-inline-md inline-flex items-center gap-1.5 type-ui text-ink-muted hover:text-ink disabled:opacity-50" :disabled="archivingSampleId===client.id" @click.stop="toggleSampleArchive(client)"><Archive class="workspace-icon" aria-hidden="true" /><span>{{ archivingSampleId===client.id?'Saving…':client.archived?'Restore sample':'Archive sample' }}</span></button><span class="icon-surface !h-8 !w-8 !rounded-pill border-transparent bg-transparent text-accent group-hover:bg-brand-sage-soft" aria-hidden="true"><ChevronRight class="workspace-icon" /></span></td></tr></tbody></table></div>
    </template>
    <AddClientModal v-if="showAddClient" :submitting="addingClient" :error="addError" @close="showAddClient=false" @submit="handleAddClient" />
  </div>
</template>
<script setup>
import { computed,ref,onMounted } from 'vue';import { useRouter } from 'vue-router';import { Archive,ChevronRight,Search,Sparkles,UserPlus,UserRound,UsersRound } from '@lucide/vue';import { listClients,createClient,listUpcomingClientAppointments,setClientArchived } from '../lib/clients.js';import { createSampleWorkspace,isSampleClient } from '../lib/sampleWorkspace.js';import AddClientModal from '../components/sidebar/AddClientModal.vue';import PageHeader from '../components/ui/PageHeader.vue';import AppButton from '../components/ui/AppButton.vue';import FormControl from '../components/ui/FormControl.vue';import StatusIndicator from '../components/ui/StatusIndicator.vue';
const router=useRouter(),clients=ref([]),appointments=ref([]),loading=ref(true),error=ref(''),showAddClient=ref(false),addingClient=ref(false),addError=ref(''),seedingSample=ref(false),sampleError=ref(''),sampleActionError=ref(''),archivingSampleId=ref(''),searchQuery=ref(''),statusFilter=ref('active');
const activeCount=computed(()=>clients.value.filter(c=>!c.archived).length),archivedCount=computed(()=>clients.value.filter(c=>c.archived).length),statusOptions=computed(()=>[{value:'active',label:'Active',count:activeCount.value},{value:'archived',label:'Archived',count:archivedCount.value},{value:'all',label:'All',count:clients.value.length}]);const filteredClients=computed(()=>{const q=searchQuery.value.trim().toLowerCase();return clients.value.filter(c=>statusFilter.value==='all'||(statusFilter.value==='archived'?c.archived:!c.archived)).filter(c=>!q||c.display_name?.toLowerCase().includes(q)||c.reference?.toLowerCase().includes(q))});const resultLabel=computed(()=>`${filteredClients.value.length} ${statusFilter.value==='all'?'client':statusFilter.value+' client'}${filteredClients.value.length===1?'':'s'}`),emptyStatusMessage=computed(()=>statusFilter.value==='archived'?'No archived clients.':statusFilter.value==='all'?'No clients yet.':'You don’t have any active clients yet.');const nextAppointments=computed(()=>{const map=new Map();for(const a of appointments.value){if(a.client_id&&!map.has(a.client_id))map.set(a.client_id,a)}return map});function appointmentLabel(id){const a=nextAppointments.value.get(id);if(!a?.starts_at)return'Not scheduled';return new Date(a.starts_at).toLocaleString('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}function openClient(id){router.push(`/clients/${id}`)}
async function loadClients(){loading.value=true;error.value='';try{[clients.value,appointments.value]=await Promise.all([listClients({includeArchived:true}),listUpcomingClientAppointments()])}catch(e){error.value='The clinical directory could not be loaded.'}finally{loading.value=false}}async function seedSampleWorkspace(){if(seedingSample.value)return;seedingSample.value=true;sampleError.value='';try{await createSampleWorkspace();statusFilter.value='active';await loadClients()}catch(e){sampleError.value=e.message||'The sample workspace could not be added.'}finally{seedingSample.value=false}}async function toggleSampleArchive(client){if(archivingSampleId.value)return;archivingSampleId.value=client.id;sampleActionError.value='';try{const updated=await setClientArchived({clientId:client.id,archived:!client.archived});const i=clients.value.findIndex(c=>c.id===client.id);if(i!==-1)clients.value[i]={...clients.value[i],...updated}}catch(e){sampleActionError.value=e.message||'Could not update the sample client.'}finally{archivingSampleId.value=''}}async function handleAddClient(data){if(addingClient.value)return;addingClient.value=true;addError.value='';try{const c=await createClient(data);clients.value.push(c);clients.value.sort((a,b)=>a.display_name.localeCompare(b.display_name));statusFilter.value='active';showAddClient.value=false}catch(e){addError.value=e.message||'Failed to create client.'}finally{addingClient.value=false}}onMounted(loadClients);
</script>
