<template>
  <PublicPageShell title="Cookie information" eyebrow="Privacy" summary="A plain-language description of browser storage used by Helios.">
    <section><h2 class="type-subsection">Essential browser storage</h2><p class="mt-2 type-body text-ink-secondary">Helios uses browser storage where it is needed for authentication, security and application state. Optional Google and Zoom integrations can also involve browser redirects or storage as part of authentication flows you choose to start.</p></section>
    <section><h2 class="type-subsection">Optional public-site analytics</h2><p class="mt-2 type-body text-ink-secondary">If you choose “Allow analytics”, Helios uses PostHog on a limited set of public pages to understand page visits and key steps such as starting account creation. This analytics tracking does not run until you give permission. Helios does not send form contents, email addresses, client information, session material, transcripts or Clinical Records to PostHog.</p></section>
    <section><h2 class="type-subsection">Clinical workspace</h2><p class="mt-2 type-body text-ink-secondary">PostHog analytics is deliberately excluded from authenticated clinical workspace routes, public client booking and questionnaire routes. Session replay and automatic click or form capture are not used by this Helios analytics implementation.</p></section>
    <section><h2 class="type-subsection">Your choice</h2><p class="mt-2 type-body text-ink-secondary">You can refuse optional analytics and continue using Helios. Your analytics choice is stored in your browser so Helios can remember it. Clearing site storage will cause Helios to ask again on a later public-page visit.</p></section>
    <section><h2 class="type-subsection">Questions</h2><p class="mt-2 type-body text-ink-secondary">Questions about browser storage or privacy can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
