<template>
  <PublicPageShell title="Cookie information" eyebrow="Privacy" summary="A plain-language description of browser storage used by Helios.">
    <section><h2 class="type-subsection">Traffic and performance telemetry</h2><p class="mt-2 type-body text-ink-secondary">Helios is configured to use Vercel Analytics for traffic measurement and Speed Insights for performance measurement on public pages and recognised workspace routes, when enabled in the deployed service. Before telemetry events are sent, Helios removes all query strings and URL fragments and replaces client IDs, session IDs and booking tokens in recognised paths with fixed placeholders. Questionnaire tokens and other identifiers in query strings are removed too. Events for unrecognised paths and custom analytics events are excluded. These filters apply to analytics and performance events, not separate hosting or server logs.</p></section>
    <section><h2 class="type-subsection">Authentication and connected services</h2><p class="mt-2 type-body text-ink-secondary">Helios uses browser storage for authentication and application state. This can include a persisted sign-in session, workspace preferences and working material stored by individual features. Optional Google and Zoom integrations also use authentication redirects. Browser storage is distinct from the sanitised URLs sent through the telemetry filters.</p></section>
    <section><h2 class="type-subsection">Cookies and consent controls</h2><p class="mt-2 type-body text-ink-secondary">Helios currently has no cookie-consent banner or telemetry consent control. The optional product-update checkbox at signup concerns email communications, not telemetry. Vercel describes Web Analytics as operating without cookies; Speed Insights measures browser performance. Cookie-free measurement does not, by itself, establish that consent is unnecessary. This page describes the implementation and does not claim an exemption from consent requirements. See <a class="text-action-link hover:underline" href="https://vercel.com/docs/analytics/privacy-policy">Vercel Web Analytics privacy information</a> and <a class="text-action-link hover:underline" href="https://vercel.com/docs/speed-insights/privacy-policy">Speed Insights privacy information</a> for provider details.</p></section>
    <section><h2 class="type-subsection">Questions</h2><p class="mt-2 type-body text-ink-secondary">Questions about browser storage or privacy can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
