<template>
  <PublicPageShell title="Cookie information" eyebrow="Privacy" summary="A plain-language description of browser storage used by Helios.">
    <section><h2 class="type-subsection">Current public site</h2><p class="mt-2 type-body text-ink-secondary">The current Helios application does not include advertising or analytics tracking in its frontend code. No non-essential cookie or tracking mechanism has been identified in the current implementation, so Helios does not presently show an accept/reject consent banner simply for visiting its public information pages.</p></section>
    <section><h2 class="type-subsection">Authentication and connected services</h2><p class="mt-2 type-body text-ink-secondary">Signing in and using features the user requests can involve browser storage that is needed for authentication, security and application state. Optional Google and Zoom integrations can also involve browser redirects or storage as part of their authentication flows.</p></section>
    <section><h2 class="type-subsection">Consent if the technology changes</h2><p class="mt-2 type-body text-ink-secondary">If Helios introduces analytics, advertising or another non-essential storage or tracking technology, it must be assessed before activation. Where consent is required, the technology should not run before the user has made that choice, and refusing it should be straightforward.</p></section>
    <section><h2 class="type-subsection">Questions</h2><p class="mt-2 type-body text-ink-secondary">Questions about browser storage or privacy can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
