<template>
  <main class="min-h-screen bg-surface-canvas text-ink">
    <header class="border-b border-border-muted bg-surface-canvas">
      <div class="mx-auto flex w-full max-w-[1540px] items-center justify-between px-5 py-4 sm:px-8 xl:px-12">
        <router-link to="/" class="flex items-center gap-3" aria-label="Helios home">
          <svg class="h-9 w-9 text-brand-amber" viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="M9 31h30" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M15 31a9 9 0 0 1 18 0" stroke="currentColor" stroke-width="2"/><path d="M24 8v7M9.5 14.5l5 5M38.5 14.5l-5 5M5 26h7M36 26h7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
          <span class="text-xl font-semibold tracking-[-0.02em]">Helios</span>
        </router-link>
        <nav class="hidden items-center gap-7 text-sm font-medium text-ink-secondary lg:flex" aria-label="Landing page sections">
          <a href="#platform" class="hover:text-ink">Platform</a><a href="#integrations" class="hover:text-ink">Integrations</a><a href="#cpd" class="hover:text-ink">CPD</a><a href="#trust" class="hover:text-ink">Trust &amp; control</a>
        </nav>
        <nav class="flex items-center gap-2" aria-label="Account access">
          <router-link to="/sign-in" class="rounded-control px-4 py-2 text-sm font-semibold text-ink-secondary hover:bg-surface-muted hover:text-ink">Sign in</router-link>
          <router-link to="/get-started" class="rounded-control bg-action-primary px-4 py-2 text-sm font-semibold text-on-action hover:bg-action-primary-hover">Get started</router-link>
        </nav>
      </div>
    </header>

    <section class="overflow-hidden border-b border-border-muted">
      <div class="mx-auto w-full max-w-[1540px] px-5 pt-8 sm:px-8 lg:pt-10 xl:px-12">
        <div class="grid items-end gap-7 lg:grid-cols-[minmax(0,0.72fr)_minmax(420px,0.48fr)] xl:grid-cols-[minmax(0,0.8fr)_minmax(460px,0.42fr)]">
          <div class="max-w-[820px] pb-1">
            <p class="text-xs font-semibold uppercase tracking-[0.16em] text-action-link">AI-supported clinical workspace</p>
            <h1 class="mt-4 max-w-[820px] text-[3rem] font-semibold leading-[0.98] tracking-[-0.04em] sm:text-[3.5rem] lg:text-[3.8rem] xl:text-[4.1rem]">The clinical workspace for modern psychotherapy.</h1>
          </div>
          <div class="pb-2 lg:pb-1">
            <p class="max-w-[520px] text-base leading-7 text-ink-secondary">Keep schedule, client context, session work, records and professional development connected. Helios reduces cognitive load with contextual AI assistance that stays under therapist control.</p>
            <div class="mt-5 flex flex-wrap gap-3"><router-link to="/get-started" class="rounded-control bg-action-primary px-5 py-3 text-sm font-semibold text-on-action hover:bg-action-primary-hover">Get started</router-link><a href="#platform" class="rounded-control border border-border px-5 py-3 text-sm font-semibold text-ink-secondary hover:bg-surface-muted hover:text-ink">See how Helio works</a></div>
          </div>
        </div>

        <div class="mt-7 lg:-mr-12 xl:mt-8" aria-label="Representative Helios therapist workspace">
          <div class="overflow-hidden rounded-tl-panel border border-b-0 border-border bg-surface-raised">
            <div class="flex h-10 items-center justify-between border-b border-border-muted bg-surface-muted px-4 text-[11px] text-ink-muted">
              <div class="flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-brand-amber"></span><span class="font-semibold text-ink-secondary">Helios workspace</span></div><span>Sunday · 23 August</span>
            </div>
            <div class="grid min-h-[430px] grid-cols-[148px_minmax(0,1fr)] lg:grid-cols-[170px_minmax(0,1fr)]">
              <aside class="border-r border-border-muted bg-surface-sidebar p-3 lg:p-4">
                <div class="mb-4 flex items-center gap-2 border-b border-border-muted pb-4"><span class="flex h-8 w-8 items-center justify-center rounded-control bg-brand-amber-soft text-brand-amber">☼</span><div><p class="text-xs font-semibold">Practice</p><p class="text-[10px] text-ink-muted">Workspace</p></div></div>
                <nav class="space-y-0.5 text-xs" aria-label="Representative workspace navigation">
                  <div class="rounded-control bg-state-selected px-3 py-2 font-semibold">Today</div><div class="px-3 py-2 text-ink-secondary">Calendar</div><div class="px-3 py-2 text-ink-secondary">Clients</div><div class="px-3 py-2 text-ink-secondary">Sessions</div><div class="px-3 py-2 text-ink-secondary">Transcripts</div><div class="px-3 py-2 text-ink-secondary">Documents</div><div class="px-3 py-2 text-ink-secondary">CPD</div>
                </nav>
                <div class="mt-5 border-t border-border-muted pt-4 text-[10px] leading-4 text-ink-muted"><p class="font-semibold uppercase tracking-[0.12em]">Connected</p><p class="mt-2">Google Calendar</p><p>Zoom</p></div>
              </aside>

              <div class="min-w-0 bg-surface-raised">
                <div class="flex items-center justify-between border-b border-border-muted px-5 py-3 lg:px-6"><div><p class="text-[10px] font-semibold uppercase tracking-[0.14em] text-ink-muted">Today</p><p class="mt-0.5 text-lg font-semibold">Good morning. Here’s what needs your attention.</p></div><span class="hidden rounded-control border border-border-muted bg-surface px-3 py-1.5 text-[11px] text-ink-secondary sm:inline">Practice overview</span></div>
                <div class="grid gap-4 p-4 lg:grid-cols-[minmax(0,1.45fr)_minmax(250px,.72fr)] lg:p-5">
                  <section class="min-w-0">
                    <div class="flex items-center justify-between"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-ink-muted">Schedule &amp; continuity</p><span class="text-[11px] text-ink-muted">3 appointments</span></div>
                    <div class="mt-2 overflow-hidden rounded-control border border-border-muted bg-surface">
                      <div class="grid grid-cols-[58px_minmax(0,1fr)_auto] items-center gap-3 border-b border-border-muted px-3 py-2.5"><p class="text-xs font-semibold">09:00</p><div><p class="text-xs font-semibold">Client A</p><p class="text-[11px] text-ink-muted">Context reviewed · session complete</p></div><span class="text-[10px] font-semibold text-success">Follow-through</span></div>
                      <div class="grid grid-cols-[58px_minmax(0,1fr)_auto] items-center gap-3 border-b border-border-muted bg-state-selected px-3 py-2.5"><p class="text-xs font-semibold">11:30</p><div><p class="text-xs font-semibold">Client B</p><p class="text-[11px] text-ink-muted">Previous session and current focus ready</p></div><span class="rounded-control bg-action-primary px-2 py-1 text-[10px] font-semibold text-on-action">Prepare</span></div>
                      <div class="grid grid-cols-[58px_minmax(0,1fr)_auto] items-center gap-3 px-3 py-2.5"><p class="text-xs font-semibold">15:00</p><div><p class="text-xs font-semibold">Client C</p><p class="text-[11px] text-ink-muted">Zoom appointment</p></div><span class="text-[10px] text-ink-muted">Later</span></div>
                    </div>

                    <div class="mt-4 grid gap-3 sm:grid-cols-2">
                      <article class="rounded-control border border-border-muted bg-surface p-3"><div class="flex items-center justify-between"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-muted">Client B · continuity</p><span class="text-[10px] text-action-link">Open client</span></div><p class="mt-2 text-sm font-semibold">Working context in one place</p><div class="mt-3 grid grid-cols-3 divide-x divide-border-muted text-[10px]"><div class="pr-2"><p class="font-semibold">6</p><p class="text-ink-muted">Sessions</p></div><div class="px-2"><p class="font-semibold">2</p><p class="text-ink-muted">Documents</p></div><div class="pl-2"><p class="font-semibold">1</p><p class="text-ink-muted">Follow-up</p></div></div></article>
                      <article class="rounded-control border border-border-muted bg-surface p-3"><div class="flex items-center justify-between"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-muted">Recent timeline</p><span class="text-[10px] text-ink-muted">Client B</span></div><div class="mt-2 space-y-2 text-[11px]"><p><span class="font-semibold">Session working material</span><span class="text-ink-muted"> · editable draft</span></p><p><span class="font-semibold">Clinical Record</span><span class="text-ink-muted"> · previous record approved</span></p><p><span class="font-semibold">Follow-through</span><span class="text-ink-muted"> · review next session</span></p></div></article>
                    </div>
                  </section>

                  <section class="space-y-3">
                    <article class="rounded-control border border-border-muted bg-surface p-3"><div class="flex items-center justify-between"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-muted">Work requiring attention</p><span class="rounded-control bg-state-warning-surface px-2 py-1 text-[10px] font-semibold text-warning">2 items</span></div><p class="mt-2 text-sm font-semibold">Session draft to review</p><p class="mt-1 text-[11px] leading-4 text-ink-muted">Editable working material remains separate from the Clinical Record.</p></article>
                    <article class="rounded-control border border-accent/30 bg-state-selected p-3"><div class="flex items-center justify-between"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-action-link">AI assistance</p><span class="text-[10px] text-ink-muted">Therapist-triggered</span></div><p class="mt-2 text-sm font-semibold">Context available when useful</p><p class="mt-1 text-[11px] leading-4 text-ink-secondary">Review suggestions against the session working material. Nothing becomes a record without your decision.</p><button type="button" class="mt-2 rounded-control border border-border bg-surface px-2.5 py-1.5 text-[10px] font-semibold text-ink-secondary">Review assistance</button></article>
                    <article class="rounded-control border border-border-muted bg-surface p-3"><p class="text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-muted">Clinical Record</p><div class="mt-2 flex items-center justify-between gap-2"><div><p class="text-sm font-semibold">Approval is deliberate</p><p class="text-[11px] text-ink-muted">Draft not approved</p></div><span class="rounded-control border border-border-muted px-2 py-1 text-[10px] font-semibold">Review</span></div></article>
                  </section>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="platform" class="scroll-mt-6 border-b border-border-muted bg-surface-raised"><div class="mx-auto grid w-full max-w-[1540px] gap-0 px-5 sm:grid-cols-2 sm:px-8 lg:grid-cols-4 xl:px-12"><div class="border-b border-border-muted py-5 sm:border-r lg:border-b-0 lg:pr-6"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">One working context</p><p class="mt-2 text-sm text-ink-secondary">Today, clients, sessions, transcripts and documents stay connected instead of becoming separate admin silos.</p></div><div class="border-b border-border-muted py-5 sm:pl-6 lg:border-b-0 lg:border-r lg:pr-6"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">Clinical continuity</p><p class="mt-2 text-sm text-ink-secondary">See the relevant thread before, during and after a session without relying on memory alone.</p></div><div class="border-b border-border-muted py-5 sm:border-b-0 sm:border-r lg:pl-6 lg:pr-6"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">Deliberate records</p><p class="mt-2 text-sm text-ink-secondary">Working drafts remain editable. Clinical Records are approved deliberately and kept distinct.</p></div><div class="py-5 sm:pl-6"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">Therapist-controlled AI</p><p class="mt-2 text-sm text-ink-secondary">Contextual assistance supports the work; therapist judgement remains authoritative.</p></div></div></section>

    <section class="mx-auto w-full max-w-[1200px] px-5 py-16 sm:px-8 lg:py-20">
      <div class="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-16"><div><p class="type-eyebrow text-action-link">The work around therapy</p><h2 class="mt-3 text-3xl font-semibold tracking-[-0.03em] sm:text-4xl">Continuity across the whole professional day.</h2><p class="mt-4 type-body-long text-ink-secondary">Helios is built around the sequence of real therapist work, not around a single note or AI interaction.</p></div><div class="grid gap-px overflow-hidden rounded-panel border border-border bg-border sm:grid-cols-2"><article class="bg-surface-raised p-6"><p class="type-eyebrow text-ink-muted">01 · Prepare</p><h3 class="mt-2 type-subsection">Today and client context</h3><p class="mt-3 type-body text-ink-secondary">Bring appointments, recent work and follow-through into view before the next session.</p></article><article class="bg-surface-raised p-6"><p class="type-eyebrow text-ink-muted">02 · Work</p><h3 class="mt-2 type-subsection">Sessions and transcripts</h3><p class="mt-3 type-body text-ink-secondary">Keep editable working material close to the session, with transcript support when it is useful.</p></article><article class="bg-surface-raised p-6"><p class="type-eyebrow text-ink-muted">03 · Decide</p><h3 class="mt-2 type-subsection">Clinical Records</h3><p class="mt-3 type-body text-ink-secondary">Review what belongs in the formal record and approve it deliberately rather than treating drafts as records.</p></article><article class="bg-surface-raised p-6"><p class="type-eyebrow text-ink-muted">04 · Continue</p><h3 class="mt-2 type-subsection">Follow-through and CPD</h3><p class="mt-3 type-body text-ink-secondary">Carry professional threads forward, including learning and development beyond individual client work.</p></article></div></div>
    </section>

    <section id="integrations" class="scroll-mt-6 border-y border-border-muted bg-surface-elevated"><div class="mx-auto grid w-full max-w-[1200px] gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="type-eyebrow text-action-link">Connected practice</p><h2 class="mt-3 text-3xl font-semibold tracking-[-0.03em]">Less switching between the systems around your work.</h2><p class="mt-4 type-body-long text-ink-secondary">Calendar and video workflows can feed back into the same professional context rather than living as disconnected appointments and files.</p></div><div class="grid gap-4 sm:grid-cols-2"><article class="surface-card p-6"><p class="type-eyebrow text-ink-muted">Google Calendar</p><h3 class="mt-2 type-subsection">Schedule in context</h3><p class="mt-3 type-body text-ink-secondary">Bring appointments into the working day so preparation and follow-through stay attached to the right client context.</p></article><article class="surface-card p-6"><p class="type-eyebrow text-ink-muted">Zoom</p><h3 class="mt-2 type-subsection">Video and transcript workflows</h3><p class="mt-3 type-body text-ink-secondary">Connect video consultations and supported transcript workflows back to the relevant session workspace.</p></article></div></div></section>

    <section id="cpd" class="mx-auto w-full max-w-[1200px] scroll-mt-6 px-5 py-16 sm:px-8"><div class="grid gap-8 lg:grid-cols-2 lg:items-center"><div><p class="type-eyebrow text-action-link">CPD &amp; professional development</p><h2 class="mt-3 text-3xl font-semibold tracking-[-0.03em]">The therapist’s development belongs in the workspace too.</h2><p class="mt-4 type-body-long text-ink-secondary">Helios extends beyond client administration with a dedicated professional-development area for supervision, reflection, growth and insights.</p></div><div class="grid grid-cols-2 gap-px overflow-hidden rounded-panel border border-border bg-border"><div class="bg-surface-raised p-5"><p class="font-semibold">Supervision</p><p class="mt-1 text-sm text-ink-muted">Keep development work accessible.</p></div><div class="bg-surface-raised p-5"><p class="font-semibold">Reflections</p><p class="mt-1 text-sm text-ink-muted">Separate from client records.</p></div><div class="bg-surface-raised p-5"><p class="font-semibold">Growth</p><p class="mt-1 text-sm text-ink-muted">Carry learning forward.</p></div><div class="bg-surface-raised p-5"><p class="font-semibold">Insights</p><p class="mt-1 text-sm text-ink-muted">See professional threads over time.</p></div></div></div></section>

    <section id="trust" class="scroll-mt-6 border-y border-border-muted bg-surface-raised"><div class="mx-auto grid w-full max-w-[1200px] gap-8 px-5 py-14 sm:px-8 lg:grid-cols-3"><div><p class="type-eyebrow text-action-link">Trust &amp; control</p><h2 class="mt-3 text-3xl font-semibold tracking-[-0.03em]">Software that respects clinical judgement.</h2></div><article><p class="font-semibold">Drafts are drafts</p><p class="mt-2 type-body text-ink-secondary">Session working material stays editable and is not presented as an approved Clinical Record.</p></article><article><p class="font-semibold">AI stays subordinate</p><p class="mt-2 type-body text-ink-secondary">Assistance is contextual and reviewable. The therapist decides what is useful and what belongs in the professional record.</p></article></div></section>

    <section class="mx-auto flex w-full max-w-[1200px] flex-col gap-6 px-5 py-14 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><p class="type-eyebrow text-action-link">Helios</p><h2 class="mt-2 text-3xl font-semibold tracking-[-0.03em]">A calmer, connected place for the work around therapy.</h2></div><router-link to="/get-started" class="w-fit rounded-control bg-action-primary px-5 py-3 text-sm font-semibold text-on-action hover:bg-action-primary-hover">Get started</router-link></section>

    <footer class="border-t border-border-muted"><div class="mx-auto flex w-full max-w-[1200px] flex-col gap-4 px-5 py-7 text-sm text-ink-muted sm:px-8 md:flex-row md:items-center md:justify-between"><router-link to="/" class="font-semibold text-ink">Helios</router-link><nav class="flex flex-wrap gap-x-5 gap-y-2"><router-link to="/privacy" class="hover:text-ink">Privacy</router-link><router-link to="/terms" class="hover:text-ink">Terms</router-link><router-link to="/ai-data" class="hover:text-ink">AI &amp; data</router-link><router-link to="/support" class="hover:text-ink">Support</router-link></nav></div></footer>
  </main>
</template>
