<template>
  <PublicPageShell title="Privacy Notice" eyebrow="Privacy" summary="How Helios handles personal information during current testing and beta use.">
    <section><h2 class="type-subsection">Contact</h2><p class="mt-2 type-body text-ink-secondary">Questions about privacy or data handling can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>. This notice describes the service as it is currently provided to individual therapist testers and will be updated when the service or its operating arrangements materially change.</p></section>
    <section><h2 class="type-subsection">Current service scope</h2><p class="mt-2 type-body text-ink-secondary">Helios is currently designed for individual therapists using a single account for their own professional practice. It does not currently provide organisational, clinic-administrator or shared multi-practitioner accounts. Privacy arrangements for clinic or organisational use will be assessed separately if those capabilities are introduced.</p></section>
    <section><h2 class="type-subsection">Information Helios handles</h2><p class="mt-2 type-body text-ink-secondary">Depending on how the therapist uses the service, Helios may handle therapist account and practice information, client details, appointments, session material, editable working notes, approved Clinical Records, documents, private professional reflection and CPD material.</p></section>
    <section><h2 class="type-subsection">How information is used</h2><p class="mt-2 type-body text-ink-secondary">Helios uses information to provide and secure the therapist workspace, store and retrieve the therapist's practice material, provide features the therapist chooses to invoke, operate connected services the therapist enables, send service-related account email, troubleshoot the service and respond to support or privacy questions. Helios does not use the application as an advertising platform.</p></section>
    <section><h2 class="type-subsection">Core service providers</h2><p class="mt-2 type-body text-ink-secondary">Helios currently uses Supabase for application data, authentication and storage, Vercel for application hosting and server-side functions, and Resend for account email. Information needed to provide those services may therefore be processed through those providers.</p></section>
    <section><h2 class="type-subsection">Optional connected services</h2><p class="mt-2 type-body text-ink-secondary">Therapists can choose to connect Google and Zoom. The Google integration requests access needed for the therapist's account email and Calendar features, including reading calendars and creating or updating events. Zoom is used for connected meeting and transcript workflows where the therapist enables those features. These integrations are optional and are not required for Helios' core Clinical Record model.</p></section>
    <section><h2 class="type-subsection">AI and dictation</h2><p class="mt-2 type-body text-ink-secondary">When a therapist deliberately invokes supported AI or dictation features, relevant working material may be sent from Helios' server-side functions to OpenAI for processing. AI-generated or transcript-derived output remains working material for therapist review and does not become an approved Clinical Record automatically. See <router-link class="text-action-link hover:underline" to="/ai-data">AI &amp; data</router-link> for more detail.</p></section>
    <section><h2 class="type-subsection">Clinical information</h2><p class="mt-2 type-body text-ink-secondary">Helios is designed to keep therapist-owned information behind authenticated access and database row-level security. Approved Clinical Records are distinct from editable drafts: approval locks the record, and later corrections are handled as append-only amendments rather than silent edits. Private professional reflection remains separate from the Clinical Record.</p></section>
    <section><h2 class="type-subsection">Retention and account questions</h2><p class="mt-2 type-body text-ink-secondary">Helios retains information as needed to operate the current service and its clinical record model. Because approved Clinical Records have deliberate immutability and amendment behaviour, deletion and retention questions may depend on the type of information involved. Testers who want to discuss access, correction, deletion or their account should contact <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a> so the request can be assessed appropriately.</p></section>
    <section><h2 class="type-subsection">Privacy questions and concerns</h2><p class="mt-2 type-body text-ink-secondary">Contact <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a> with questions or concerns about personal information handled through Helios. This notice will be expanded if the service's legal, commercial or organisational model changes.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
