<template>
  <PublicPageShell title="Privacy Notice" eyebrow="Privacy" summary="How Helios handles personal information in the current service.">
    <section><h2 class="type-subsection">Service operator</h2><p class="mt-2 type-body text-ink-secondary">Helios is operated by Robert Ormston, trading as Chrysalis Therapy Services.</p></section>
    <section><h2 class="type-subsection">Traffic and performance telemetry</h2><p class="mt-2 type-body text-ink-secondary">Helios is configured to use Vercel Analytics for traffic measurement and Speed Insights for performance measurement on public pages and recognised workspace routes. These services can receive page-view and performance information, including sanitised URLs and browser or device information, when enabled in the deployed service. Before these telemetry events are sent, Helios removes all query strings and URL fragments and replaces client IDs, session IDs and booking tokens in recognised paths with fixed placeholders. This also removes questionnaire tokens and other identifiers carried in query strings. Events for unrecognised paths and custom analytics events are excluded. These filters apply to analytics and performance events, not separate hosting or server logs.</p></section>
    <section><h2 class="type-subsection">Optional product updates</h2><p class="mt-2 type-body text-ink-secondary">Signup includes an optional choice to receive Helios product updates, practical tips and news. The signup email workflow sends name, email address and subscription preference to Resend for contact management, including an unsubscribed preference when marketing is not selected, and uses Resend to send the welcome email. When marketing is selected and Loops is configured, the workflow also sends email address, first name, account identifier, signup date and subscription status to Loops for product-update communications. Loops processing depends on service configuration. Questions about these communications or your preference can be sent to hello@helio.works.</p></section>
    <section><h2 class="type-subsection">Contact</h2><p class="mt-2 type-body text-ink-secondary">Questions about privacy or data handling can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>. This notice describes the service as it is currently provided to individual therapist testers and will be updated when the service or its operating arrangements materially change.</p></section>
    <section><h2 class="type-subsection">Current service scope</h2><p class="mt-2 type-body text-ink-secondary">Helios is currently designed for individual therapists using a single account for their own professional practice. It does not currently provide organisational, clinic-administrator or shared multi-practitioner accounts. Privacy arrangements for clinic or organisational use will be assessed separately if those capabilities are introduced.</p></section>
    <section><h2 class="type-subsection">Information Helios handles</h2><p class="mt-2 type-body text-ink-secondary">Depending on how the therapist uses the service, Helios may handle therapist account and practice information, client details, appointments, session material, editable working notes, approved Clinical Records, documents, private professional reflection and CPD material.</p></section>
    <section><h2 class="type-subsection">How information is used</h2><p class="mt-2 type-body text-ink-secondary">Helios uses information to provide and secure the therapist workspace, store and retrieve the therapist's practice material, provide features the therapist chooses to invoke, operate connected services the therapist enables, send service-related account email, troubleshoot the service and respond to support or privacy questions. Helios does not use the application as an advertising platform.</p></section>
    <section><h2 class="type-subsection">Core service providers</h2><p class="mt-2 type-body text-ink-secondary">Helios currently uses Supabase for application data, authentication and storage, Vercel for application hosting and server-side functions, and Resend for account email. Information needed to provide those services may therefore be processed through those providers.</p></section>
    <section><h2 class="type-subsection">Google Calendar data</h2><p class="mt-2 type-body text-ink-secondary">Google Calendar is an optional integration enabled by the therapist. When connected, Helios accesses the therapist's Google account email and Google Calendar information needed to provide calendar functionality. This includes calendar metadata and event information such as event identifiers, titles, dates and times, status and other event details returned by the Google Calendar API. Helios uses read access to display Google Calendar events in the therapist's Helios calendar. Where the therapist uses supported appointment workflows, Helios uses Calendar event access to create, update or remove the corresponding event in the therapist's Google Calendar. Helios requests these permissions only to provide the connected calendar functionality chosen by the therapist.</p></section>
    <section><h2 class="type-subsection">Protecting Google and other sensitive data</h2><p class="mt-2 type-body text-ink-secondary">Helios protects access to therapist data through authenticated accounts and database row-level access controls. Google OAuth access and refresh tokens stored by Helios are encrypted using authenticated AES-256-GCM encryption, and Google API requests are made from server-side Helios functions rather than exposing integration credentials to browser code. Data is transmitted to Google and Helios service providers over encrypted HTTPS connections. Access is limited to the authenticated therapist and the service components required to provide the requested functionality. A therapist can disconnect Google Calendar from Helios to stop ongoing connected-calendar access.</p></section>
    <section><h2 class="type-subsection">Google API Limited Use</h2><p class="mt-2 type-body text-ink-secondary">Helios' use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. Raw, aggregated or derived Google Workspace API user data is not used, transferred or sold to create, train or improve generalized or foundational artificial intelligence or machine-learning models. Google Workspace API data is used only to provide or improve the user-facing functionality requested by the therapist, as permitted by the Google User Data Policy.</p></section>
    <section><h2 class="type-subsection">Optional connected services</h2><p class="mt-2 type-body text-ink-secondary">Therapists can choose to connect Google and Zoom. Zoom is used for connected meeting and transcript workflows where the therapist enables those features. These integrations are optional and are not required for Helios' core Clinical Record model.</p></section>
    <section><h2 class="type-subsection">AI and dictation</h2><p class="mt-2 type-body text-ink-secondary">When a therapist deliberately invokes supported AI or dictation features, relevant working material may be sent from Helios' server-side functions to OpenAI for processing. Google Workspace API user data is not used to train or improve generalized or foundational AI or ML models. AI-generated or transcript-derived output remains working material for therapist review and does not become an approved Clinical Record automatically. See <router-link class="text-action-link hover:underline" to="/ai-data">AI &amp; data</router-link> for more detail.</p></section>
    <section><h2 class="type-subsection">Clinical information</h2><p class="mt-2 type-body text-ink-secondary">Helios is designed to keep therapist-owned information behind authenticated access and database row-level security. Approved Clinical Records are distinct from editable drafts: approval locks the record, and later corrections are handled as append-only amendments rather than silent edits. Private professional reflection remains separate from the Clinical Record.</p></section>
    <section><h2 class="type-subsection">Retention and account questions</h2><p class="mt-2 type-body text-ink-secondary">Helios retains information as needed to operate the current service and its clinical record model. Because approved Clinical Records have deliberate immutability and amendment behaviour, deletion and retention questions may depend on the type of information involved. Testers who want to discuss access, correction, deletion or their account should contact <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a> so the request can be assessed appropriately.</p></section>
    <section><h2 class="type-subsection">Privacy questions and concerns</h2><p class="mt-2 type-body text-ink-secondary">Contact <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a> with questions or concerns about personal information handled through Helios. This notice will be expanded if the service's legal, commercial or organisational model changes.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
