<template>
  <div class="flex flex-col h-full bg-surface-canvas">
    <div v-if="loading" class="flex-1 flex items-center justify-center"><div class="text-ink-muted flex flex-col items-center gap-2"><span class="w-8 h-8 border-4 border-state-selected border-t-transparent rounded-full animate-spin"></span><p>Loading clinical workspace…</p></div></div>
    <div v-else-if="error" class="flex-1 flex items-center justify-center p-inline-lg"><div class="max-w-md w-full bg-surface p-inline-lg py-stack-lg rounded-card shadow-sm border border-state-danger/20 text-center"><h2 class="text-h2 font-semibold text-state-danger mb-2">Workspace Error</h2><p class="text-ink-secondary mb-6">{{ error }}</p><button @click="loadSession" class="button-primary">Try Again</button></div></div>
    <template v-else-if="session">
      <SessionWorkspaceHeader :session="workspaceSession" :joiningMeeting="joiningMeeting" :meetingError="meetingError" @join-meeting="joinMeeting" />
      <WorkflowIndicator :activeStage="activeTab" @select-stage="activeTab = $event" />
      <div class="flex-1 overflow-auto p-inline-lg py-stack-lg"><div class="max-w-6xl mx-auto">
        <section v-if="activeTab === 'Clinical Record' && session.status === 'completed'" data-testid="session-completion-handoff" class="mb-6 rounded-panel border border-state-success/20 bg-state-success-surface p-5">
          <p class="text-caption font-semibold uppercase tracking-wider text-state-success">Session complete</p>
          <h2 class="mt-1 text-h3 font-semibold text-ink">Clinical record approved and locked.</h2>
          <p class="mt-2 text-body-sm text-ink-secondary">The approved record remains available below. Return to the client workspace, or schedule the next appointment when you are ready.</p>
          <div class="mt-4 flex flex-wrap gap-2">
            <RouterLink :to="`/clients/${session.clientId}`" class="px-inline-md py-stack-xs bg-surface-elevated border border-border text-body-sm font-medium text-ink rounded-control hover:bg-surface-subtle">Return to client</RouterLink>
            <RouterLink :to="{ name: 'ScheduleAppointment', query: { clientId: session.clientId } }" class="px-inline-md py-stack-xs bg-action-link text-on-action text-body-sm font-medium rounded-control hover:bg-action-link-hover">Schedule next appointment</RouterLink>
          </div>
        </section>
        <TranscriptTab v-if="activeTab === 'Session Capture'" :transcript="transcript" :loading="transcriptLoading" :error="transcriptError" :activeTab="activeTab" @retry="loadTranscript" />
        <TherapistNotesTab v-else-if="activeTab === 'Notes'" :clientId="session.clientId" :sessionId="session.id" :initialDraft="aiClinicalNoteDraft" @draft-consumed="aiClinicalNoteDraft = null" />
        <ReflectionTab v-else-if="activeTab === 'Reflection'" :clientId="session.clientId" :sessionId="session.id" />
        <CompletedClinicalRecord v-else-if="activeTab === 'Clinical Record' && session.status === 'completed'" :key="clinicalRecordKey" :session="session" :therapistName="therapistName" />
        <ClinicalSummaryTab v-else-if="activeTab === 'Clinical Record'" :key="clinicalRecordKey" :session="session" :therapistName="therapistName" @update:session="handleSessionUpdate" />
        <SupervisionSummaryTab v-else-if="activeTab === 'CPD'" :clientId="session.clientId" :sessionId="session.id" @open-reflection="activeTab = 'Reflection'" />
      </div></div>
    </template>
  </div>
</template>
<script setup>
import {ref,onMounted,computed} from 'vue'; import {useRoute,useRouter,RouterLink} from 'vue-router'; import {supabase} from '../lib/supabase.js'; import {getSession} from '../lib/sessions.js'; import {getClient} from '../lib/clients.js'; import {authenticatedFetch} from '../lib/api.js'; import SessionWorkspaceHeader from '../components/workspace/SessionWorkspaceHeader.vue'; import WorkflowIndicator from '../components/workspace/WorkflowIndicator.vue'; import TranscriptTab from '../components/workspace/TranscriptTab.vue'; import TherapistNotesTab from '../components/workspace/TherapistNotesTab.vue'; import ReflectionTab from '../components/workspace/ReflectionTab.vue'; import ClinicalSummaryTab from '../components/workspace/ClinicalSummaryTab.vue'; import CompletedClinicalRecord from '../components/workspace/CompletedClinicalRecord.vue'; import SupervisionSummaryTab from '../components/workspace/SupervisionSummaryTab.vue';
const route=useRoute(); const session=ref(null),client=ref(null),loading=ref(true),error=ref(''),transcript=ref(null),transcriptLoading=ref(false),transcriptError=ref(''),activeTab=ref('Session Capture'),joiningMeeting=ref(false),meetingError=ref(''),clinicalRecordKey=ref(0),aiClinicalNoteDraft=ref(null),therapistName=ref('');
function handleSessionUpdate(updatedSession){const becameCompleted=session.value?.status!=='completed'&&updatedSession?.status==='completed';session.value=updatedSession;if(becameCompleted)clinicalRecordKey.value+=1;}
async function joinMeeting(){if(!session.value?.id||!session.value?.clientId||joiningMeeting.value)return;joiningMeeting.value=true;meetingError.value='';try{const response=await authenticatedFetch('/api/zoom/start-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:session.value.clientId,sessionRef:session.value.id})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to open Zoom for this session.');if(!data.startUrl)throw new Error('Zoom did not return a meeting link.');window.open(data.startUrl,'_blank','noopener,noreferrer')}catch(err){meetingError.value=err?.message||'Unable to open Zoom for this session.'}finally{joiningMeeting.value=false}}
async function loadTherapistProfile(){if(!supabase)return;try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:profile}=await supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle();const metadataName=typeof user.user_metadata?.full_name==='string'?user.user_metadata.full_name.trim():'';therapistName.value=profile?.full_name?.trim()||metadataName||''}catch(e){console.warn('[SessionWorkspace] Could not load therapist identity',e)}} async function loadSession(){loading.value=true;error.value='';aiClinicalNoteDraft.value=null;try{const {clientId,sessionId}=route.params;const [sessionData,clientData]=await Promise.all([getSession({clientId,sessionId}),getClient({clientId}),loadTherapistProfile()]);session.value=sessionData;client.value=clientData;loadTranscript()}catch(e){error.value='The clinical workspace could not be loaded.'}finally{loading.value=false}}
async function loadTranscript(){if(!session.value?.id||!session.value?.clientId)return;transcriptLoading.value=true;transcriptError.value='';transcript.value=null;try{const params=new URLSearchParams({sessionRef:String(session.value.id),clientId:String(session.value.clientId)});const response=await authenticatedFetch(`/api/zoom/transcripts?${params.toString()}`);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to load the linked transcript.');transcript.value=data.transcripts?.[0]||null}catch(err){transcriptError.value=err?.message||'Unable to load the linked transcript.'}finally{transcriptLoading.value=false}}
const workspaceSession=computed(()=>{if(!session.value)return null;const dateObj=new Date(session.value.startedAt),isValidDate=!isNaN(dateObj.getTime());return{id:session.value.id,clientId:session.value.clientId,status:session.value.status==='in_progress'?'In Progress':(session.value.status==='completed'?'Completed':session.value.status),clientName:client.value?.display_name||client.value?.name||'Unknown Client',date:isValidDate?dateObj.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):'Pending',time:isValidDate?dateObj.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',hour12:true}):'',type:'Clinical session',videoProvider:'zoom',isInPerson:false}}); onMounted(loadSession);
</script>
