<template>
  <div class="flex flex-col h-full bg-surface-canvas">
    <div v-if="loading" class="flex-1 flex items-center justify-center"><div class="text-ink-muted flex flex-col items-center gap-2"><span class="w-8 h-8 border-4 border-state-selected border-t-transparent rounded-full animate-spin"></span><p>Loading clinical workspace…</p></div></div>
    <div v-else-if="error" class="flex-1 flex items-center justify-center p-inline-lg"><div class="max-w-md w-full bg-surface p-inline-lg py-stack-lg rounded-card shadow-sm border border-state-danger/20 text-center"><h2 class="text-h2 font-semibold text-state-danger mb-2">Workspace Error</h2><p class="text-ink-secondary mb-6">{{ error }}</p><button @click="loadSession" class="button-primary">Try Again</button></div></div>
    <template v-else-if="session"><SessionWorkspaceHeader :session="workspaceSession" :joiningMeeting="joiningMeeting" :meetingError="meetingError" @join-meeting="joinMeeting" /><WorkflowIndicator :activeStage="activeTab" @select-stage="activeTab = $event" /><div class="flex-1 overflow-auto p-inline-lg py-stack-lg"><div class="max-w-6xl mx-auto">
      <TranscriptTab v-if="activeTab === 'Session Capture'" :transcript="transcript" :loading="transcriptLoading" :error="transcriptError" :activeTab="activeTab" @retry="loadTranscript" @clinical-summary-draft="openClinicalSummaryDraft" @clinical-note-draft="openClinicalNoteDraft" @cbt-care-suggestions="openCbtCareSuggestions" />
      <TherapistNotesTab v-else-if="activeTab === 'Notes'" :clientId="session.clientId" :sessionId="session.id" :initialDraft="aiClinicalNoteDraft" @draft-consumed="aiClinicalNoteDraft = null" />
      <ReflectionTab v-else-if="activeTab === 'Reflection'" :clientId="session.clientId" :sessionId="session.id" />
      <CompletedClinicalRecord v-else-if="activeTab === 'Clinical Record' && session.status === 'completed'" :key="clinicalRecordKey" :session="session" />
      <template v-else-if="activeTab === 'Clinical Record'"><div v-if="aiClinicalSummaryDraft" class="mb-4 rounded-panel border border-state-info/20 bg-state-info/10 p-4"><p class="text-caption font-medium uppercase tracking-wider text-state-info">AI-assisted draft · not saved</p><p class="mt-1 text-body-sm text-ink-secondary">Helio prepared this editable draft from the linked transcript after your request. Review every field. It remains temporary until you choose Save Draft, and it is not a Clinical Record unless you later complete the separate review and approval steps.</p></div><ClinicalSummaryTab :key="clinicalRecordKey" :session="clinicalSummarySession" @update:session="handleSessionUpdate" /></template>
      <SupervisionSummaryTab v-else-if="activeTab === 'CPD'" :clientId="session.clientId" :sessionId="session.id" />
    </div></div></template>
  </div>
</template>
<script setup>
import {ref,onMounted,computed} from 'vue'; import {useRoute,useRouter} from 'vue-router'; import {getSession} from '../lib/sessions.js'; import {getClient} from '../lib/clients.js'; import {authenticatedFetch} from '../lib/api.js'; import SessionWorkspaceHeader from '../components/workspace/SessionWorkspaceHeader.vue'; import WorkflowIndicator from '../components/workspace/WorkflowIndicator.vue'; import TranscriptTab from '../components/workspace/TranscriptTab.vue'; import TherapistNotesTab from '../components/workspace/TherapistNotesTab.vue'; import ReflectionTab from '../components/workspace/ReflectionTab.vue'; import ClinicalSummaryTab from '../components/workspace/ClinicalSummaryTab.vue'; import CompletedClinicalRecord from '../components/workspace/CompletedClinicalRecord.vue'; import SupervisionSummaryTab from '../components/workspace/SupervisionSummaryTab.vue';
const route=useRoute(),router=useRouter(); const session=ref(null),client=ref(null),loading=ref(true),error=ref(''),transcript=ref(null),transcriptLoading=ref(false),transcriptError=ref(''),activeTab=ref('Session Capture'),joiningMeeting=ref(false),meetingError=ref(''),clinicalRecordKey=ref(0),aiClinicalSummaryDraft=ref(null),aiClinicalNoteDraft=ref(null);
function handleSessionUpdate(updatedSession){const becameCompleted=session.value?.status!=='completed'&&updatedSession?.status==='completed';session.value=updatedSession;aiClinicalSummaryDraft.value=null;if(becameCompleted)clinicalRecordKey.value+=1;} function openClinicalSummaryDraft(draft){if(!draft)return;aiClinicalSummaryDraft.value=draft;clinicalRecordKey.value+=1;activeTab.value='Clinical Record';} function openClinicalNoteDraft(draft){if(!draft)return;aiClinicalNoteDraft.value=draft;activeTab.value='Notes';} function openCbtCareSuggestions(data){if(!data?.suggestions?.length||!session.value?.clientId)return;sessionStorage.setItem(`helios-care-suggestions:${session.value.clientId}`,JSON.stringify({suggestions:data.suggestions,sessionId:data.sessionId||session.value.id,lensId:'gentle_cbt'}));router.push({name:'ClientWorkspace',params:{clientId:session.value.clientId},query:{tab:'Care',source:'session-cbt'}})}
async function joinMeeting(){if(!session.value?.id||!session.value?.clientId||joiningMeeting.value)return;joiningMeeting.value=true;meetingError.value='';try{const response=await authenticatedFetch('/api/zoom/start-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:session.value.clientId,sessionRef:session.value.id})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to open Zoom for this session.');if(!data.startUrl)throw new Error('Zoom did not return a meeting link.');window.open(data.startUrl,'_blank','noopener,noreferrer')}catch(err){meetingError.value=err?.message||'Unable to open Zoom for this session.'}finally{joiningMeeting.value=false}}
async function loadSession(){loading.value=true;error.value='';aiClinicalSummaryDraft.value=null;aiClinicalNoteDraft.value=null;try{const {clientId,sessionId}=route.params;const [sessionData,clientData]=await Promise.all([getSession({clientId,sessionId}),getClient({clientId})]);session.value=sessionData;client.value=clientData;loadTranscript()}catch(e){error.value='The clinical workspace could not be loaded.'}finally{loading.value=false}}
async function loadTranscript(){if(!session.value?.id||!session.value?.clientId)return;transcriptLoading.value=true;transcriptError.value='';transcript.value=null;try{const params=new URLSearchParams({sessionRef:String(session.value.id),clientId:String(session.value.clientId)});const response=await authenticatedFetch(`/api/zoom/transcripts?${params.toString()}`);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Unable to load the linked transcript.');transcript.value=data.transcripts?.[0]||null}catch(err){transcriptError.value=err?.message||'Unable to load the linked transcript.'}finally{transcriptLoading.value=false}}
const clinicalSummarySession=computed(()=>{if(!session.value)return null;if(!aiClinicalSummaryDraft.value)return session.value;return{...session.value,notes:JSON.stringify(aiClinicalSummaryDraft.value)}}); const workspaceSession=computed(()=>{if(!session.value)return null;const dateObj=new Date(session.value.startedAt),isValidDate=!isNaN(dateObj.getTime());return{id:session.value.id,clientId:session.value.clientId,status:session.value.status==='in_progress'?'In Progress':(session.value.status==='completed'?'Completed':session.value.status),clientName:client.value?.display_name||client.value?.name||'Unknown Client',date:isValidDate?dateObj.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}):'Pending',time:isValidDate?dateObj.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',hour12:true}):'',type:'Clinical session',videoProvider:'zoom',isInPerson:false}}); onMounted(loadSession);
</script>
