<template>
  <PublicPageShell title="Terms of Service" eyebrow="Legal" summary="Terms for current testing and beta use of Helios by individual therapists.">
    <section><h2 class="type-subsection">About Helios</h2><p class="mt-2 type-body text-ink-secondary">Helios Therapist is a workspace for therapists to manage practice administration, session work, notes, Clinical Records, professional reflection and CPD. Product, service and account questions can be sent to <a class="text-action-link hover:underline" href="mailto:hello@helio.works">hello@helio.works</a>.</p></section>
    <section><h2 class="type-subsection">Current service scope</h2><p class="mt-2 type-body text-ink-secondary">Helios is currently intended for individual therapists operating their own professional practice. Each account is a single-therapist workspace for that therapist's own practice data. Organisational, shared-practice and multi-user clinic accounts are not currently supported and should not be created or operated as though they were.</p></section>
    <section><h2 class="type-subsection">Testing and beta service</h2><p class="mt-2 type-body text-ink-secondary">Helios is currently being tested and developed. Features may change, be interrupted or occasionally be unavailable. Testers should use the service with appropriate professional judgement and should not rely on Helios as the sole means of meeting a legal, clinical, safeguarding or record-keeping obligation.</p></section>
    <section><h2 class="type-subsection">Professional responsibility</h2><p class="mt-2 type-body text-ink-secondary">Helios supports professional work but does not replace clinical judgement, supervision, professional standards or legal obligations. Therapists remain responsible for reviewing information, deciding what belongs in a Clinical Record and using the service appropriately for their practice.</p></section>
    <section><h2 class="type-subsection">AI and transcripts</h2><p class="mt-2 type-body text-ink-secondary">AI-assisted and transcript-derived material is draft or suggestion material for therapist review. It does not become an approved Clinical Record automatically.</p></section>
    <section><h2 class="type-subsection">Connected services</h2><p class="mt-2 type-body text-ink-secondary">Helios can connect to optional third-party services including Google and Zoom. Those services remain subject to their own availability and terms, and therapists choose whether to enable the relevant integration.</p></section>
    <section><h2 class="type-subsection">Accounts and security</h2><p class="mt-2 type-body text-ink-secondary">Users must keep their account credentials secure and must not use Helios to access information they are not authorised to access. Access may be suspended where reasonably necessary to protect the service, users or data.</p></section>
    <section><h2 class="type-subsection">Changes to the service and terms</h2><p class="mt-2 type-body text-ink-secondary">Because Helios is in testing and beta, the service and these terms may change as the product develops. Material changes affecting current users will be reflected in the published terms. Paid-service terms and any future clinic or organisational terms will be introduced separately if and when those services are offered.</p></section>
  </PublicPageShell>
</template>
<script setup>import PublicPageShell from '../components/PublicPageShell.vue'</script>
