<template>
  <main class="page"><section class="card">
    <p v-if="loading">Opening your questionnaire…</p>
    <template v-else-if="submitted"><p class="eyebrow">Submitted</p><h1>Thank you</h1><p>Your response has been sent to your therapist for review.</p></template>
    <template v-else-if="error"><h1>This item is unavailable</h1><p>{{ error }}</p></template>
    <template v-else><p class="eyebrow">Helio</p><h1>{{ assignment.title }}</h1><p v-if="assignment.description">{{ assignment.description }}</p><p v-if="assignment.instruction" class="instruction"><strong>Your therapist asks:</strong> {{ assignment.instruction }}</p><form @submit.prevent="submit"><p class="period">Over the last two weeks, how often have you been bothered by any of the following problems?</p><fieldset v-for="(item, index) in phq9Items" :key="index"><legend>{{ index + 1 }}. {{ item }}</legend><label v-for="[value, label] in phq9Choices" :key="value"><input v-model="answers[`q${index + 1}`]" type="radio" :name="`q${index + 1}`" :value="value" required /> {{ label }}</label></fieldset><section v-if="needsUrgentSupport" class="urgent" role="alert"><strong>Please do not wait for your therapist to review this form.</strong><p>If you feel you might harm yourself, or cannot stay safe, contact local emergency services now, go to the nearest emergency department, or contact a crisis service in your country. If you are in immediate danger, call your local emergency number.</p><p>You can still submit this questionnaire, but it is not monitored as an emergency service.</p></section><p v-if="submitError" class="error">{{ submitError }}</p><button :disabled="submitting" type="submit">{{ submitting ? 'Submitting…' : 'Submit to therapist' }}</button></form></template>
  </section></main>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { phq9Choices, phq9Items } from '../lib/phq9.js'
const token = new URLSearchParams(window.location.search).get('token') || ''
const loading = ref(true), error = ref(''), assignment = ref(null), answers = ref({}), submitting = ref(false), submitError = ref(''), submitted = ref(false)
const needsUrgentSupport = computed(() => Number(answers.value.q9) > 0)
async function json(response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Unable to open this item.'); return data }
onMounted(async () => { try { assignment.value = (await json(await fetch(`/api/client-completion?token=${encodeURIComponent(token)}`))).assignment } catch (cause) { error.value = cause.message } finally { loading.value = false } })
async function submit() { submitting.value = true; submitError.value = ''; try { await json(await fetch('/api/client-completion', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, answers: answers.value }) })); submitted.value = true } catch (cause) { submitError.value = cause.message } finally { submitting.value = false } }
</script>
<style scoped>
.page{min-height:100vh;background:var(--surface-canvas);padding:1.25rem;display:flex;justify-content:center}.card{width:min(42rem,100%);height:max-content;background:var(--surface-elevated);border:1px solid var(--border-muted);border-radius:1rem;padding:1.4rem;color:var(--text-primary)}.eyebrow{margin:0;color:var(--text-muted);text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;font-weight:700}.card h1{margin:.35rem 0 .65rem;font-size:1.55rem}.card>p{line-height:1.55;color:var(--text-secondary)}.instruction{padding:.8rem;border-radius:.6rem;background:var(--surface-muted);border:1px solid var(--state-selected)}.period{font-size:.9rem;color:var(--text-secondary)}fieldset{margin:1rem 0;padding:1rem;border:1px solid var(--border-muted);border-radius:.7rem}legend{font-weight:700;line-height:1.4;padding:0 .25rem}label{display:block;padding:.65rem .25rem;border-top:1px solid var(--border-muted);font-size:.95rem}label:first-of-type{margin-top:.6rem}input{margin-right:.45rem}button{width:100%;min-height:3rem;border:0;border-radius:.65rem;background:var(--action-link);color:var(--text-on-action);font:inherit;font-weight:700;margin-top:.5rem}.error,.urgent{padding:.8rem;border-radius:.6rem}.error{background:var(--state-danger-surface);color:var(--state-danger)}.urgent{background:var(--state-warning-surface);border:1px solid var(--state-warning);color:var(--state-warning);line-height:1.45}.urgent p{margin:.55rem 0 0}@media(max-width:500px){.page{padding:0}.card{border-radius:0;border:0;padding:1.2rem}fieldset{padding:.85rem}label{padding:.8rem .25rem}}
</style>
