<template>
  <div class="max-w-3xl mx-auto py-6 sm:py-10 px-4 sm:px-6 w-full overflow-x-hidden">
    <header class="mb-8 sm:mb-10"><h1 class="text-h2 sm:text-h1 font-semibold text-ink">Settings</h1></header>

    <section class="mb-12">
      <h2 class="text-caption sm:text-body-sm font-semibold uppercase tracking-wider text-ink-muted mb-4 px-1">Professional profile</h2>
      <form class="bg-surface-elevated border border-border-muted rounded-panel p-4 sm:p-5 space-y-5" @submit.prevent="saveProfile">
        <p class="text-body-sm text-ink-subtle">These details identify you and your practice. They are also available to supported Helio documents.</p>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <label class="block"><span class="text-body-sm font-medium text-ink-secondary">Full name</span><input v-model.trim="profile.full_name" type="text" autocomplete="name" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block"><span class="text-body-sm font-medium text-ink-secondary">Professional title</span><input v-model.trim="profile.professional_title" type="text" placeholder="Psychotherapist" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block sm:col-span-2"><span class="text-body-sm font-medium text-ink-secondary">Practice name</span><input v-model.trim="profile.practice_name" type="text" autocomplete="organization" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block"><span class="text-body-sm font-medium text-ink-secondary">Practice email</span><input v-model.trim="profile.document_email" type="email" autocomplete="email" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block"><span class="text-body-sm font-medium text-ink-secondary">Practice phone</span><input v-model.trim="profile.document_phone" type="tel" autocomplete="tel" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block sm:col-span-2"><span class="text-body-sm font-medium text-ink-secondary">Practice website</span><input v-model.trim="profile.practice_website" type="url" autocomplete="url" placeholder="https://" class="mt-2 min-h-touch w-full rounded-control border border-border bg-surface px-3 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected" /></label>
          <label class="block sm:col-span-2"><span class="text-body-sm font-medium text-ink-secondary">Practice address</span><textarea v-model.trim="profile.practice_address" rows="3" autocomplete="street-address" class="mt-2 w-full rounded-control border border-border bg-surface px-3 py-2.5 text-ink outline-none focus:border-action-link focus:ring-2 focus:ring-state-selected"></textarea></label>
        </div>
        <div class="flex flex-wrap items-center gap-3"><button type="submit" :disabled="isSavingProfile || isLoadingProfile" class="min-h-touch px-4 py-2 rounded-control bg-action-link text-on-action text-body-sm font-medium hover:bg-action-link-hover disabled:opacity-50">{{ isSavingProfile ? 'Saving…' : 'Save profile' }}</button><span v-if="profileError" role="alert" class="text-body-sm text-state-danger">{{ profileError }}</span></div>
      </form>
    </section>

    <section class="mb-12">
      <h2 class="text-caption sm:text-body-sm font-semibold uppercase tracking-wider text-ink-muted mb-4 px-1">Integrations</h2>
      <div class="bg-surface-elevated border border-border-muted rounded-panel overflow-hidden">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between p-4 border-b border-border-muted gap-4">
          <div class="flex items-start sm:items-center gap-4">
            <span class="icon-surface icon-surface-accent !w-10 !h-10" aria-hidden="true"><CalendarDays class="workspace-icon-lg" /></span>
            <div class="min-w-0 flex-1"><div class="text-body font-medium text-ink break-words">Google Calendar</div><div class="text-body-sm break-words" :class="googleStatus === 'Connected' ? 'text-state-success' : 'text-ink-subtle'"><span v-if="isLoadingStatus" class="text-ink-subtle animate-pulse">Checking status...</span><div v-else-if="googleStatus === 'Connected' || googleStatus === 'Reconnect Required'" class="flex flex-col mt-1"><span class="font-medium inline-flex items-center gap-1.5" :class="googleStatus === 'Connected' ? 'text-state-success' : 'text-state-warning'"><CircleCheck v-if="googleStatus === 'Connected'" class="workspace-icon-sm" aria-hidden="true" /><TriangleAlert v-else class="workspace-icon-sm" aria-hidden="true" />{{ googleStatus }}</span><span v-if="googleEmail" class="text-ink text-body-sm">{{ googleEmail }}</span><span class="text-ink-subtle text-overline leading-tight">{{ lastSyncedGoogle }}</span></div><span v-else>Not connected</span></div></div>
          </div>
          <div class="flex items-center gap-2 w-full sm:w-auto"><details v-if="googleStatus === 'Connected'" class="relative"><summary class="list-none cursor-pointer min-h-touch sm:min-h-0 px-3 py-2 sm:py-1.5 text-body-sm font-medium text-ink-muted hover:bg-surface-subtle rounded-control"><MoreHorizontal class="workspace-icon" aria-label="Google Calendar actions" /></summary><div class="absolute right-0 mt-1 z-10 w-48 bg-surface-elevated border border-border-muted rounded-control shadow-overlay p-1"><button @click="disconnectGoogle" class="w-full text-left px-3 py-2 text-body-sm text-state-danger hover:bg-state-danger-surface rounded">Disconnect Google Calendar</button></div></details><button v-else @click="connectGoogle" :disabled="isConnectingGoogle" class="w-full sm:w-auto min-h-touch sm:min-h-0 px-4 py-2 sm:py-1.5 text-body-sm font-medium text-action-link hover:bg-state-selected rounded-control border border-transparent hover:border-state-selected disabled:opacity-50">{{ isConnectingGoogle ? 'Connecting...' : googleStatus === 'Reconnect Required' ? 'Reconnect' : 'Connect' }}</button></div>
        </div>
        <div class="flex flex-col sm:flex-row sm:items-center justify-between p-4 gap-4">
          <div class="flex items-start sm:items-center gap-4">
            <span class="icon-surface icon-surface-reflection !w-10 !h-10" aria-hidden="true"><Video class="workspace-icon-lg" /></span>
            <div class="min-w-0 flex-1"><div class="text-body font-medium text-ink break-words">Zoom</div><div class="text-body-sm" :class="zoomStatus === 'Connected' ? 'text-state-success' : 'text-ink-subtle'"><span v-if="isLoadingZoomStatus" class="text-ink-subtle animate-pulse">Checking status...</span><span v-else-if="zoomStatus === 'Connected'" class="font-medium inline-flex items-center gap-1.5"><CircleCheck class="workspace-icon-sm" aria-hidden="true" />Connected</span><span v-else>Not connected</span></div></div>
          </div>
          <div class="flex items-center gap-2 w-full sm:w-auto"><details v-if="zoomStatus === 'Connected'" class="relative"><summary class="list-none cursor-pointer min-h-touch sm:min-h-0 px-3 py-2 sm:py-1.5 text-body-sm font-medium text-ink-muted hover:bg-surface-subtle rounded-control"><MoreHorizontal class="workspace-icon" aria-label="Zoom actions" /></summary><div class="absolute right-0 mt-1 z-10 w-48 bg-surface-elevated border border-border-muted rounded-control shadow-overlay p-1"><button @click="disconnectZoom" class="w-full text-left px-3 py-2 text-body-sm text-state-danger hover:bg-state-danger-surface rounded">Disconnect Zoom</button></div></details><button v-else @click="connectZoom" :disabled="isConnectingZoom" class="w-full sm:w-auto min-h-touch sm:min-h-0 px-4 py-2 sm:py-1.5 text-body-sm font-medium text-action-link hover:bg-state-selected rounded-control border border-transparent hover:border-state-selected disabled:opacity-50">{{ isConnectingZoom ? 'Connecting...' : 'Connect' }}</button></div>
        </div>
      </div>
      <p class="mt-3 px-1 text-caption text-ink-subtle">Only integrations with a supported Helio workflow are shown here. Video links are chosen when scheduling or working with an appointment rather than stored as a separate default setting.</p>
    </section>

    <section class="mb-12"><h2 class="text-caption sm:text-body-sm font-semibold uppercase tracking-wider text-ink-muted mb-4 px-1">Account</h2><div class="bg-surface-elevated border border-border-muted rounded-panel p-4 flex items-center justify-between gap-4"><div class="flex items-center gap-3"><span class="icon-surface" aria-hidden="true"><ShieldCheck class="workspace-icon" /></span><div><div class="text-body font-medium text-ink">Therapist account</div><div class="text-body-sm text-ink-subtle">Secure Supabase session</div></div></div><button @click="signOut" class="px-4 py-2 text-body-sm font-medium text-state-danger hover:bg-state-danger-surface rounded-control">Sign out</button></div></section>

    <Transition name="fade"><div v-if="showSuccess" class="fixed bottom-8 left-1/2 transform -translate-x-1/2 bg-ink text-on-action px-6 py-3 rounded-pill shadow-overlay flex items-center gap-3 z-50"><CircleCheck class="workspace-icon text-state-success" aria-hidden="true" /><span class="text-body font-medium">{{ successMessage }}</span></div></Transition>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { CalendarDays, CircleCheck, MoreHorizontal, ShieldCheck, TriangleAlert, Video } from '@lucide/vue'
import { authenticatedFetch } from '../lib/api.js'
import { supabase } from '../lib/supabase.js'

const emptyProfile = () => ({ full_name:'', professional_title:'', practice_name:'', document_email:'', document_phone:'', practice_website:'', practice_address:'' })
const profile = ref(emptyProfile())
const isLoadingProfile = ref(true), isSavingProfile = ref(false), profileError = ref('')
const googleStatus = ref('Not connected'), googleEmail = ref(''), lastSyncedGoogle = ref('Not synced yet'), isConnectingGoogle = ref(false), isLoadingStatus = ref(true)
const zoomStatus = ref('Not connected'), isConnectingZoom = ref(false), isLoadingZoomStatus = ref(true)
const showSuccess = ref(false), successMessage = ref('')

onMounted(async () => { const params = new URLSearchParams(window.location.search); if (params.get('google') === 'success') { successMessage.value='Google Calendar connected successfully'; showSuccess.value=true; cleanupUrl() } if (params.get('zoom') === 'success') { successMessage.value='Zoom connected successfully'; showSuccess.value=true; cleanupUrl() } if (params.get('google') === 'error') { alert(params.get('message') || 'Google connection failed'); cleanupUrl() } if (params.get('zoom') === 'error') { alert(params.get('message') || 'Zoom connection failed'); cleanupUrl() } await Promise.all([loadProfile(), fetchGoogleStatus(), fetchZoomStatus()]) })
const loadProfile = async () => { isLoadingProfile.value=true;profileError.value='';try{const {data:{user},error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!user)throw new Error('Unable to load your therapist profile.');const {data,error}=await supabase.from('profiles').select('full_name,professional_title,practice_name,document_email,document_phone,practice_website,practice_address').eq('id',user.id).maybeSingle();if(error)throw error;profile.value={...emptyProfile(),...(data||{})}}catch(error){profileError.value=error.message||'Unable to load your therapist profile.'}finally{isLoadingProfile.value=false}}
const saveProfile = async () => { isSavingProfile.value=true;profileError.value='';try{const {data:{user},error:userError}=await supabase.auth.getUser();if(userError)throw userError;if(!user)throw new Error('Unable to save your therapist profile.');const {error}=await supabase.from('profiles').upsert({id:user.id,...profile.value},{onConflict:'id'});if(error)throw error;successMessage.value='Professional profile saved';showSuccess.value=true;setTimeout(()=>{showSuccess.value=false},3000)}catch(error){profileError.value=error.message||'Unable to save your therapist profile.'}finally{isSavingProfile.value=false}}
const formatSyncTime=value=>{if(!value)return'Not synced yet';const date=new Date(value),elapsed=Date.now()-date.getTime();if(elapsed>=0&&elapsed<60000)return'Synced just now';if(elapsed>=0&&elapsed<3600000)return`Last synced ${Math.floor(elapsed/60000)}m ago`;return`Last synced ${date.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}`}
const cleanupUrl=()=>{window.history.replaceState({},document.title,window.location.pathname);setTimeout(()=>{showSuccess.value=false},3000)}
const fetchGoogleStatus=async()=>{isLoadingStatus.value=true;try{const response=await authenticatedFetch('/api/google/status');if(response.ok){const data=await response.json();if(data.connected){googleEmail.value=data.email||'';googleStatus.value=['GOOGLE_TOKEN_EXPIRED','GOOGLE_REVOKED','GOOGLE_TOKEN_MISSING'].includes(data.error)?'Reconnect Required':'Connected';lastSyncedGoogle.value=formatSyncTime(data.last_synced_at)}else{googleStatus.value='Not connected';googleEmail.value=''}}}catch(err){console.error('Failed to fetch Google status:',err)}finally{isLoadingStatus.value=false}}
const fetchZoomStatus=async()=>{isLoadingZoomStatus.value=true;try{const response=await authenticatedFetch('/api/zoom/status');const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to check Zoom connection');zoomStatus.value=data.connected?'Connected':'Not connected'}catch(error){console.error('Failed to fetch Zoom status:',error);zoomStatus.value='Not connected'}finally{isLoadingZoomStatus.value=false}}
const connectGoogle=async()=>{isConnectingGoogle.value=true;try{const response=await authenticatedFetch('/api/google/authorize',{method:'POST'});const data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||'Unable to start Google connection');window.location.href=data.url}catch(error){alert(error.message);isConnectingGoogle.value=false}}
const disconnectGoogle=async()=>{if(!confirm('Disconnect Google Calendar?'))return;try{const response=await authenticatedFetch('/api/google/disconnect',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to disconnect Google Calendar');googleStatus.value='Not connected';googleEmail.value='';lastSyncedGoogle.value='Not synced yet';successMessage.value='Google Calendar disconnected';showSuccess.value=true;setTimeout(()=>showSuccess.value=false,3000)}catch(err){console.error('Failed to disconnect Google:',err);alert('Failed to disconnect Google Calendar')}}
const connectZoom=async()=>{isConnectingZoom.value=true;try{const response=await authenticatedFetch('/api/zoom/authorize',{method:'POST'});const data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||'Unable to start Zoom connection');window.location.href=data.url}catch(error){alert(error.message);isConnectingZoom.value=false}}
const disconnectZoom=async()=>{if(!confirm('Disconnect Zoom? Helio will no longer retrieve future Zoom transcripts.'))return;try{const response=await authenticatedFetch('/api/zoom/disconnect',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to disconnect Zoom');zoomStatus.value='Not connected';successMessage.value='Zoom disconnected';showSuccess.value=true;setTimeout(()=>showSuccess.value=false,3000)}catch(error){console.error('Failed to disconnect Zoom:',error);alert(error.message)}}
const signOut=async()=>{await supabase.auth.signOut()}
</script>

<style scoped>
.fade-enter-active,.fade-leave-active{transition:opacity .3s ease,transform .3s ease}.fade-enter-from,.fade-leave-to{opacity:0;transform:translate(-50%,20px)}
</style>
