<template>
  <section class="rounded-panel border border-border bg-surface p-5">
    <div class="flex items-start justify-between gap-4"><div><p class="type-overline text-ink-muted">Outgoing documents</p><h3 class="text-h3 font-semibold mt-1">Practice identity</h3><p class="text-body-sm text-ink-secondary mt-1">Used on professional PDFs and letters. Keep this as the identity you want recipients to see.</p></div><button type="button" class="button-secondary" @click="expanded=!expanded">{{ expanded?'Done':'Edit' }}</button></div>
    <div v-if="!expanded" class="mt-4 text-body-sm text-ink-secondary"><strong class="text-ink">{{ model.practiceName||model.fullName||'Not configured' }}</strong><span v-if="model.professionalTitle"> · {{ model.professionalTitle }}</span><p v-if="!model.practiceName&&!model.fullName" class="text-state-warning mt-1">Add your practice identity before sending documents externally.</p></div>
    <form v-else class="mt-5 grid sm:grid-cols-2 gap-4" @submit.prevent="save"><label><span class="text-caption font-semibold">Your name</span><input v-model="model.fullName" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" /></label><label><span class="text-caption font-semibold">Practice name</span><input v-model="model.practiceName" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" /></label><label><span class="text-caption font-semibold">Professional title</span><input v-model="model.professionalTitle" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" placeholder="e.g. Integrative Psychotherapist" /></label><label><span class="text-caption font-semibold">Document email</span><input v-model="model.email" type="email" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" /></label><label><span class="text-caption font-semibold">Phone</span><input v-model="model.phone" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" /></label><label><span class="text-caption font-semibold">Website</span><input v-model="model.website" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" /></label><label class="sm:col-span-2"><span class="text-caption font-semibold">Practice address</span><textarea v-model="model.address" rows="2" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface resize-y" /></label><label class="sm:col-span-2"><span class="text-caption font-semibold">Footer / registration details</span><input v-model="model.footer" class="mt-1 w-full p-2.5 border border-border rounded-control bg-surface" placeholder="Optional professional registration or footer text" /></label><div class="sm:col-span-2 flex items-center gap-3"><button class="button-primary" :disabled="saving">{{ saving?'Saving…':'Save practice identity' }}</button><span class="text-caption" :class="error?'text-state-danger':'text-state-success'">{{ error||message }}</span></div></form>
  </section>
</template>
<script setup>
import { onMounted,reactive,ref } from 'vue';import { getDocumentProfile,saveDocumentProfile } from '../../lib/documentProfile.js';
const emit=defineEmits(['updated']);const expanded=ref(false),saving=ref(false),error=ref(''),message=ref('');const model=reactive({fullName:'',practiceName:'',professionalTitle:'',email:'',phone:'',website:'',address:'',footer:''});
onMounted(async()=>{try{Object.assign(model,await getDocumentProfile());emit('updated',{...model})}catch(e){error.value=e.message||'Could not load practice identity.'}});
async function save(){saving.value=true;error.value='';message.value='';try{const saved=await saveDocumentProfile(model);Object.assign(model,saved);emit('updated',saved);message.value='Saved';expanded.value=false}catch(e){error.value=e.message||'Could not save practice identity.'}finally{saving.value=false}}
</script>
