<template>
  <div class="flex h-screen bg-surface-canvas text-ink overflow-hidden">
    <Transition name="slide"><aside v-if="isMobileMenuOpen" class="fixed inset-y-0 left-0 z-50 w-64 bg-sidebar border-r border-border-muted shadow-overlay md:hidden flex flex-col"><div class="h-16 flex items-center justify-between px-5 border-b border-border-muted shrink-0"><BrandLockup/><button class="p-2 -mr-2 text-ink-subtle hover:text-ink-secondary" @click="isMobileMenuOpen=false" aria-label="Close menu"><X class="workspace-icon-lg" /></button></div><SidebarNavigation :groups="navGroups" :current-path="$route.path" @navigate="isMobileMenuOpen=false" /><SidebarAccount :account="accountIdentity" @sign-out="handleSignOut" /></aside></Transition>
    <Transition name="fade"><div v-if="isMobileMenuOpen" class="fixed inset-0 z-40 bg-backdrop backdrop-blur-sm md:hidden" @click="isMobileMenuOpen=false"></div></Transition>
    <aside class="hidden md:flex flex-col w-64 bg-sidebar border-r border-border-muted h-full shrink-0"><div class="h-16 flex items-center px-5 border-b border-border-muted shrink-0"><BrandLockup/></div><SidebarNavigation :groups="navGroups" :current-path="$route.path" /><SidebarAccount :account="accountIdentity" @sign-out="handleSignOut" /></aside>
    <div class="flex flex-col flex-1 min-w-0 min-h-0 h-full overflow-hidden">
      <header class="h-16 flex items-center justify-between px-inline-lg md:px-6 border-b border-border-muted bg-surface shrink-0">
        <div class="flex items-center gap-inline-md"><button class="md:hidden p-2 -ml-2 text-ink-secondary hover:bg-surface-subtle rounded-control" @click="isMobileMenuOpen=true" aria-label="Open menu"><Menu class="workspace-icon-lg" /></button><h2 class="type-body-medium text-ink truncate">{{ currentPageName }}</h2></div>
        <div class="flex items-center gap-2">
          <div class="hidden lg:flex items-center gap-2.5 whitespace-nowrap text-ink-muted" data-testid="global-appointment-clock" :data-appointment-approaching="isAppointmentApproaching?'true':'false'" aria-live="off"><time class="type-ui tabular-nums font-medium text-ink-secondary" :datetime="now.toISOString()">{{ currentTimeLabel }}</time><span class="h-4 w-px bg-border-muted" aria-hidden="true"></span><span v-if="nextAppointment" class="type-metadata" :class="isAppointmentApproaching?'text-ink-secondary':'text-ink-muted'">Next {{ nextAppointmentTimeLabel }}<span class="ml-1.5" :class="isAppointmentApproaching?'font-semibold text-accent':'text-ink-subtle'">{{ nextAppointmentCountdownLabel }}</span></span><span v-else class="type-metadata text-ink-subtle">No upcoming appointment</span></div>
          <span class="hidden lg:block mx-1 h-6 w-px bg-border-muted" aria-hidden="true"></span>
          <button type="button" class="h-9 inline-flex items-center gap-1.5 px-3 rounded-control border type-ui whitespace-nowrap transition-colors" :class="outstandingReminderCount?'border-brand-amber/40 bg-brand-amber-soft/60 text-ink':'border-border-muted bg-surface text-ink-secondary hover:bg-surface-subtle'" :aria-expanded="showQuickCapture" aria-haspopup="dialog" @click="showQuickCapture=!showQuickCapture"><Plus class="workspace-icon-sm text-focus" aria-hidden="true" /><span class="hidden sm:inline">Quick capture</span><span v-if="outstandingReminderCount" class="min-w-5 h-5 px-1.5 inline-flex items-center justify-center rounded-pill bg-brand-amber/15 type-metadata font-semibold">{{ outstandingReminderCount }}</span></button>
          <router-link v-if="$route.path!=='/schedule'" to="/schedule" class="hidden sm:inline-flex h-9 items-center gap-1.5 px-3 rounded-control border border-border-muted bg-surface type-ui whitespace-nowrap text-ink-secondary hover:bg-surface-subtle hover:text-ink transition-colors"><CalendarDays class="workspace-icon-sm text-accent" aria-hidden="true" /><span>Schedule</span></router-link>
          <button type="button" class="hidden sm:inline-flex h-9 min-w-[4.25rem] items-center justify-center px-3 rounded-control border type-ui font-semibold whitespace-nowrap transition-colors" :class="canJoinNextAppointment?'border-action-primary bg-action-primary text-on-action hover:bg-action-primary-hover':'border-border-muted bg-surface-subtle text-ink-subtle cursor-default'" :disabled="!canJoinNextAppointment||joiningNextAppointment" :title="canJoinNextAppointment?'Join next appointment':'No joinable appointment'" @click="joinNextAppointment">{{ joiningNextAppointment?'Opening…':'Join' }}</button>
        </div>
      </header>
      <main class="flex-1 min-h-0 bg-surface-canvas relative" :class="isFullHeightWorkspace?'overflow-hidden':'overflow-y-auto overflow-x-hidden'"><slot/></main>
    </div>
    <GlobalQuickCapture v-if="showQuickCapture" :reminders="openReminders" @close="showQuickCapture=false" @saved="refreshReminders" @changed="refreshReminders" />
  </div>
</template>
<script setup>
import { computed,defineComponent,h,onMounted,onUnmounted,ref } from 'vue';import { RouterLink,useRoute,useRouter } from 'vue-router';import { CalendarDays,FileText,FolderOpen,GraduationCap,LayoutDashboard,LogOut,Menu,MoreHorizontal,Plus,Settings,Sun,Users,X } from '@lucide/vue';import { supabase } from '../lib/supabase.js';import { authenticatedFetch } from '../lib/authenticatedFetch.js';import { listScheduledAppointments } from '../lib/appointments.js';import { nextTimedAppointment } from '../lib/nextAppointment.js';import { createOrResumeSession } from '../lib/sessions.js';import { listTherapistReminders } from '../lib/therapistReminders.js';import GlobalQuickCapture from '../components/reminders/GlobalQuickCapture.vue';
const route=useRoute(),router=useRouter(),isMobileMenuOpen=ref(false),accountIdentity=ref({name:'Signed in',subtitle:'',initials:'·'}),fullHeightWorkspacePaths=new Set(['/calendar','/transcripts']),isFullHeightWorkspace=computed(()=>fullHeightWorkspacePaths.has(route.path)),showQuickCapture=ref(false),reminders=ref([]),openReminders=computed(()=>reminders.value.filter(item=>!item.completedAt)),outstandingReminderCount=computed(()=>openReminders.value.length),now=ref(new Date()),appointments=ref([]),googleEvents=ref([]),joiningNextAppointment=ref(false);let clockTimer,appointmentRefreshTimer;
const nextAppointment=computed(()=>nextTimedAppointment({appointments:appointments.value,googleEvents:googleEvents.value,now:now.value})),canJoinNextAppointment=computed(()=>nextAppointment.value?.source==='appointment'&&Boolean(nextAppointment.value.appointment?.zoom_meeting_id)),minutesUntilNextAppointment=computed(()=>nextAppointment.value?Math.ceil((nextAppointment.value.start.getTime()-now.value.getTime())/60000):null),isAppointmentApproaching=computed(()=>minutesUntilNextAppointment.value!==null&&minutesUntilNextAppointment.value>=0&&minutesUntilNextAppointment.value<=15),currentTimeLabel=computed(()=>now.value.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})),nextAppointmentTimeLabel=computed(()=>nextAppointment.value?nextAppointment.value.start.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):''),nextAppointmentCountdownLabel=computed(()=>{if(!nextAppointment.value)return'';const minutes=Math.max(0,minutesUntilNextAppointment.value);if(minutes<60)return minutes===1?'in 1 min':`in ${minutes} min`;const hours=Math.floor(minutes/60),remaining=minutes%60;return remaining?`in ${hours}h ${remaining}m`:`in ${hours}h`});
async function refreshReminders(){try{reminders.value=await listTherapistReminders()}catch(error){console.warn('[AppShell] Reminders unavailable',error)}}async function loadUpcomingGoogleEvents(){try{const s=await authenticatedFetch('/api/google/status');if(!s.ok)return[];const status=await s.json();if(!status.connected)return[];const timeMin=new Date();timeMin.setHours(0,0,0,0);const timeMax=new Date(timeMin);timeMax.setDate(timeMax.getDate()+31);const r=await authenticatedFetch(`/api/google/events?${new URLSearchParams({timeMin:timeMin.toISOString(),timeMax:timeMax.toISOString()})}`);if(!r.ok)return[];return (await r.json()).events||[]}catch{return[]}}async function refreshAppointments(){try{[appointments.value,googleEvents.value]=await Promise.all([listScheduledAppointments(),loadUpcomingGoogleEvents()])}catch(error){console.warn('[AppShell] Appointments unavailable',error)}}function refreshAppointmentsWhenActive(){if(document.visibilityState==='visible')refreshAppointments()}async function joinNextAppointment(){if(!canJoinNextAppointment.value||joiningNextAppointment.value)return;joiningNextAppointment.value=true;try{const appointment=nextAppointment.value.appointment,{session}=await createOrResumeSession(appointment.client_id),response=await authenticatedFetch('/api/zoom/join-appointment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:appointment.client_id,appointmentId:appointment.id})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to join the appointment.');window.open(data.startUrl,'_blank','noopener,noreferrer');await router.push(`/clients/${session.clientId}/sessions/${session.id}`)}finally{joiningNextAppointment.value=false}}
function initialsFor(value){const parts=String(value||'').trim().split(/\s+/).filter(Boolean);return parts.length?parts.slice(0,2).map(p=>p[0]?.toUpperCase()||'').join(''):'·'}async function loadAccountIdentity(){if(!supabase)return;try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:profile}=await supabase.from('profiles').select('full_name,role,professional_title').eq('id',user.id).maybeSingle(),metadataName=typeof user.user_metadata?.full_name==='string'?user.user_metadata.full_name.trim():'',email=user.email||'',name=profile?.full_name?.trim()||metadataName||email||'Signed in';accountIdentity.value={name,subtitle:profile?.professional_title?.trim()||profile?.role?.trim()||(name!==email?email:''),initials:initialsFor(name)}}catch{}}const handleReminderChange=()=>refreshReminders();onMounted(()=>{window.addEventListener('helios-reminders-changed',handleReminderChange);window.addEventListener('focus',refreshAppointments);document.addEventListener('visibilitychange',refreshAppointmentsWhenActive);loadAccountIdentity();refreshReminders();refreshAppointments();clockTimer=window.setInterval(()=>now.value=new Date(),30000);appointmentRefreshTimer=window.setInterval(refreshAppointments,60000)});onUnmounted(()=>{window.removeEventListener('helios-reminders-changed',handleReminderChange);window.removeEventListener('focus',refreshAppointments);document.removeEventListener('visibilitychange',refreshAppointmentsWhenActive);clearInterval(clockTimer);clearInterval(appointmentRefreshTimer)});async function handleSignOut(){if(supabase)await supabase.auth.signOut();await router.replace('/sign-in')}
const navGroups=[{label:'Practice',items:[{name:'Overview',path:'/overview',icon:LayoutDashboard,iconTone:'icon-surface-accent'},{name:'Calendar',path:'/calendar',icon:CalendarDays,iconTone:'icon-surface-reflection'},{name:'Clients',path:'/clients',icon:Users,iconTone:'icon-surface-accent'}]},{label:'Records',items:[{name:'Transcripts',path:'/transcripts',icon:FileText,iconTone:'icon-surface-reflection'},{name:'Documents',path:'/documents',icon:FolderOpen,iconTone:'icon-surface-accent'}]},{label:'Professional',items:[{name:'CPD',path:'/supervision',icon:GraduationCap,iconTone:'icon-surface-reflection'}]}],pageTitles={'/overview':'Overview','/calendar':'Calendar','/schedule':'Schedule appointment','/clients':'Clients','/transcripts':'Transcripts','/documents':'Documents','/supervision':'CPD','/settings':'Settings'},currentPageName=computed(()=>pageTitles[route.path]||route.meta?.title||'Workspace');
const BrandLockup=defineComponent({setup(){return()=>h(RouterLink,{to:'/',class:'flex items-center gap-2.5 rounded-control','aria-label':'Helios home'},()=>[h('div',{class:'icon-surface icon-surface-reflection rounded-pill'},[h(Sun,{class:'workspace-icon'})]),h('div',{class:'leading-none'},[h('p',{class:'font-serif text-[1.35rem] font-semibold text-ink'},'Helios'),h('p',{class:'text-[0.58rem] uppercase tracking-[0.16em] text-ink-muted mt-1'},'Practice')])])}});const SidebarNavigation=defineComponent({props:{groups:Array,currentPath:String},emits:['navigate'],setup(props,{emit}){return()=>h('nav',{class:'sidebar-navigation flex-1 min-h-0 overflow-y-auto px-3 py-4 space-y-5'},props.groups.map(g=>h('section',[h('p',{class:'px-3 mb-2 type-eyebrow text-ink-subtle'},g.label),h('div',{class:'space-y-1'},g.items.map(i=>h(RouterLink,{to:i.path,onClick:()=>emit('navigate'),class:['flex items-center gap-2.5 min-h-touch px-2.5 rounded-control type-ui',props.currentPath===i.path||props.currentPath.startsWith(`${i.path}/`)?'bg-state-selected text-ink font-semibold':'text-ink-secondary hover:bg-surface-subtle']},()=>[h('span',{class:['icon-surface !h-7 !w-7',i.iconTone]},[h(i.icon,{class:'workspace-icon-sm'})]),h('span',i.name)])))])]))}});const SidebarAccount=defineComponent({props:{account:Object},emits:['sign-out'],setup(props,{emit}){const open=ref(false);return()=>h('div',{class:'relative shrink-0 border-t border-border-muted px-3 py-2 bg-sidebar'},[open.value?h('div',{class:'absolute left-3 right-3 bottom-[3.35rem] rounded-panel border bg-surface-overlay p-1.5 z-50'},[h(RouterLink,{to:'/settings',class:'flex items-center gap-2.5 min-h-touch px-3'},()=>[h(Settings,{class:'workspace-icon-sm'}),'Settings']),h('button',{onClick:()=>emit('sign-out'),class:'flex items-center gap-2.5 min-h-touch px-3'},[h(LogOut,{class:'workspace-icon-sm'}),'Sign out'])]):null,h('button',{onClick:()=>open.value=!open.value,class:'w-full min-h-touch flex items-center gap-3 px-2 rounded-control text-left hover:bg-surface-subtle'},[h('div',{class:'h-8 w-8 rounded-pill bg-action-primary flex items-center justify-center type-metadata font-semibold text-on-action'},props.account.initials),h('p',{class:'type-ui font-semibold text-ink truncate flex-1'},props.account.name),h(MoreHorizontal,{class:'workspace-icon text-ink-muted'})])])}});
</script>
<style scoped>.slide-enter-active,.slide-leave-active{transition:transform .25s ease-out}.slide-enter-from,.slide-leave-to{transform:translateX(-100%)}.fade-enter-active,.fade-leave-active{transition:opacity .2s ease-out}.fade-enter-from,.fade-leave-to{opacity:0}.sidebar-navigation{scrollbar-width:none}.sidebar-navigation::-webkit-scrollbar{display:none}</style>
